// Initial template generated by Claude, with wiring up, edits, and function edits done manually with AI guidance
<template>
  <div class="container-fluid px-4 py-4">

    <div class="d-flex justify-content-between align-items-center mb-5">
      <div>
        <h2 class="mb-1" style="color:#1b4d1b;font-weight:600;font-size:1.75rem;">Welcome back</h2>
        <p class="mb-0" style="color:#6b7280;font-size:0.9375rem;">{{ today }}</p>
      </div>
      <RouterLink :to="`/diary?date=${todayIso}`" class="btn fw-semibold"
                  style="background:#1b4d1b;color:#ffffff;border:none;padding:0.625rem 1.5rem;border-radius:8px;font-size:0.9375rem;">
        + Log Meal
      </RouterLink>
    </div>

    <div v-if="error" class="alert alert-danger mb-4" style="border-radius:8px;">{{ error }}</div>

    <div class="row g-3 mb-4">

      <div class="col-md-5">
        <div class="h-100 p-3 rounded"
             style="background:#fff;box-shadow:0 1px 3px rgba(0,0,0,0.08);border-radius:12px;border:0.75px solid #1b4d1b;">
          <h6 class="mb-3" style="color:#1b4d1b;font-weight:600;font-size:0.875rem;letter-spacing:0.01em;">Calories Today</h6>
          <div v-if="loading" class="text-center py-3" style="color:#9ca3af;"><small>Loading…</small></div>
          <template v-else>
            <div class="d-flex justify-content-between align-items-end mb-3">
              <div>
                <span class="fw-bold" style="font-size:2rem;color:#1b4d1b;line-height:1;">
                  {{ Math.round(caloriesToday) }}
                </span>
                <span class="ms-2" style="color:#6b7280;font-size:0.875rem;">eaten</span>
              </div>
              <div class="text-end">
                <span class="fw-bold" style="font-size:1.25rem;"
                      :style="`color:${caloriesRemaining < 0 ? '#d94f4f' : '#1b4d1b'};`">
                  {{ Math.abs(caloriesRemaining) }}
                </span>
                <span class="ms-1" style="color:#6b7280;font-size:0.875rem;">
                  {{ caloriesRemaining < 0 ? 'over' : 'remaining' }}
                </span>
              </div>
            </div>
            <div class="mb-3" style="height:8px;background:#f3f4f6;border-radius:6px;overflow:hidden;">
              <div style="height:100%;border-radius:6px;transition:width 0.5s;"
                   :style="`width:${Math.min(caloriePercent, 100)}%;background:${caloriePercent > 100 ? '#d94f4f' : '#2e7d32'};`">
              </div>
            </div>
            <div class="row g-2 text-center">
              <div v-for="m in macroSummary" :key="m.code" class="col-4">
                <div class="p-2 rounded" style="background:#f9fafb;">
                  <div class="fw-bold mb-1" style="color:#1b4d1b;font-size:1rem;">{{ m.amount }}{{ m.unit }}</div>
                  <div style="font-size:0.75rem;color:#6b7280;">{{ m.label }}</div>
                  <div style="height:3px;background:#e5e7eb;border-radius:2px;margin-top:6px;overflow:hidden;">
                    <div style="height:100%;border-radius:2px;background:#2e7d32;transition:width 0.5s;"
                         :style="`width:${m.pct}%;`"></div>
                  </div>
                </div>
              </div>
            </div>
            <div class="text-center mt-2" style="font-size:0.75rem;color:#9ca3af;">
              Daily goal: {{ calorieBudget }} kcal
            </div>
          </template>
        </div>
      </div>

      <div class="col-md-7">
        <div class="h-100 p-3 rounded"
             style="background:#fff;box-shadow:0 1px 3px rgba(0,0,0,0.08);border-radius:12px;border:0.75px solid #1b4d1b;">
          <h6 class="mb-3" style="color:#1b4d1b;font-weight:600;font-size:0.875rem;letter-spacing:0.01em;">This Week's Calories</h6>
          <div v-if="loading" class="text-center py-3" style="color:#9ca3af;"><small>Loading…</small></div>
          <template v-else>
            <div class="d-flex align-items-end gap-2" style="height:100px;">
              <div v-for="bar in weekBars" :key="bar.date"
                   class="d-flex flex-column align-items-center"
                   style="flex:1;">
                <span style="font-size:0.7rem;margin-bottom:4px;font-weight:600;"
                      :style="`color:${bar.over ? '#d94f4f' : bar.val === '-' ? '#d1d5db' : '#1b4d1b'};`">
                  {{ bar.val }}
                </span>
                <div style="width:100%;border-radius:6px 6px 0 0;transition:height 0.4s;min-height:4px;"
                     :style="`height:${bar.height}px;background:${bar.isToday ? '#2e7d32' : bar.over ? '#fecaca' : '#f3f4f6'};`">
                </div>
              </div>
            </div>
            <div class="d-flex justify-content-end mt-2">
              <span style="font-size:0.75rem;color:#9ca3af;">
                Goal: {{ calorieBudget }} kcal/day
              </span>
            </div>
            <div class="d-flex gap-2 mt-2">
              <div v-for="bar in weekBars" :key="bar.date + '-label'"
                   class="text-center" style="flex:1;">
                <span style="font-size:0.75rem;"
                      :style="`color:${bar.isToday ? '#1b4d1b' : '#6b7280'};font-weight:${bar.isToday ? '600' : '400'};`">
                  {{ bar.day }}
                </span>
              </div>
            </div>
          </template>
        </div>
      </div>

    </div>

    <h5 class="fw-bold mb-3" style="color:#1b4d1b;">Your Overview</h5>

    <div class="row g-3 mb-4">

      <div class="col-md-6">
        <RouterLink :to="`/diary?date=${todayIso}`" class="text-decoration-none">
          <div class="h-100 p-3 rounded" style="background:#fff;box-shadow:0 1px 3px rgba(0,0,0,0.08);border-radius:12px;border:0.75px solid #1b4d1b;cursor:pointer;transition:all 0.2s;"
               @mouseenter="$event.currentTarget.style.boxShadow='0 4px 12px rgba(0,0,0,0.12)';$event.currentTarget.style.transform='translateY(-2px)'"
               @mouseleave="$event.currentTarget.style.boxShadow='0 1px 3px rgba(0,0,0,0.08)';$event.currentTarget.style.transform='translateY(0)'">
            <div class="d-flex justify-content-between align-items-center mb-2">
              <h6 class="mb-0" style="color:#1b4d1b;font-weight:600;font-size:0.875rem;">Food Diary</h6>
              <span style="color:#2e7d32;font-size:0.8125rem;font-weight:500;">View All →</span>
            </div>
            <div v-if="loading" class="py-2 text-center" style="color:#9ca3af;"><small>Loading…</small></div>
            <ul v-else-if="foodDiaryPreview.length > 0" class="list-unstyled mb-0">
              <li v-for="entry in foodDiaryPreview" :key="entry.diaryEntryId"
                  class="d-flex justify-content-between align-items-center py-2"
                  style="border-bottom:1px solid #f3f4f6;">
                <span class="fw-semibold text-capitalize" style="color:#1b4d1b;font-size:0.875rem;">{{ entry.mealType }}</span>
                <span class="badge rounded-pill" style="background:#f3f4f6;color:#6b7280;font-weight:500;font-size:0.75rem;padding:0.25rem 0.625rem;">
                  {{ entry.items?.length ?? 0 }} {{ (entry.items?.length ?? 0) === 1 ? 'item' : 'items' }}
                </span>
              </li>
            </ul>
            <div v-else class="py-3 text-center" style="color:#9ca3af;">
              <p class="mb-0" style="font-size:0.8125rem;">No meals logged today yet.</p>
            </div>
          </div>
        </RouterLink>
      </div>

      <div class="col-md-6">
        <RouterLink :to="`/nutrition?date=${todayIso}`" class="text-decoration-none">
          <div class="h-100 p-3 rounded" style="background:#fff;box-shadow:0 1px 3px rgba(0,0,0,0.08);border-radius:12px;border:0.75px solid #1b4d1b;cursor:pointer;transition:all 0.2s;"
               @mouseenter="$event.currentTarget.style.boxShadow='0 4px 12px rgba(0,0,0,0.12)';$event.currentTarget.style.transform='translateY(-2px)'"
               @mouseleave="$event.currentTarget.style.boxShadow='0 1px 3px rgba(0,0,0,0.08)';$event.currentTarget.style.transform='translateY(0)'">
            <div class="d-flex justify-content-between align-items-center mb-2">
              <h6 class="mb-0" style="color:#1b4d1b;font-weight:600;font-size:0.875rem;">Nutrition Today</h6>
              <span style="color:#2e7d32;font-size:0.8125rem;font-weight:500;">Details →</span>
            </div>
            <div v-if="loading" class="text-center py-2" style="color:#9ca3af;"><small>Loading…</small></div>
            <div v-else-if="nutritionPreview.length > 0">
              <div v-for="n in nutritionPreview" :key="n.code" class="mb-2">
                <div class="d-flex justify-content-between mb-1">
                  <span class="fw-semibold" style="color:#1b4d1b;font-size:0.8125rem;">{{ nutrientLabels[n.code] ?? n.name }}</span>
                  <span style="color:#2e7d32;font-size:0.8125rem;font-weight:500;">{{ formatAmount(n) }}</span>
                </div>
                <div style="height:5px;background:#f3f4f6;border-radius:4px;overflow:hidden;">
                  <div style="height:100%;border-radius:4px;background:#2e7d32;transition:width 0.4s;"
                       :style="`width:${nutrientPercent(n)}%;`"></div>
                </div>
              </div>
            </div>
            <div v-else class="text-center py-3" style="color:#9ca3af;">
              <p class="mb-0" style="font-size:0.8125rem;">No data yet. Log meals to see your breakdown.</p>
            </div>
          </div>
        </RouterLink>
      </div>

    </div>

    <div class="row g-3 mb-4">

      <div class="col-md-6">
        <RouterLink to="/goals" class="text-decoration-none">
          <div class="h-100 p-3 rounded" style="background:#fff;box-shadow:0 1px 3px rgba(0,0,0,0.08);border-radius:12px;border:0.75px solid #1b4d1b;cursor:pointer;transition:all 0.2s;"
               @mouseenter="$event.currentTarget.style.boxShadow='0 4px 12px rgba(0,0,0,0.12)';$event.currentTarget.style.transform='translateY(-2px)'"
               @mouseleave="$event.currentTarget.style.boxShadow='0 1px 3px rgba(0,0,0,0.08)';$event.currentTarget.style.transform='translateY(0)'">
            <div class="d-flex justify-content-between align-items-center mb-2">
              <h6 class="mb-0" style="color:#1b4d1b;font-weight:600;font-size:0.875rem;">Goals & Progress</h6>
              <span style="color:#2e7d32;font-size:0.8125rem;font-weight:500;">View All →</span>
            </div>
            <div v-if="loadingGoals" class="text-center py-2" style="color:#9ca3af;"><small>Loading…</small></div>
            <div v-else-if="goals.length === 0" class="text-center py-3" style="color:#9ca3af;">
              <p class="mb-0" style="font-size:0.8125rem;">No active goals yet.</p>
            </div>
            <div v-else>
              <div v-for="goal in goals.slice(0, 3)" :key="goal.goalId"
                   class="d-flex justify-content-between align-items-center py-2"
                   style="border-bottom:1px solid #f3f4f6;">
                <div>
                  <div class="fw-semibold mb-1" style="color:#1b4d1b;font-size:0.875rem;">
                    {{ goal.nutrient?.name ?? goal.notes ?? 'Custom goal' }}
                  </div>
                  <div style="color:#6b7280;font-size:0.75rem;">{{ goalRange(goal) }}</div>
                </div>
                <span class="badge rounded-pill"
                      :style="`background:${goal.source === 'professional_defined' ? '#2e7d32' : '#f3f4f6'};color:${goal.source === 'professional_defined' ? '#fff' : '#6b7280'};font-weight:500;font-size:0.75rem;padding:0.25rem 0.625rem;`">
                  {{ goal.source === 'professional_defined' ? 'Pro' : 'Personal' }}
                </span>
              </div>
              <div v-if="goals.length > 3" class="text-center mt-2" style="color:#9ca3af;font-size:0.75rem;">
                +{{ goals.length - 3 }} more
              </div>
            </div>
          </div>
        </RouterLink>
      </div>

      <div class="col-md-6">
        <RouterLink to="/messages" class="text-decoration-none">
          <div class="h-100 p-3 rounded" style="background:#fff;box-shadow:0 1px 3px rgba(0,0,0,0.08);border-radius:12px;border:0.75px solid #1b4d1b;cursor:pointer;transition:all 0.2s;"
               @mouseenter="$event.currentTarget.style.boxShadow='0 4px 12px rgba(0,0,0,0.12)';$event.currentTarget.style.transform='translateY(-2px)'"
               @mouseleave="$event.currentTarget.style.boxShadow='0 1px 3px rgba(0,0,0,0.08)';$event.currentTarget.style.transform='translateY(0)'">
            <div class="d-flex justify-content-between align-items-center mb-2">
              <h6 class="mb-0" style="color:#1b4d1b;font-weight:600;font-size:0.875rem;">Professional Support</h6>
              <span style="color:#2e7d32;font-size:0.8125rem;font-weight:500;">Messages →</span>
            </div>
            <div v-if="loadingPro" class="text-center py-2" style="color:#9ca3af;"><small>Loading…</small></div>
            <template v-else>
              <div v-if="professional" class="d-flex align-items-center gap-2 mb-2">
                <div class="avatar-circle flex-shrink-0" style="width:40px;height:40px;font-size:0.875rem;">
                  {{ initialsFor(professional.professional.fullName) }}
                </div>
                <div>
                  <div class="fw-semibold mb-1" style="color:#1b4d1b;font-size:0.875rem;">{{ professional.professional.fullName }}</div>
                  <div style="color:#6b7280;font-size:0.75rem;">Your assigned nutritionist</div>
                </div>
              </div>
              <div v-for="inv in pendingInvites" :key="inv.professionalId ?? inv.id"
                   class="p-2 rounded mb-2" style="background:#fffbf0;border:1px solid #fbbf24;">
                <div class="fw-semibold mb-1" style="color:#1b4d1b;font-size:0.8125rem;">
                  {{ inv.professional?.fullName ?? 'A nutritionist' }} has invited you
                </div>
                <div class="mb-2" style="color:#6b7280;font-size:0.75rem;">Would you like to accept this invitation?</div>
                <div class="d-flex gap-2">
                  <button class="btn btn-sm fw-semibold"
                          style="background:#2e7d32;color:#fff;border:none;padding:0.375rem 0.75rem;border-radius:6px;font-size:0.75rem;"
                          @click.prevent="respondToInvite(inv.professionalId ?? inv.professional?.userId, 'accept')">
                    Accept
                  </button>
                  <button class="btn btn-sm"
                          style="background:#f3f4f6;color:#6b7280;border:none;padding:0.375rem 0.75rem;border-radius:6px;font-size:0.75rem;"
                          @click.prevent="respondToInvite(inv.professionalId ?? inv.professional?.userId, 'reject')">
                    Decline
                  </button>
                </div>
              </div>
              <div v-if="!professional && pendingInvites.length === 0" class="text-center py-3" style="color:#9ca3af;">
                <p class="mb-0" style="font-size:0.8125rem;">No nutritionist linked yet.</p>
              </div>
            </template>
          </div>
        </RouterLink>
      </div>

    </div>

    <div class="mb-3">
      <h5 style="color:#1b4d1b;font-weight:600;font-size:1rem;margin-bottom:1rem;">My Favourite Recipes</h5>
    </div>

    <div v-if="loadingFavs" class="text-center py-5" style="color:#9ca3af;">
      <small>Loading favourites…</small>
    </div>

    <div v-else-if="favourites.length > 0">
      <div class="row g-4 mb-4">
        <div v-for="recipe in favourites.slice(0, 3)" :key="recipe.recipeId" class="col-md-4">
          <div class="h-100 rounded" style="background:#fff;box-shadow:0 1px 3px rgba(0,0,0,0.08);border-radius:12px;border:0.75px solid #1b4d1b;overflow:hidden;transition:all 0.2s;cursor:pointer;"
               @mouseenter="$event.currentTarget.style.boxShadow='0 4px 12px rgba(0,0,0,0.12)';$event.currentTarget.style.transform='translateY(-2px)'"
               @mouseleave="$event.currentTarget.style.boxShadow='0 1px 3px rgba(0,0,0,0.08)';$event.currentTarget.style.transform='translateY(0)'">
            <div style="position:relative;overflow:hidden;height:160px;">
              <img :src="recipe.image || '/src/assets/hero.png'" :alt="recipe.title"
                   style="width:100%;height:100%;object-fit:cover;" />
              <span v-if="recipe.category"
                    class="position-absolute top-0 start-0 m-2"
                    style="background:#2e7d32;color:#fff;padding:0.25rem 0.5rem;border-radius:6px;font-size:0.7rem;font-weight:500;">
                {{ recipe.category }}
              </span>
              <span class="position-absolute top-0 end-0 m-2" style="color:#d94f4f;font-size:1.125rem;">♥</span>
            </div>
            <div class="p-3">
              <div class="fw-semibold mb-1" style="color:#1b4d1b;font-size:0.875rem;line-height:1.3;">{{ recipe.title }}</div>
              <div class="mb-2" style="color:#6b7280;font-size:0.75rem;">
                {{ recipe.kcal }} kcal · P:{{ recipe.protein }}g · C:{{ recipe.carbs }}g · F:{{ recipe.fat }}g
              </div>
              <div v-if="recipe.averageRating != null" class="mb-2" style="font-size:0.75rem;color:#fbbf24;">
                {{ '★'.repeat(Math.round(recipe.averageRating)) }}{{ '☆'.repeat(5 - Math.round(recipe.averageRating)) }}
                <span style="color:#9ca3af;">({{ recipe.reviewCount }})</span>
              </div>
              <RouterLink :to="`/recipes?highlight=${recipe.recipeId}`"
                          class="btn w-100" style="background:#f3f4f6;color:#1b4d1b;border:none;padding:0.5rem;border-radius:8px;font-size:0.8125rem;font-weight:500;text-decoration:none;">
                View Recipe →
              </RouterLink>
            </div>
          </div>
        </div>
      </div>

      <div v-if="favourites.length > 3" class="text-center mb-4">
        <RouterLink to="/recipes" class="btn fw-semibold"
                    style="background:#f3f4f6;color:#1b4d1b;border:none;padding:0.625rem 1.5rem;border-radius:8px;font-size:0.875rem;">
          View all {{ favourites.length }} favourites →
        </RouterLink>
      </div>
    </div>

    <div v-else class="text-center py-5 rounded mb-4"
         style="background:#f9fafb;border:2px dashed #e5e7eb;">
      <p class="mb-3" style="color:#6b7280;font-size:0.9375rem;">You haven't saved any favourite recipes yet.</p>
      <RouterLink to="/recipes" class="btn fw-semibold"
                  style="background:#1b4d1b;color:#ffffff;border:none;padding:0.625rem 1.5rem;border-radius:8px;font-size:0.875rem;">
        Browse Recipe Library
      </RouterLink>
    </div>

  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { apiFetch } from '../auth.js'

const today = new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })

const dashboard = ref(null)
const loading = ref(true)
const error = ref('')

const professional = ref(null)
const pendingInvites = ref([])
const loadingPro = ref(true)

const goals = ref([])
const loadingGoals = ref(true)

const favourites = ref([])
const loadingFavs = ref(true)

const calorieBudget = computed(() => {
  const goal = goals.value.find(g =>
    g.status === 'active' && g.nutrient?.code === 'calories' && g.targetMax != null
  )
  return goal ? Number(goal.targetMax) : 2000
})

onMounted(async () => {
  await Promise.all([loadDashboard(), loadProfessional(), loadGoals(), loadFavourites()])
})

async function loadDashboard() {
  loading.value = true
  try {
    const res = await apiFetch('/api/diary/dashboard')
    const data = await res.json().catch(() => ({}))
    if (!res.ok) {
      error.value = data.message || data.error || 'Failed to load dashboard'
      return
    }
    dashboard.value = data.dashboardData ?? data
  } catch {
    error.value = 'Network error - could not load dashboard'
  } finally {
    loading.value = false
  }
}

async function loadProfessional() {
  loadingPro.value = true
  try {
    const [proRes, inviteRes] = await Promise.all([
      apiFetch('/api/client/professionals'),
      apiFetch('/api/client/client-invitations'),
    ])
    const proData = await proRes.json().catch(() => ({}))
    if (proRes.ok) professional.value = (proData.professionals ?? [])[0] ?? null
    const inviteData = await inviteRes.json().catch(() => ({}))
    if (inviteRes.ok) pendingInvites.value = inviteData.invitations ?? []
  } catch {
  } finally {
    loadingPro.value = false
  }
}

async function respondToInvite(professionalId, action) {
  try {
    const res = await apiFetch(`/api/client/client-invitations/${professionalId}/${action}`, { method: 'POST' })
    if (res.ok) await loadProfessional()
  } catch {
  }
}

async function loadGoals() {
  loadingGoals.value = true
  try {
    const res = await apiFetch('/api/goals?effective=true')
    const data = await res.json().catch(() => ({}))
    if (res.ok) goals.value = data.goals ?? []
  } catch {
  } finally {
    loadingGoals.value = false
  }
}

async function loadFavourites() {
  loadingFavs.value = true
  try {
    const res = await apiFetch('/api/recipes/favorites')
    const data = await res.json().catch(() => ({}))
    if (res.ok) favourites.value = data.recipes ?? []
  } catch {
  } finally {
    loadingFavs.value = false
  }
}


const quickStats = computed(() => dashboard.value?.quickStats ?? {})
const foodDiaryPreview = computed(() => (dashboard.value?.foodDiaryPreview ?? []).filter(e => (e.items?.length ?? 0) > 0))
const nutritionPreview = computed(() => dashboard.value?.nutritionPreview ?? [])
const caloriesToday = computed(() => quickStats.value.calories_today ?? 0)
const caloriePercent = computed(() => Math.round((caloriesToday.value / calorieBudget.value) * 100))
const caloriesRemaining = computed(() => calorieBudget.value - Math.round(caloriesToday.value))

const MACRO_REFS = { protein: { label: 'Protein', ref: 50, unit: 'g' }, carbohydrates: { label: 'Carbs', ref: 260, unit: 'g' }, fat: { label: 'Fat', ref: 70, unit: 'g' } }
const nutrientLabels = { protein: 'Protein', carbohydrates: 'Carbs', fat: 'Fat', fibre: 'Fibre' }

const macroSummary = computed(() =>
  Object.entries(MACRO_REFS).map(([code, meta]) => {
    const n = nutritionPreview.value.find(x => x.code === code)
    const amount = Math.round(Number(n?.totalAmount ?? 0))
    return {
      code,
      label: meta.label,
      unit: meta.unit,
      amount,
      pct: Math.min(Math.round((amount / meta.ref) * 100), 100),
    }
  })
)

const WEEK_DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
const MAX_BAR_H = 72
const todayIso = new Date().toISOString().slice(0, 10)

const weekBars = computed(() => {
  const trend = dashboard.value?.weeklyCaloryTrend ?? []
  if (!trend.length) {
    return WEEK_DAYS.map(day => ({ day, date: '', val: '-', height: 0, over: false, isToday: false }))
  }
  const maxCal = Math.max(...trend.map(d => d.calories), calorieBudget.value)
  return trend.map((d, dayIndex) => {
    const cal = Math.round(d.calories)
    const isToday = d.date === todayIso
    return {
      day: isToday ? 'Today' : (WEEK_DAYS[dayIndex] ?? d.date.slice(5)),
      date: d.date,
      val: cal > 0 ? String(cal) : '-',
      height: cal > 0 ? Math.max(3, Math.round((cal / maxCal) * MAX_BAR_H)) : 0,
      over: cal > calorieBudget.value,
      isToday,
    }
  })
})

function nutrientPercent(n) {
  const meta = MACRO_REFS[n.code]
  if (!meta) return 0
  return Math.min(Math.round((Number(n.totalAmount) / meta.ref) * 100), 100)
}

function formatAmount(n) {
  const value = Number(n.totalAmount ?? 0)
  const unit = n.unit ?? 'g'
  return `${Math.round(value)}${unit}`
}

function initialsFor(name) {
  if (!name) return '?'
  return name.trim().split(/\s+/).slice(0, 2).map(p => p[0].toUpperCase()).join('') || '?'
}

function goalRange(goal) {
  const min = goal.targetMin
  const max = goal.targetMax
  const unit = goal.nutrient?.unit ? ` ${goal.nutrient.unit}` : ''
  if (min != null && max != null) return `${min}–${max}${unit}`
  if (min != null) return `≥ ${min}${unit}`
  if (max != null) return `≤ ${max}${unit}`
  return 'Custom goal'
}
</script>
