// Initial template generated by Claude, with wiring up, edits, and function edits done manually with AI guidance
<template>
  <div class="container-fluid px-4 py-3">

    <div class="p-3 mb-3 rounded d-flex justify-content-between align-items-center"
         style="background:#e8f4e6;border:1px solid #5a9e56;">
      <div>
        <h4 style="color:#5a9e56;" class="mb-0">Food Diary</h4>
        <small class="text-secondary">{{ formattedDate }} - Log everything you eat and drink today</small>
      </div>

      <div class="d-flex align-items-center gap-2">
        <button class="btn btn-outline-secondary btn-sm" @click="handlePrevDay">‹</button>
        <span class="border rounded px-3 py-1 bg-white small">{{ formattedDate }}</span>
        <button class="btn btn-outline-secondary btn-sm" @click="handleNextDay">›</button>
      </div>
    </div>

    <div v-if="diaryLoading" class="text-center text-muted py-3">Loading diary…</div>
    <div v-if="diaryError" class="alert alert-danger py-2">{{ diaryError }}</div>

    <div class="card border mb-3 p-3">
      <div class="d-flex flex-wrap gap-4 align-items-center">
        <div>
          <div class="stat-label">Today's Total</div>
          <div class="stat-value">{{ headerTotals.kcal }} kcal</div>
        </div>
        <div>
          <div class="stat-label">Remaining</div>
          <div class="stat-value" :class="caloriesRemaining < 0 ? 'text-danger' : 'text-success'">
            {{ caloriesRemaining }} kcal
          </div>
        </div>
        <div><div class="stat-label">Protein</div><div class="stat-value">{{ headerTotals.protein }}g</div></div>
        <div><div class="stat-label">Carbs</div><div class="stat-value">{{ headerTotals.carbs }}g</div></div>
        <div><div class="stat-label">Fat</div><div class="stat-value">{{ headerTotals.fat }}g</div></div>
        <div><div class="stat-label">Fibre</div><div class="stat-value">{{ headerTotals.fibre }}g</div></div>
        <div><div class="stat-label">Sugar</div><div class="stat-value">{{ headerTotals.sugar }}g</div></div>
        <div><div class="stat-label">Salt</div><div class="stat-value">{{ headerTotals.salt }}g</div></div>
        <div class="ms-auto">
          <RouterLink to="/nutrition" class="btn btn-gf-outline btn-sm" style="white-space:nowrap;">
            Nutrition Analysis
          </RouterLink>
        </div>
      </div>
    </div>

    <div v-for="meal in mainMeals" :key="meal.id" class="mb-4">

      <div class="meal-section-header d-flex justify-content-between">
        <span>{{ meal.label.toUpperCase() }}</span>
        <span>Total: {{ meal.entries.reduce((s, e) => s + (e.kcal || 0), 0) }} kcal</span>
      </div>

      <div v-for="entry in meal.entries" :key="entry.itemId" class="diary-entry-row mt-1">

        <div v-if="editingItem?.itemId !== entry.itemId"
             class="d-flex justify-content-between align-items-start">
          <div>
            <div class="fw-semibold small">{{ entry.name }}</div>
            <div style="font-size:0.75rem;color:#666;">{{ entry.detail }} · qty {{ entry.quantity }}</div>
          </div>
          <div class="d-flex align-items-center gap-2">
            <span class="small text-muted">Carbs: {{ entry.carbs }}g</span>
            <span class="small text-muted">Protein: {{ entry.protein }}g</span>
            <span class="small text-muted">Fat: {{ entry.fat }}g</span>
            <span class="small text-muted">Sugar: {{ entry.sugar }}g</span>
            <span class="small text-muted">Salt: {{ entry.salt }}g</span>
            <span class="fw-bold text-success small">{{ entry.kcal }} kcal</span>
            <button class="btn btn-gf-outline btn-sm py-0 px-1" title="Edit entry"
                    @click="startEditItem(entry)">Edit</button>
            <button class="btn btn-sm py-0 px-1"
                    style="background:#fde8e8;border:1px solid #d99;color:#c44;"
                    title="Remove entry"
                    :disabled="removingItemId === entry.itemId"
                    @click="handleRemoveItem(entry.itemId)">
              {{ removingItemId === entry.itemId ? '…' : 'Remove' }}
            </button>
          </div>
        </div>

        <div v-else class="p-2 rounded" style="background:#f0f7ef;border:1px solid #5a9e56;">
          <div class="row g-2 mb-2 align-items-end">
            <div class="col-auto">
              <div class="small fw-semibold mb-1">{{ entry.name }}</div>
              <div class="text-muted" style="font-size:0.75rem;">{{ entry.detail }}</div>
            </div>
            <div class="col-md-2">
              <label class="form-label form-label-sm">Quantity (servings)</label>
              <input type="number" min="0.1" step="0.1" class="form-control form-control-sm" v-model.number="editQty">
            </div>
          </div>
          <div v-if="editError" class="text-danger small mb-1">{{ editError }}</div>
          <div class="d-flex gap-2">
            <button class="btn btn-gf btn-sm" :disabled="editSaving" @click="saveEditItem(entry.itemId)">
              {{ editSaving ? 'Saving…' : 'Save' }}
            </button>
            <button class="btn btn-outline-secondary btn-sm" @click="editingItem = null">Cancel</button>
          </div>
        </div>

      </div>

      <div v-if="meal.entries.length === 0"
           class="border rounded p-3 text-center text-muted my-1"
           style="border-style:dashed!important;">
        <small>Nothing logged yet for {{ meal.label.toLowerCase() }} - use the panel below to add</small>
      </div>

      <div class="mt-2">
        <button class="btn btn-gf-outline btn-sm"
                @click="openPanel === meal.id ? openPanel = null : (openPanel = meal.id, activeTab[meal.id] === 'recipes' && loadDiaryRecipes())">
          {{ openPanel === meal.id ? 'Close' : 'Add to ' + meal.label }}
        </button>
      </div>

      <div v-if="openPanel === meal.id" class="add-meal-panel mt-2">

        <div class="d-flex gap-2 mb-3">
          <button v-for="tab in addTabs" :key="tab.id"
                  class="btn btn-sm"
                  :class="activeTab[meal.id] === tab.id ? 'btn-gf' : 'btn-gf-outline'"
                  @click="activeTab[meal.id] = tab.id; if (tab.id === 'recipes') loadDiaryRecipes()">
            {{ tab.label }}
          </button>
        </div>

        <div v-if="activeTab[meal.id] === 'custom'">
          <div class="row g-2 mb-2">
            <div class="col-md-4">
              <label class="form-label form-label-sm">Food Name</label>
              <input type="text" class="form-control form-control-sm" placeholder="e.g. Porridge"
                     v-model="customForm[meal.id].name">
            </div>
            <div class="col-md-2">
              <label class="form-label form-label-sm">Calories (kcal)</label>
              <input type="number" class="form-control form-control-sm" v-model.number="customForm[meal.id].kcal">
            </div>
            <div class="col-md-2">
              <label class="form-label form-label-sm">Serving Size</label>
              <input type="text" class="form-control form-control-sm" placeholder="e.g. 100g"
                     v-model="customForm[meal.id].serving">
            </div>
          </div>
          <div class="row g-2 mb-2">
            <div class="col" v-for="field in customNutrientFields" :key="field.key">
              <label class="form-label form-label-sm">{{ field.label }}</label>
              <input type="number" class="form-control form-control-sm" v-model.number="customForm[meal.id][field.key]">
            </div>
          </div>
          <div v-if="customError[meal.id]" class="text-danger small mb-1">{{ customError[meal.id] }}</div>
          <div class="d-flex gap-2">
            <button class="btn btn-gf btn-sm" :disabled="customSaving[meal.id]" @click="handleAddCustom(meal.id)">
              {{ customSaving[meal.id] ? 'Adding…' : 'Add Entry' }}
            </button>
          </div>
        </div>

        <div v-if="activeTab[meal.id] === 'saved'">
          <div class="d-flex gap-2 mb-2">
            <input type="text" class="form-control form-control-sm"
                   placeholder="Search food database…"
                   v-model="mealSearchQuery[meal.id]"
                   @keyup.enter="searchMealFood(meal.id)">
            <button class="btn btn-gf btn-sm px-3"
                    :disabled="mealSearchLoading[meal.id]"
                    @click="searchMealFood(meal.id)">
              {{ mealSearchLoading[meal.id] ? '…' : 'Search' }}
            </button>
          </div>
          <div v-if="mealSearchError[meal.id]" class="text-danger small mb-2">{{ mealSearchError[meal.id] }}</div>
          <div v-if="(mealSearchResults[meal.id] ?? []).length > 0"
               class="border rounded p-2 mb-2" style="background:#fff;">
            <div v-for="food in mealSearchResults[meal.id]" :key="food.food_id"
                 class="d-flex justify-content-between align-items-center py-1 border-bottom">
              <div>
                <span class="small fw-semibold">{{ food.food_name }}</span>
                <span v-if="food.brand_name" class="text-muted small ms-1">({{ food.brand_name }})</span>
                <div class="text-muted" style="font-size:0.72rem;">{{ food.food_description }}</div>
              </div>
              <button class="btn btn-gf btn-sm ms-2"
                      :disabled="mealAddingFoodId[meal.id] === food.food_id"
                      @click="handleAddMealFood(meal.id, food.food_id)">
                {{ mealAddingFoodId[meal.id] === food.food_id ? '…' : 'Add' }}
              </button>
            </div>
          </div>
        </div>

        <div v-if="activeTab[meal.id] === 'recipes'">
          <input type="text" class="form-control form-control-sm mb-2"
                 placeholder="Search recipes..."
                 v-model="recipeSearch">
          <div v-if="recipesLoading" class="text-muted small text-center py-3">Loading recipes…</div>
          <div v-else class="row g-2" style="max-height:340px;overflow-y:auto;">
            <div class="col-md-4" v-for="r in filteredRecipes" :key="r.recipeId">
              <div class="card h-100">
                <img :src="r.image || '/src/assets/hero.png'" :alt="r.title"
                     style="width:100%;height:90px;object-fit:cover;" />
                <div class="p-2">
                  <div class="small fw-bold">{{ r.title }}</div>
                  <div style="font-size:0.72rem;color:#666;">{{ r.kcal }} kcal · P:{{ r.protein }}g · C:{{ r.carbs }}g · F:{{ r.fat }}g</div>
                  <div style="font-size:0.72rem;color:#888;">{{ r.cookTime }}</div>
                  <button class="btn btn-gf btn-sm w-100 mt-1"
                          style="font-size:0.72rem;"
                          :disabled="recipeAdding[r.recipeId + meal.id]"
                          @click="handleAddRecipe(r, meal.id)">
                    {{ recipeAdding[r.recipeId + meal.id] ? 'Adding…' : 'Add (1 serving)' }}
                  </button>
                </div>
              </div>
            </div>
            <div v-if="filteredRecipes.length === 0" class="text-muted small text-center py-3 col-12">
              No recipes match.
            </div>
          </div>
        </div>

      </div>
    </div>

    <div class="mb-4">
      <div class="meal-section-header d-flex justify-content-between">
        <span>SNACKS &amp; DRINKS</span>
        <span>Total: {{ snackMeal?.entries.reduce((s, e) => s + (e.kcal || 0), 0) ?? 0 }} kcal</span>
      </div>

      <div v-for="entry in (snackMeal?.entries ?? [])" :key="entry.itemId" class="diary-entry-row mt-1">
        <div v-if="editingItem?.itemId !== entry.itemId" class="d-flex justify-content-between align-items-start">
          <div>
            <div class="fw-semibold small">{{ entry.name }}</div>
            <div style="font-size:0.75rem;color:#666;">{{ entry.detail }} · qty {{ entry.quantity }}</div>
          </div>
          <div class="d-flex align-items-center gap-2">
            <span class="small text-muted">Carbs: {{ entry.carbs }}g</span>
            <span class="small text-muted">Protein: {{ entry.protein }}g</span>
            <span class="small text-muted">Fat: {{ entry.fat }}g</span>
            <span class="small text-muted">Sugar: {{ entry.sugar }}g</span>
            <span class="small text-muted">Salt: {{ entry.salt }}g</span>
            <span class="fw-bold text-success small">{{ entry.kcal }} kcal</span>
            <button class="btn btn-gf-outline btn-sm py-0 px-1" title="Edit entry"
                    @click="startEditItem(entry)">Edit</button>
            <button class="btn btn-sm py-0 px-1"
                    style="background:#fde8e8;border:1px solid #d99;color:#c44;"
                    title="Remove entry"
                    :disabled="removingItemId === entry.itemId"
                    @click="handleRemoveItem(entry.itemId)">
              {{ removingItemId === entry.itemId ? '…' : 'Remove' }}
            </button>
          </div>
        </div>
        <div v-else class="p-2 rounded" style="background:#f0f7ef;border:1px solid #5a9e56;">
          <div class="row g-2 mb-2 align-items-end">
            <div class="col-auto">
              <div class="small fw-semibold mb-1">{{ entry.name }}</div>
              <div class="text-muted" style="font-size:0.75rem;">{{ entry.detail }}</div>
            </div>
            <div class="col-md-2">
              <label class="form-label form-label-sm">Quantity (servings)</label>
              <input type="number" min="0.1" step="0.1" class="form-control form-control-sm" v-model.number="editQty">
            </div>
          </div>
          <div v-if="editError" class="text-danger small mb-1">{{ editError }}</div>
          <div class="d-flex gap-2">
            <button class="btn btn-gf btn-sm" :disabled="editSaving" @click="saveEditItem(entry.itemId)">
              {{ editSaving ? 'Saving…' : 'Save' }}
            </button>
            <button class="btn btn-outline-secondary btn-sm" @click="editingItem = null">Cancel</button>
          </div>
        </div>
      </div>

      <div v-if="!snackMeal || snackMeal.entries.length === 0"
           class="border rounded p-3 text-center text-muted my-1"
           style="border-style:dashed!important;">
        <small>Nothing logged yet for snacks &amp; drinks</small>
      </div>

      <div class="mt-2">
        <button class="btn btn-gf-outline btn-sm"
                @click="showSnackPanel = !showSnackPanel">
          {{ showSnackPanel ? 'Close' : 'Add Snack / Drink' }}
        </button>
      </div>

      <div v-if="showSnackPanel" class="add-meal-panel mt-2">

        <div class="d-flex gap-2 mb-2">
          <input type="text" class="form-control form-control-sm"
                 placeholder="Search food or drink (e.g. banana, orange juice)..."
                 v-model="snackQuery"
                 @keyup.enter="searchSnacks">
          <button class="btn btn-gf btn-sm px-3" @click="searchSnacks" :disabled="snackLoading">
            {{ snackLoading ? '...' : 'Search' }}
          </button>
        </div>

        <div v-if="snackError" class="text-danger small mb-2">{{ snackError }}</div>

        <div v-if="snackResults.length > 0" class="border rounded p-2 mb-2" style="background:#fff;">
          <div v-for="food in snackResults" :key="food.food_id"
               class="d-flex justify-content-between align-items-center py-1 border-bottom">
            <div>
              <span class="small fw-semibold">{{ food.food_name }}</span>
              <span v-if="food.brand_name" class="text-muted small ms-1">({{ food.brand_name }})</span>
              <div class="text-muted" style="font-size:0.72rem;">{{ food.food_description }}</div>
            </div>
            <button class="btn btn-gf btn-sm ms-2" style="white-space:nowrap;"
                    :disabled="snackAddingFoodId === food.food_id"
                    @click="handleAddSnack(food.food_id)">
              {{ snackAddingFoodId === food.food_id ? '...' : 'Add' }}
            </button>
          </div>
        </div>

      </div>
    </div>


  </div>
</template>

<script setup>
import { ref, computed, watch, onMounted } from 'vue'
import {
  meals, headerTotals,
  diaryLoading, diaryError,
  viewDate, prevDay, nextDay,
  loadDiary,
  addFatSecretItem, addCustomItem, addRecipeToDiary,
  updateItem, removeItem,
} from '../diaryStore.js'
import { apiFetch } from '../auth.js'

const formattedDate = computed(() =>
  viewDate.value.toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short', year: 'numeric' })
)

const snackMeal = computed(() => meals.value.find(m => m.id === 'snack'))
const mainMeals = computed(() => meals.value.filter(m => m.id !== 'snack'))

const calorieBudget = ref(2000)

async function loadCalorieGoal() {
  try {
    const res = await apiFetch('/api/goals')
    const data = await res.json().catch(() => ({}))
    if (!res.ok) return
    const goals = data.goals ?? []
    const calorieGoal = goals.find(g =>
      g.status === 'active' && g.nutrient?.code === 'calories' && g.targetMax != null
    )
    if (calorieGoal) calorieBudget.value = Number(calorieGoal.targetMax)
  } catch {
    // non-critical, keep default 2000
  }
}

const caloriesRemaining = computed(() => calorieBudget.value - headerTotals.value.kcal)

onMounted(() => {
  loadDiary()
  loadCalorieGoal()
})
watch(viewDate, loadDiary)

function handlePrevDay() { prevDay() }
function handleNextDay() { nextDay() }

const addTabs = [
  { id: 'custom',  label: 'Custom Entry' },
  { id: 'saved',   label: 'Food Search' },
  { id: 'recipes', label: 'From Recipes' },
]

const openPanel = ref(null)

const activeTab = ref({
  breakfast: 'custom',
  lunch: 'saved',
  dinner: 'recipes',
})

const recipeSearch = ref('')
const recipeAdding = ref({})
const recipesLoading = ref(false)
const diaryRecipes = ref([])

async function loadDiaryRecipes() {
  if (diaryRecipes.value.length > 0) return
  recipesLoading.value = true
  try {
    const res = await apiFetch('/api/recipes')
    const data = await res.json().catch(() => ({}))
    if (res.ok) diaryRecipes.value = data.recipes ?? []
  } catch {
    // non-critical
  } finally {
    recipesLoading.value = false
  }
}

const filteredRecipes = computed(() => {
  if (!recipeSearch.value) return diaryRecipes.value
  const q = recipeSearch.value.toLowerCase()
  return diaryRecipes.value.filter(r => r.title.toLowerCase().includes(q))
})

async function handleAddRecipe(recipe, mealId) {
  const key = recipe.recipeId + mealId
  recipeAdding.value[key] = true
  try {
    await addRecipeToDiary(recipe, mealId)
    openPanel.value = null
  } catch (e) {
    alert(e.message)
  } finally {
    recipeAdding.value[key] = false
  }
}

function blankCustomForm() {
  return { name: '', kcal: null, serving: '', protein: null, carbs: null, fat: null, fibre: null, sugar: null, salt: null }
}

const customForm = ref({
  breakfast: blankCustomForm(),
  lunch: blankCustomForm(),
  dinner: blankCustomForm(),
  snack: blankCustomForm(),
})
const customError = ref({})
const customSaving = ref({})
const customNutrientFields = [
  { key: 'protein', label: 'Protein (g)' },
  { key: 'carbs', label: 'Carbs (g)' },
  { key: 'fat', label: 'Fat (g)' },
  { key: 'fibre', label: 'Fibre (g)' },
  { key: 'sugar', label: 'Sugar (g)' },
  { key: 'salt', label: 'Salt (g)' },
]

async function handleAddCustom(mealId) {
  const form = customForm.value[mealId]
  if (!form.name?.trim()) {
    customError.value[mealId] = 'Food name is required.'
    return
  }
  customError.value[mealId] = ''
  customSaving.value[mealId] = true
  try {
    await addCustomItem({ mealType: mealId, ...form })
    customForm.value[mealId] = blankCustomForm()
    openPanel.value = null
  } catch (e) {
    customError.value[mealId] = e.message
  } finally {
    customSaving.value[mealId] = false
  }
}

const mealSearchQuery = ref({})
const mealSearchLoading = ref({})
const mealSearchError = ref({})
const mealSearchResults = ref({})
const mealAddingFoodId = ref({})

async function searchMealFood(mealId) {
  const q = mealSearchQuery.value[mealId]?.trim()
  if (!q) return
  mealSearchLoading.value[mealId] = true
  mealSearchError.value[mealId] = ''
  mealSearchResults.value[mealId] = []
  try {
    const res = await apiFetch(`/api/search?query=${encodeURIComponent(q)}`)
    const data = await res.json()
    const foods = data?.foods?.food
    if (!foods) {
      mealSearchError.value[mealId] = 'No results found.'
      return
    }
    mealSearchResults.value[mealId] = Array.isArray(foods) ? foods : [foods]
  } catch {
    mealSearchError.value[mealId] = 'Search failed.'
  } finally {
    mealSearchLoading.value[mealId] = false
  }
}

async function handleAddMealFood(mealId, food_id) {
  mealAddingFoodId.value[mealId] = food_id
  try {
    await addFatSecretItem({ mealType: mealId, food_id })
    mealSearchResults.value[mealId] = []
    mealSearchQuery.value[mealId] = ''
    openPanel.value = null
  } catch (e) {
    mealSearchError.value[mealId] = e.message
  } finally {
    mealAddingFoodId.value[mealId] = null
  }
}

const showSnackPanel = ref(false)

const snackQuery = ref('')
const snackLoading = ref(false)
const snackError = ref('')
const snackResults = ref([])
const snackAddingFoodId = ref(null)

async function searchSnacks() {
  if (!snackQuery.value.trim()) return
  snackLoading.value = true
  snackError.value = ''
  snackResults.value = []
  try {
    const res = await apiFetch(`/api/search?query=${encodeURIComponent(snackQuery.value)}`)
    const data = await res.json()
    const foods = data?.foods?.food
    if (!foods) {
      snackError.value = 'No results found.'
      return
    }
    snackResults.value = Array.isArray(foods) ? foods : [foods]
  } catch {
    snackError.value = 'Search failed - is the backend running?'
  } finally {
    snackLoading.value = false
  }
}

async function handleAddSnack(food_id) {
  snackAddingFoodId.value = food_id
  try {
    await addFatSecretItem({ mealType: 'snack', food_id })
    snackResults.value = []
    snackQuery.value = ''
    showSnackPanel.value = false
  } catch (e) {
    snackError.value = e.message
  } finally {
    snackAddingFoodId.value = null
  }
}

// backend only supports updating quantity, not renaming the food after it's been saved
const editingItem = ref(null)
const editQty = ref(1)
const editSaving = ref(false)
const editError = ref('')

function startEditItem(entry) {
  editingItem.value = entry
  editQty.value = entry.quantity
  editError.value = ''
}

async function saveEditItem(itemId) {
  if (!editQty.value || editQty.value <= 0) {
    editError.value = 'Quantity must be greater than 0.'
    return
  }
  editSaving.value = true
  editError.value = ''
  try {
    await updateItem({ itemId, quantity: editQty.value })
    editingItem.value = null
  } catch (e) {
    editError.value = e.message
  } finally {
    editSaving.value = false
  }
}

const removingItemId = ref(null)

async function handleRemoveItem(itemId) {
  removingItemId.value = itemId
  try {
    await removeItem(itemId)
  } catch (e) {
    alert(e.message)
  } finally {
    removingItemId.value = null
  }
}
</script>
