// Initial template generated by Claude, with wiring up, edits, and function edits done manually with AI guidance
<template>
  <div class="container-fluid px-4 py-4">

    <div class="d-flex justify-content-between align-items-center mb-5">
      <div>
        <h1 class="mb-1" style="color:#1b4d1b;font-weight:600;font-size:1.75rem;">Goals &amp; Progress</h1>
        <p class="mb-0" style="color:#6b7280;font-size:0.9375rem;">Set personal goals, track your progress and celebrate achievements</p>
      </div>
      <button class="btn fw-semibold" @click="toggleAddForm"
              :aria-expanded="showAddForm"
              aria-controls="add-goal-section"
              style="background:#1b4d1b;color:#ffffff;border:none;padding:0.625rem 1.5rem;border-radius:8px;font-size:0.9375rem;">
        {{ showAddForm ? 'Close' : '+ Add New Goal' }}
      </button>
    </div>

    <div v-if="loadError" role="alert" class="alert alert-danger mb-4" style="border-radius:8px;">{{ loadError }}</div>

    <!-- quick stats row — at a glance summary of where the user is today -->
    <div class="row g-3 mb-4">
      <div class="col-md-4 col-6">
        <div class="p-3 rounded h-100" style="background:#f9fafb;">
          <div style="color:#6b7280;font-size:0.8125rem;margin-bottom:0.25rem;">Active Goals</div>
          <div style="color:#1b4d1b;font-size:1.25rem;font-weight:700;">{{ activeGoals.length }}</div>
        </div>
      </div>
      <div class="col-md-4 col-6">
        <div class="p-3 rounded h-100" style="background:#f9fafb;">
          <div style="color:#6b7280;font-size:0.8125rem;margin-bottom:0.25rem;">Done Today</div>
          <div style="color:#1b4d1b;font-size:1.25rem;font-weight:700;">{{ doneToday }} / {{ activeGoals.length }}</div>
        </div>
      </div>
      <div class="col-md-4 col-6">
        <div class="p-3 rounded h-100" style="background:#f9fafb;">
          <div style="color:#6b7280;font-size:0.8125rem;margin-bottom:0.25rem;">Set By Pro</div>
          <div style="color:#1b4d1b;font-size:1.25rem;font-weight:700;">{{ proGoalsCount }}</div>
        </div>
      </div>
    </div>

    <div role="tablist" aria-label="Goal filter"
         class="d-flex gap-2 mb-4 pb-3 flex-wrap" style="border-bottom:1px solid #f3f4f6;"
         @keydown="handleGoalTabKeydown">
      <button v-for="(tab, i) in tabs" :key="tab.id"
              role="tab"
              :id="`goal-tab-${tab.id}`"
              :aria-selected="activeTab === tab.id ? 'true' : 'false'"
              :aria-controls="`goal-panel-${tab.id}`"
              :tabindex="activeTab === tab.id ? 0 : -1"
              class="btn"
              :style="(activeTab === tab.id) ? 'background:#1b4d1b;color:#fff;border:none;padding:0.5rem 1rem;border-radius:8px;font-size:0.875rem;font-weight:500;' : 'background:#f3f4f6;color:#4b5563;border:none;padding:0.5rem 1rem;border-radius:8px;font-size:0.875rem;font-weight:500;'"
              @click="activeTab = tab.id">
        {{ tab.label }}
      </button>
    </div>

    <div v-if="loading" role="status" aria-live="polite" class="text-center text-muted py-5"><small>Loading goals…</small></div>

    <div v-else
         role="tabpanel"
         :id="`goal-panel-${activeTab}`"
         :aria-labelledby="`goal-tab-${activeTab}`">
      <div v-if="visibleGoals.length === 0"
           class="text-center py-5 rounded mb-4"
           style="background:#f9fafb;border:2px dashed #e5e7eb;">
        <p class="mb-3" style="color:#6b7280;font-size:0.9375rem;">{{ emptyMessage }}</p>
        <button v-if="activeTab === 'active'" class="btn fw-semibold" @click="toggleAddForm"
                style="background:#1b4d1b;color:#ffffff;border:none;padding:0.625rem 1.5rem;border-radius:8px;font-size:0.875rem;">
          Set your first goal
        </button>
      </div>

      <div class="row g-3 mb-4">
        <div class="col-md-6" v-for="goal in visibleGoals" :key="goal.goalId">
          <div class="h-100 rounded" style="background:#fff;box-shadow:0 1px 3px rgba(0,0,0,0.08);border-radius:12px;border:0.75px solid #1b4d1b;overflow:hidden;">
            <div class="d-flex justify-content-between align-items-center p-3" style="border-bottom:1px solid #f3f4f6;">
              <div class="d-flex align-items-center gap-2">
                <span class="fw-semibold" style="color:#1b4d1b;font-size:0.875rem;">{{ goalTitle(goal) }}</span>
                <span class="badge rounded-pill"
                      :style="`background:${goal.source === 'professional_defined' ? '#2e7d32' : '#e5e7eb'};color:${goal.source === 'professional_defined' ? '#fff' : '#374151'};font-weight:500;font-size:0.7rem;padding:0.25rem 0.625rem;`">
                  {{ sourceLabel(goal.source) }}
                </span>
              </div>
              <div class="d-flex gap-1">
                <button v-if="goal.status === 'active'"
                        class="btn btn-sm"
                        style="background:#f3f4f6;color:#1b4d1b;border:none;padding:0.25rem 0.625rem;border-radius:6px;font-size:0.75rem;"
                        :aria-label="`Edit goal: ${goalTitle(goal)}`"
                        @click="startEdit(goal)">Edit</button>
              </div>
            </div>
            <div class="p-3">
              <div class="d-flex align-items-center gap-3 mb-3">

                <!-- SVG ring — stroke-dasharray does the progress arc math -->
                <svg viewBox="0 0 100 100" width="80" height="80" style="flex-shrink:0;"
                     role="img"
                     :aria-label="`${goalTitle(goal)}: ${goalProgress(goal)}% progress (${goalProgressLabel(goal)})`">
                  <circle cx="50" cy="50" r="40" fill="none" stroke="#f3f4f6" stroke-width="10"/>
                  <circle cx="50" cy="50" r="40" fill="none" :stroke="goalProgressColor(goal)" stroke-width="10"
                          :stroke-dasharray="`${Math.min(goalProgress(goal), 100) * 2.51} ${(100 - Math.min(goalProgress(goal), 100)) * 2.51}`"
                          stroke-dashoffset="62.75"
                          stroke-linecap="round"
                          transform="rotate(-90 50 50)"/>
                  <text x="50" y="46" text-anchor="middle" font-size="16" font-weight="bold" fill="#1b4d1b">
                    {{ goalProgress(goal) }}%
                  </text>
                  <text x="50" y="60" text-anchor="middle" font-size="9" fill="#6b7280">{{ goalProgressLabel(goal) }}</text>
                </svg>
                <span class="visually-hidden">Target: {{ goalRange(goal) || 'Personal goal' }}. {{ formatRange(goal) }}</span>

                <div class="flex-grow-1">
                  <div class="fw-semibold mb-1" style="color:#1b4d1b;font-size:0.875rem;">{{ goalRange(goal) || 'Personal goal' }}</div>
                  <div class="mb-1" style="color:#6b7280;font-size:0.75rem;">{{ goal.notes }}</div>
                  <div style="color:#6b7280;font-size:0.75rem;">{{ formatRange(goal) }}</div>
                </div>
              </div>

              <!-- 7-day sparkline — taller bar means done, short bar means missed that day -->
              <div v-if="goal.status === 'active'" class="mb-3">
                <small style="color:#6b7280;font-size:0.75rem;">Last 7 days:</small>
                <div class="d-flex align-items-end gap-1 mt-1" style="height:32px;"
                     role="img"
                     :aria-label="`Last 7 days: ${trendFor(goal).map(d => d.label + ': ' + (d.done ? 'done' : 'missed')).join(', ')}`">
                  <div v-for="(day, i) in trendFor(goal)" :key="i"
                       aria-hidden="true"
                       :style="`height:${day.done ? 28 : 8}px;flex:1;background:${day.done ? '#2e7d32' : '#f3f4f6'};border-radius:2px 2px 0 0;border:1px solid ${day.done ? '#1b4d1b' : '#e5e7eb'};`">
                  </div>
                </div>
              </div>

              <div class="d-flex flex-wrap gap-2">
                <button v-if="goal.status === 'active' && !goal.nutrientId"
                        class="btn btn-sm fw-semibold"
                        :style="isDoneToday(goal) ? 'background:#f3f4f6;color:#1b4d1b;border:1px solid #e5e7eb;padding:0.375rem 0.75rem;border-radius:6px;font-size:0.75rem;' : 'background:#2e7d32;color:#fff;border:none;padding:0.375rem 0.75rem;border-radius:6px;font-size:0.75rem;'"
                        :disabled="goal._toggling"
                        @click="toggleDone(goal)">
                  {{ goal._toggling ? '…' : (isDoneToday(goal) ? '✓ Mark Today Undone' : 'Mark Today Done') }}
                </button>
                <span v-if="goal.status === 'active' && goal.nutrientId"
                      class="badge rounded-pill align-self-center"
                      :style="`background:${isDoneToday(goal) ? '#2e7d32' : '#6b7280'};color:#fff;font-size:0.7rem;padding:0.25rem 0.625rem;`">
                  {{ isDoneToday(goal) ? '✓ Met today' : 'Not met yet' }}
                </span>
                <template v-if="goal.status === 'active'">
                  <template v-if="confirmingGoalId === goal.goalId">
                    <span style="font-size:0.75rem;color:#991b1b;align-self:center;">Archive goal?</span>
                    <button class="btn btn-sm fw-semibold"
                            style="background:#991b1b;color:#fff;border:none;padding:0.375rem 0.75rem;border-radius:6px;font-size:0.75rem;"
                            :aria-label="`Confirm archive: ${goalTitle(goal)}`"
                            @click="archiveGoal(goal)">
                      Yes, archive
                    </button>
                    <button class="btn btn-sm"
                            style="background:#f3f4f6;color:#4b5563;border:none;padding:0.375rem 0.75rem;border-radius:6px;font-size:0.75rem;"
                            :aria-label="`Cancel archive of ${goalTitle(goal)}`"
                            @click="confirmingGoalId = null">
                      Cancel
                    </button>
                  </template>
                  <button v-else
                          class="btn btn-sm"
                          style="background:#fde8e8;border:1px solid #d99;color:#991b1b;padding:0.375rem 0.75rem;border-radius:6px;font-size:0.75rem;"
                          :aria-label="`Delete goal: ${goalTitle(goal)}`"
                          :disabled="goal._archiving"
                          @click="archiveGoal(goal)">
                    {{ goal._archiving ? '…' : 'Delete' }}
                  </button>
                </template>
              </div>

              <div v-if="editingId === goal.goalId" class="mt-3 pt-3" style="border-top:1px solid #f3f4f6;">
                <div class="row g-2 mb-2">
                  <div class="col-md-6">
                    <label for="edit-goal-notes" class="form-label" style="font-size:0.8125rem;color:#6b7280;">Notes</label>
                    <input id="edit-goal-notes" type="text" class="form-control form-control-sm" v-model="editDraft.notes">
                  </div>
                  <div class="col-md-3">
                    <label for="edit-goal-start" class="form-label" style="font-size:0.8125rem;color:#6b7280;">Start</label>
                    <input id="edit-goal-start" type="date" class="form-control form-control-sm" v-model="editDraft.startDate">
                  </div>
                  <div class="col-md-3">
                    <label for="edit-goal-end" class="form-label" style="font-size:0.8125rem;color:#6b7280;">End</label>
                    <input id="edit-goal-end" type="date" class="form-control form-control-sm" v-model="editDraft.endDate">
                  </div>
                </div>
                <div class="row g-2 mb-2">
                  <div class="col-md-6">
                    <label for="edit-goal-min" class="form-label" style="font-size:0.8125rem;color:#6b7280;">Target Min</label>
                    <input id="edit-goal-min" type="number" class="form-control form-control-sm" v-model.number="editDraft.targetMin" step="any">
                  </div>
                  <div class="col-md-6">
                    <label for="edit-goal-max" class="form-label" style="font-size:0.8125rem;color:#6b7280;">Target Max</label>
                    <input id="edit-goal-max" type="number" class="form-control form-control-sm" v-model.number="editDraft.targetMax" step="any">
                  </div>
                </div>
                <div v-if="editError" class="alert alert-danger py-2 mb-2" style="font-size:0.8125rem;border-radius:6px;">{{ editError }}</div>
                <div class="d-flex gap-2">
                  <button class="btn btn-sm fw-semibold" :disabled="editSaving" @click="saveEdit(goal)"
                          style="background:#2e7d32;color:#fff;border:none;padding:0.375rem 0.75rem;border-radius:6px;font-size:0.75rem;">
                    {{ editSaving ? '…' : 'Save Changes' }}
                  </button>
                  <button class="btn btn-sm" @click="cancelEdit"
                          style="background:#f3f4f6;color:#4b5563;border:none;padding:0.375rem 0.75rem;border-radius:6px;font-size:0.75rem;">Cancel</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div v-if="showAddForm" id="add-goal-section" ref="addFormSection">
      <h2 class="fw-bold mb-3" style="color:#1b4d1b;font-size:1.25rem;">Add New Goal</h2>
      <div class="row g-3 mb-4">

        <div class="col-md-6">
          <div class="p-3 rounded" style="background:#fff;box-shadow:0 1px 3px rgba(0,0,0,0.08);border-radius:12px;border:0.75px solid #1b4d1b;">
            <h3 class="fw-bold mb-2" style="color:#1b4d1b;font-size:0.875rem;">Create Custom Goal</h3>
            <p style="font-size:0.75rem;color:#6b7280;margin-bottom:0.75rem;">Fields marked <span aria-hidden="true" style="color:#c62828;">*</span><span class="visually-hidden">with an asterisk</span> are required.</p>

            <div class="mb-3">
              <label for="custom-goal-notes" class="form-label" style="font-size:0.8125rem;color:#6b7280;">Goal Title / Notes <span aria-hidden="true" style="color:#c62828;">*</span><span class="visually-hidden"> (required)</span></label>
              <input id="custom-goal-notes" type="text" class="form-control" v-model="customGoal.notes"
                     placeholder="e.g. Reduce sugar intake to 30g/day"
                     style="border-radius:8px;">
            </div>

            <div class="row g-2 mb-3">
              <div class="col">
                <label for="custom-goal-nutrient" class="form-label" style="font-size:0.8125rem;color:#6b7280;">Tracked Nutrient</label>
                <select id="custom-goal-nutrient" class="form-select" v-model="customGoal.nutrientCode" style="border-radius:8px;">
                  <option value="">No specific nutrient</option>
                  <option v-for="n in nutrients" :key="n.nutrientId" :value="n.code">
                    {{ n.name }} ({{ n.unit }})
                  </option>
                </select>
              </div>
              <div class="col">
                <label for="custom-goal-direction" class="form-label" style="font-size:0.8125rem;color:#6b7280;">Direction</label>
                <select id="custom-goal-direction" class="form-select" v-model="customGoal.direction"
                        :disabled="!customGoal.nutrientCode" style="border-radius:8px;">
                  <option value="below">Stay Below</option>
                  <option value="above">Reach At Least</option>
                  <option value="range">Stay In Range</option>
                </select>
              </div>
            </div>

            <div class="row g-2 mb-3" v-if="customGoal.nutrientCode">
              <div class="col" v-if="customGoal.direction !== 'below'">
                <label for="custom-goal-min" class="form-label" style="font-size:0.8125rem;color:#6b7280;">Min ({{ selectedNutrientUnit }})</label>
                <input id="custom-goal-min" type="number" class="form-control"
                       v-model.number="customGoal.targetMin" step="any" min="0" style="border-radius:8px;">
              </div>
              <div class="col" v-if="customGoal.direction !== 'above'">
                <label for="custom-goal-max" class="form-label" style="font-size:0.8125rem;color:#6b7280;">Max ({{ selectedNutrientUnit }})</label>
                <input id="custom-goal-max" type="number" class="form-control"
                       v-model.number="customGoal.targetMax" step="any" min="0" style="border-radius:8px;">
              </div>
            </div>

            <div class="row g-2 mb-3">
              <div class="col">
                <label for="custom-goal-start" class="form-label" style="font-size:0.8125rem;color:#6b7280;">Start Date</label>
                <input id="custom-goal-start" type="date" class="form-control" v-model="customGoal.startDate" style="border-radius:8px;">
              </div>
              <div class="col">
                <label for="custom-goal-end" class="form-label" style="font-size:0.8125rem;color:#6b7280;">End Date (optional)</label>
                <input id="custom-goal-end" type="date" class="form-control" v-model="customGoal.endDate" style="border-radius:8px;">
              </div>
            </div>

            <div v-if="replacesGoalWarning" class="alert py-2 mb-3"
                 style="background:#fffbf0;border:1px solid #e8a820;color:#7a5800;border-radius:8px;font-size:0.8125rem;">
              This will replace your existing active {{ replacesGoalWarning }} goal.
            </div>
            <div v-if="createError" class="alert alert-danger py-2 mb-3" style="border-radius:8px;font-size:0.8125rem;">{{ createError }}</div>

            <button class="btn fw-semibold" :disabled="creating" @click="saveCustomGoal"
                    style="background:#2e7d32;color:#fff;border:none;padding:0.625rem 1.5rem;border-radius:8px;font-size:0.875rem;">
              {{ creating ? 'Saving…' : 'Save Custom Goal' }}
            </button>
          </div>
        </div>

        <div class="col-md-6">
          <div class="p-3 rounded" style="background:#fff;box-shadow:0 1px 3px rgba(0,0,0,0.08);border-radius:12px;border:0.75px solid #1b4d1b;">
            <!-- preset goals based on NHS reference intakes — quick way to get started without filling the full form -->
            <h3 class="fw-bold mb-2" style="color:#1b4d1b;font-size:0.875rem;">Choose a Preset Goal</h3>
            <p class="mb-3" style="color:#6b7280;font-size:0.8125rem;">Curated goals based on NHS reference intakes</p>

            <div v-for="preset in presets" :key="preset.title"
                 class="d-flex justify-content-between align-items-center p-2 rounded mb-2"
                 style="background:#f9fafb;border:1px solid #e5e7eb;">
              <div class="flex-grow-1 me-2">
                <div class="fw-semibold" style="color:#1b4d1b;font-size:0.8125rem;">{{ preset.title }}</div>
                <div style="color:#6b7280;font-size:0.75rem;">{{ preset.desc }}</div>
                <div style="color:#6b7280;font-size:0.75rem;">Duration: {{ preset.durationLabel }}</div>
              </div>
              <button class="btn btn-sm fw-semibold" :disabled="creating" @click="applyPreset(preset)"
                      style="background:#2e7d32;color:#fff;border:none;padding:0.375rem 0.75rem;border-radius:6px;font-size:0.75rem;">
                {{ creating && pendingPreset === preset.title ? '…' : 'Add' }}
              </button>
            </div>
          </div>
        </div>

      </div>
    </div>

  </div>
</template>

<script setup>
import { ref, computed, onMounted, nextTick } from 'vue'
import { apiFetch } from '../auth.js'
import { useToast } from '../composables/useToast.js'

const { addToast } = useToast()

const goals = ref([])
const nutrients = ref([])
const loading = ref(true)
const loadError = ref('')
const todayNutrition = ref([]) // Today's nutrition summary for progress calculation

const showAddForm = ref(false)
const activeTab = ref('active')
const addFormSection = ref(null)

const creating = ref(false)
const createError = ref('')
const pendingPreset = ref(null)

const editingId = ref(null)
const editDraft = ref({})
const editSaving = ref(false)
const editError = ref('')

const confirmingGoalId = ref(null)

const todayIso = () => new Date().toISOString().slice(0, 10)
const addDays = (date, days) => {
  const d = new Date(date)
  d.setDate(d.getDate() + days)
  return d.toISOString().slice(0, 10)
}

const customGoal = ref({
  notes: '',
  nutrientCode: '',
  direction: 'below',
  targetMin: null,
  targetMax: null,
  startDate: todayIso(),
  endDate: '',
})

function handleGoalTabKeydown(event) {
  const tabIds = tabs.value.map(t => t.id)
  const currentIndex = tabIds.indexOf(activeTab.value)
  let newIndex = currentIndex
  if (event.key === 'ArrowRight') {
    event.preventDefault()
    newIndex = (currentIndex + 1) % tabIds.length
  } else if (event.key === 'ArrowLeft') {
    event.preventDefault()
    newIndex = (currentIndex - 1 + tabIds.length) % tabIds.length
  } else {
    return
  }
  activeTab.value = tabIds[newIndex]
  nextTick(() => {
    document.getElementById(`goal-tab-${tabIds[newIndex]}`)?.focus()
  })
}

async function toggleAddForm() {
  showAddForm.value = !showAddForm.value
  if (showAddForm.value) {
    await nextTick()
    addFormSection.value?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }
}

const selectedNutrientUnit = computed(() => {
  const n = nutrients.value.find(x => x.code === customGoal.value.nutrientCode)
  return n?.unit ?? ''
})

const activeGoals = computed(() => goals.value.filter(g => g.status === 'active'))

// warns the user if they're about to create a second goal for the same nutrient — only one active per nutrient
const replacesGoalWarning = computed(() => {
  if (!customGoal.value.nutrientCode) return null
  const existing = activeGoals.value.find(
    g => g.nutrient?.code === customGoal.value.nutrientCode
  )
  return existing ? existing.nutrient.name : null
})
const archivedGoals = computed(() => goals.value.filter(g => g.status === 'archived'))
const proGoalsCount = computed(() => activeGoals.value.filter(g => g.source === 'professional_defined').length)
const doneToday = computed(() => activeGoals.value.filter(isDoneToday).length)

const tabs = computed(() => [
  { id: 'active', label: 'Active', count: activeGoals.value.length },
  { id: 'pro', label: 'From Pro', count: proGoalsCount.value },
])

const visibleGoals = computed(() => {
  if (activeTab.value === 'pro') return activeGoals.value.filter(g => g.source === 'professional_defined')
  return activeGoals.value
})

const emptyMessage = computed(() => {
  if (activeTab.value === 'pro') return 'Your nutritionist hasn\'t set any goals for you yet.';
  return 'No active goals yet.';
})

const presets = [
  { title: 'Hit Daily Calorie Target', desc: 'Stay within 2,000 kcal/day', nutrientCode: 'calories', direction: 'below', targetMax: 2000, durationDays: 30, durationLabel: '30 days' },
  { title: 'Reach Protein Target', desc: 'At least 50g protein every day', nutrientCode: 'protein', direction: 'above', targetMin: 50, durationDays: 30, durationLabel: '30 days' },
  { title: 'Eat 30g of Fibre Daily', desc: 'Hit the NHS fibre recommendation', nutrientCode: 'fibre', direction: 'above', targetMin: 30, durationDays: 21, durationLabel: '21 days' },
  { title: 'Reduce Sugar to <30g/day', desc: 'Cut added sugars to under 30g', nutrientCode: 'sugar', direction: 'below', targetMax: 30, durationDays: 30, durationLabel: '30 days' },
  { title: 'Stay Under 6g Salt/day', desc: 'Lower salt intake for heart health', nutrientCode: 'salt', direction: 'below', targetMax: 6, durationDays: 30, durationLabel: '30 days' },
]

onMounted(async () => {
  await Promise.all([loadGoals(), loadNutrients(), loadTodayNutrition()])
})

async function loadGoals() {
  loading.value = true
  loadError.value = ''
  try {
    const res = await apiFetch('/api/goals?include=all')
    const data = await res.json().catch(() => ({}))
    if (res.ok) {
      goals.value = data.goals ?? []
    } else {
      loadError.value = data.message || data.error || 'Failed to load goals'
    }
  } catch (err) {
    loadError.value = 'Network error - could not load goals'
    console.error('Goals load error:', err)
  } finally {
    loading.value = false
  }
}

async function loadNutrients() {
  try {
    const res = await apiFetch('/api/goals/nutrients')
    const data = await res.json().catch(() => ({}))
    if (res.ok) nutrients.value = data.nutrients ?? []
  } catch {
    // non-critical
  }
}

// fetches today's nutrient totals so nutrient-based goals can show live progress
async function loadTodayNutrition() {
  try {
    const today = new Date()
    today.setHours(23, 59, 59, 999)
    const params = new URLSearchParams({ 
      period: 'daily', 
      endDate: today.toISOString() 
    })
    const res = await apiFetch(`/api/diary/summary?${params}`)
    const data = await res.json().catch(() => ({}))
    if (res.ok) {
      todayNutrition.value = data.summary?.nutrients ?? []
    }
  } catch {
    // non-critical
  }
}

function nutrientIdByCode(code) {
  return nutrients.value.find(n => n.code === code)?.nutrientId ?? null
}

function buildPayloadFromCustom() {
  const goal = {
    notes: customGoal.value.notes.trim(),
    startDate: customGoal.value.startDate || todayIso(),
  }
  if (customGoal.value.endDate) goal.endDate = customGoal.value.endDate
  if (customGoal.value.nutrientCode) {
    const id = nutrientIdByCode(customGoal.value.nutrientCode)
    if (id) goal.nutrientId = id
    if (customGoal.value.direction !== 'above' && customGoal.value.targetMax != null) {
      goal.targetMax = customGoal.value.targetMax
    }
    if (customGoal.value.direction !== 'below' && customGoal.value.targetMin != null) {
      goal.targetMin = customGoal.value.targetMin
    }
  }
  return goal
}

async function saveCustomGoal() {
  createError.value = ''
  if (!customGoal.value.notes.trim()) {
    createError.value = 'Please enter a goal title.'
    return
  }
  creating.value = true
  try {
    const goal = buildPayloadFromCustom()
    const res = await apiFetch('/api/goals', {
      method: 'POST',
      body: JSON.stringify({ goal }),
    })
    const data = await res.json().catch(() => ({}))
    if (!res.ok) {
      createError.value = data.error || 'Failed to save goal'
      return
    }
    customGoal.value = {
      notes: '', nutrientCode: '', direction: 'below',
      targetMin: null, targetMax: null,
      startDate: todayIso(), endDate: '',
    }
    addToast('Goal created')
    showAddForm.value = false
    await loadGoals()
  } catch {
    createError.value = 'Network error'
  } finally {
    creating.value = false
  }
}

async function applyPreset(preset) {
  createError.value = ''
  pendingPreset.value = preset.title
  creating.value = true
  try {
    const goal = {
      notes: preset.title,
      startDate: todayIso(),
      endDate: addDays(new Date(), preset.durationDays),
    }
    if (preset.nutrientCode) {
      const id = nutrientIdByCode(preset.nutrientCode)
      if (id) goal.nutrientId = id
      if (preset.targetMin != null) goal.targetMin = preset.targetMin
      if (preset.targetMax != null) goal.targetMax = preset.targetMax
    }
    const res = await apiFetch('/api/goals', {
      method: 'POST',
      body: JSON.stringify({ goal }),
    })
    const data = await res.json().catch(() => ({}))
    if (!res.ok) {
      createError.value = data.error || 'Failed to add preset'
      return
    }
    addToast('Goal added')
    showAddForm.value = false
    await loadGoals()
  } catch {
    createError.value = 'Network error'
  } finally {
    creating.value = false
    pendingPreset.value = null
  }
}

function isDoneToday(goal) {
  // For nutrient-based goals: check if target is met based on today's nutrition
  if (goal.nutrientId) {
    const nutrient = todayNutrition.value.find(n => n.nutrientId === goal.nutrientId)
    const currentAmount = nutrient ? Number(nutrient.totalAmount) : 0
    
    const min = goal.targetMin != null ? Number(goal.targetMin) : null
    const max = goal.targetMax != null ? Number(goal.targetMax) : null
    
    // Check if goal is met based on min/max constraints
    if (min != null && max != null) {
      return currentAmount >= min && currentAmount <= max
    } else if (min != null) {
      return currentAmount >= min
    } else if (max != null) {
      return currentAmount <= max
    }
    return false
  }
  
  // For manual goals: check checkIns (same logic as goalProgress uses)
  const checkIns = goal.checkIns ?? []
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  const iso = today.toISOString().slice(0, 10)
  
  return checkIns.some(c => {
    const checkInDate = new Date(c.date).toISOString().slice(0, 10)
    return checkInDate === iso && c.isDone
  })
}

async function toggleDone(goal) {
  goal._toggling = true
  try {
    const res = await apiFetch(`/api/goals/${goal.goalId}/toggle-done`, { method: 'PATCH' })
    if (!res.ok) {
      const data = await res.json().catch(() => ({}))
      addToast(data.error || 'Failed to toggle goal', { type: 'error' })
      return
    }
    await Promise.all([loadGoals(), loadTodayNutrition()])
  } catch {
    addToast('Network error', { type: 'error' })
  } finally {
    goal._toggling = false
  }
}

async function archiveGoal(goal) {
  if (confirmingGoalId.value !== goal.goalId) {
    confirmingGoalId.value = goal.goalId
    return
  }
  confirmingGoalId.value = null
  goal._archiving = true
  try {
    const res = await apiFetch(`/api/goals/${goal.goalId}`, { method: 'DELETE' })
    if (!res.ok) {
      const data = await res.json().catch(() => ({}))
      addToast(data.error || 'Failed to archive goal', { type: 'error' })
      return
    }
    addToast('Goal archived')
    await loadGoals()
  } catch {
    addToast('Network error', { type: 'error' })
  } finally {
    goal._archiving = false
  }
}

function startEdit(goal) {
  editingId.value = goal.goalId
  editError.value = ''
  editDraft.value = {
    notes: goal.notes ?? '',
    startDate: goal.startDate ? new Date(goal.startDate).toISOString().slice(0, 10) : '',
    endDate: goal.endDate ? new Date(goal.endDate).toISOString().slice(0, 10) : '',
    targetMin: goal.targetMin != null ? Number(goal.targetMin) : null,
    targetMax: goal.targetMax != null ? Number(goal.targetMax) : null,
  }
}

function cancelEdit() {
  editingId.value = null
  editError.value = ''
}

async function saveEdit(goal) {
  editError.value = ''
  editSaving.value = true
  try {
    const payload = { goalId: goal.goalId }
    if (editDraft.value.notes !== undefined) payload.notes = editDraft.value.notes
    if (editDraft.value.startDate) payload.startDate = editDraft.value.startDate
    if (editDraft.value.endDate) payload.endDate = editDraft.value.endDate
    if (editDraft.value.targetMin != null) payload.targetMin = editDraft.value.targetMin
    if (editDraft.value.targetMax != null) payload.targetMax = editDraft.value.targetMax

    const res = await apiFetch('/api/goals', {
      method: 'PATCH',
      body: JSON.stringify({ goal: payload }),
    })
    const data = await res.json().catch(() => ({}))
    if (!res.ok) {
      editError.value = data.error || 'Failed to update goal'
      return
    }
    addToast('Goal updated')
    cancelEdit()
    await loadGoals()
  } catch {
    editError.value = 'Network error'
  } finally {
    editSaving.value = false
  }
}

function goalTitle(goal) {
  if (goal.notes) return goal.notes
  if (goal.nutrient?.name) return `${goal.nutrient.name} goal`
  return 'Custom goal'
}

function goalRange(goal) {
  const min = goal.targetMin != null ? Number(goal.targetMin) : null
  const max = goal.targetMax != null ? Number(goal.targetMax) : null
  const unit = goal.nutrient?.unit ? ` ${goal.nutrient.unit}` : ''
  if (min != null && max != null) return `${min}–${max}${unit}`
  if (min != null) return `≥ ${min}${unit}`
  if (max != null) return `≤ ${max}${unit}`
  return ''
}

// goalProgress handles two very different goal types: nutrient goals (checked against diary totals) and manual check-in goals
function goalProgress(goal) {
  // For nutrient-based goals: show current intake as percentage of target
  if (goal.nutrientId) {
    const nutrient = todayNutrition.value.find(n => n.nutrientId === goal.nutrientId)
    const currentAmount = nutrient ? Number(nutrient.totalAmount) : 0
    
    const min = goal.targetMin != null ? Number(goal.targetMin) : null
    const max = goal.targetMax != null ? Number(goal.targetMax) : null
    
    let referenceValue = 0
    
    // Determine reference value based on what's set
    if (min != null && max != null) {
      // Both set: use average
      referenceValue = (min + max) / 2
    } else if (max != null) {
      // Max only: use max as the limit
      referenceValue = max
    } else if (min != null) {
      // Min only: use min as the target
      referenceValue = min
    } else {
      // Neither set: no progress bar
      return 0
    }
    
    if (referenceValue === 0) return 0
    
    // Calculate percentage of reference value (don't cap it)
    const percentage = Math.round((currentAmount / referenceValue) * 100)
    return percentage
  }
  
  // For manual (non-nutrient) goals: show completion based on checkIns
  const checkIns = goal.checkIns ?? []
  const start = goal.startDate ? new Date(goal.startDate) : new Date()
  start.setHours(0, 0, 0, 0)
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  const elapsedDays = Math.max(1, Math.min(7, Math.floor((today - start) / 86400000) + 1))
  let done = 0
  for (let i = 0; i < elapsedDays; i++) {
    const d = new Date(today)
    d.setDate(d.getDate() - i)
    const iso = d.toISOString().slice(0, 10)
    if (checkIns.some(c => new Date(c.date).toISOString().slice(0, 10) === iso && c.isDone)) {
      done++
    }
  }
  return Math.round((done / elapsedDays) * 100)
}

function goalProgressColor(goal) {
  const progress = goalProgress(goal)
  
  // For nutrient goals, determine if being over/under is good or bad
  if (goal.nutrientId) {
    const min = goal.targetMin != null ? Number(goal.targetMin) : null
    const max = goal.targetMax != null ? Number(goal.targetMax) : null
    
    // If only max is set (e.g., "stay under 30g sugar"), being over is bad
    if (max != null && min == null) {
      return progress > 100 ? '#d94f4f' : '#2e7d32' // Red if over, green if under
    }
    
    // If only min is set (e.g., "at least 50g protein"), being under is bad
    if (min != null && max == null) {
      return progress < 100 ? '#f59e0b' : '#2e7d32' // Orange if under, green if met
    }
    
    // If both are set (range), being outside range is bad
    if (min != null && max != null) {
      return progress >= 100 ? '#2e7d32' : '#f59e0b' // Green if in range, orange if not
    }
  }
  
  // Default green for manual goals
  return '#2e7d32'
}

function goalProgressLabel(goal) {
  const progress = goalProgress(goal)
  
  // For nutrient goals
  if (goal.nutrientId) {
    const min = goal.targetMin != null ? Number(goal.targetMin) : null
    const max = goal.targetMax != null ? Number(goal.targetMax) : null
    
    // If only max is set (e.g., "stay under 30g sugar")
    if (max != null && min == null) {
      if (progress > 100) return 'over limit'
      if (progress === 100) return 'at limit'
      return 'of limit'
    }
    
    // If only min is set (e.g., "at least 50g protein")
    if (min != null && max == null) {
      if (progress >= 100) return 'done'
      return 'of target'
    }
    
    // If both are set (range)
    if (min != null && max != null) {
      if (progress >= 100) return 'done'
      return 'of target'
    }
  }
  
  // For manual goals
  return progress >= 100 ? 'done' : 'of target'
}

// builds the last 7 days as pass/fail entries for the sparkline — nutrient goals use isDoneToday logic implicitly
function trendFor(goal) {
  const checkIns = goal.checkIns ?? []
  const result = []
  const today = new Date()
  for (let i = 6; i >= 0; i--) {
    const d = new Date(today)
    d.setDate(d.getDate() - i)
    d.setHours(0, 0, 0, 0)
    const iso = d.toISOString().slice(0, 10)
    const done = checkIns.some(c => new Date(c.date).toISOString().slice(0, 10) === iso && c.isDone)
    result.push({ label: iso, done })
  }
  return result
}

function formatRange(goal) {
  const start = goal.startDate ? new Date(goal.startDate).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' }) : null
  const end = goal.endDate ? new Date(goal.endDate).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' }) : 'ongoing'
  if (!start) return ''
  return `${start} → ${end}`
}

function sourceLabel(source) {
  if (source === 'professional_defined') return 'Pro'
  if (source === 'system_default') return 'System'
  return 'Personal'
}

function sourceColor(source) {
  if (source === 'professional_defined') return '#5a9e56'
  if (source === 'system_default') return '#888'
  return '#3a7fbf'
}
</script>
