// Initial template generated by Claude, with wiring up, edits, and function edits done manually with AI guidance
<template>
  <div class="container-fluid px-4 py-3">

    <div class="p-3 mb-3 rounded d-flex justify-content-between align-items-center"
         style="background:#e8f4e6;border:1px solid #5a9e56;">
      <div>
        <h4 style="color:#5a9e56;" class="mb-0">Goals &amp; Progress</h4>
        <small class="text-secondary">Set personal goals, track your progress and celebrate achievements</small>
      </div>
      <button class="btn btn-gf" @click="showAddForm = !showAddForm">
        {{ showAddForm ? 'Close' : 'Add New Goal' }}
      </button>
    </div>

    <div v-if="loadError" class="alert alert-danger small">{{ loadError }}</div>

    <div class="row g-3 mb-3">
      <div class="col-md-3 col-6">
        <div class="stat-card h-100">
          <div class="stat-label">Active Goals</div>
          <div class="stat-value">{{ activeGoals.length }}</div>
        </div>
      </div>
      <div class="col-md-3 col-6">
        <div class="stat-card h-100">
          <div class="stat-label">Done Today</div>
          <div class="stat-value">{{ doneToday }} / {{ activeGoals.length }}</div>
        </div>
      </div>
      <div class="col-md-3 col-6">
        <div class="stat-card h-100">
          <div class="stat-label">Set By Pro</div>
          <div class="stat-value">{{ proGoalsCount }}</div>
        </div>
      </div>
      <div class="col-md-3 col-6">
        <div class="stat-card h-100">
          <div class="stat-label">Archived</div>
          <div class="stat-value">{{ archivedGoals.length }}</div>
        </div>
      </div>
    </div>

    <div class="d-flex gap-2 mb-3 border-bottom pb-2 flex-wrap">
      <button v-for="tab in tabs" :key="tab.id"
              class="btn btn-sm"
              :class="activeTab === tab.id ? 'btn-gf' : 'btn-outline-secondary'"
              @click="activeTab = tab.id">
        {{ tab.label }}
        <span v-if="tab.count != null" class="badge ms-1"
              :style="`background:${activeTab === tab.id ? '#fff' : '#5a9e56'};color:${activeTab === tab.id ? '#5a9e56' : '#fff'};`">
          {{ tab.count }}
        </span>
      </button>
    </div>

    <div v-if="loading" class="text-center text-muted py-4"><small>Loading goals…</small></div>

    <template v-else>
      <div v-if="visibleGoals.length === 0"
           class="text-center text-muted py-4 border rounded mb-4"
           style="border-style:dashed!important;">
        <p class="mb-2">{{ emptyMessage }}</p>
        <button v-if="activeTab === 'active'" class="btn btn-gf btn-sm" @click="showAddForm = true">
          Set your first goal
        </button>
      </div>

      <div class="row g-3 mb-4">
        <div class="col-md-6" v-for="goal in visibleGoals" :key="goal.goalId">
          <div class="goal-card">
            <div class="goal-header d-flex justify-content-between align-items-center">
              <div class="d-flex align-items-center gap-2">
                <span>{{ goalTitle(goal) }}</span>
                <span class="badge" :style="`background:${sourceColor(goal.source)};font-size:0.6rem;`">
                  {{ sourceLabel(goal.source) }}
                </span>
              </div>
              <div class="d-flex gap-1">
                <button v-if="goal.status === 'active'"
                        class="btn btn-outline-secondary btn-sm py-0"
                        @click="startEdit(goal)">Edit</button>
              </div>
            </div>
            <div class="p-3">
              <div class="d-flex align-items-center gap-3">

                <svg viewBox="0 0 100 100" width="90" height="90" style="flex-shrink:0;">
                  <circle cx="50" cy="50" r="40" fill="none" stroke="#e9ecef" stroke-width="10"/>
                  <circle cx="50" cy="50" r="40" fill="none" stroke="#5a9e56" stroke-width="10"
                          :stroke-dasharray="`${goalProgress(goal) * 2.51} ${(100 - goalProgress(goal)) * 2.51}`"
                          stroke-dashoffset="62.75"
                          stroke-linecap="round"
                          transform="rotate(-90 50 50)"/>
                  <text x="50" y="46" text-anchor="middle" font-size="16" font-weight="bold" fill="#5a9e56">
                    {{ goalProgress(goal) }}%
                  </text>
                  <text x="50" y="60" text-anchor="middle" font-size="9" fill="#5a9e56">done</text>
                </svg>

                <div class="flex-grow-1">
                  <div class="fw-bold small">{{ goalRange(goal) || 'Personal goal' }}</div>
                  <div class="text-muted" style="font-size:0.75rem;">{{ goal.notes }}</div>
                  <div class="text-muted" style="font-size:0.75rem;">{{ formatRange(goal) }}</div>
                  <div v-if="goal.setByProfessionalId" class="text-muted" style="font-size:0.75rem;">
                    Set by your nutritionist
                  </div>
                </div>
              </div>

              <div v-if="goal.status === 'active'" class="mt-2 mb-1">
                <small class="text-muted">Last 7 days:</small>
                <div class="d-flex align-items-end gap-1 mt-1" style="height:32px;">
                  <div v-for="(day, i) in trendFor(goal)" :key="i"
                       :title="`${day.label}: ${day.done ? 'done' : 'missed'}`"
                       :style="`height:${day.done ? 28 : 8}px;flex:1;background:${day.done ? '#5a9e56' : '#d6e8d4'};border-radius:2px 2px 0 0;border:1px solid ${day.done ? '#3f7a3c' : '#a8c5a5'};`">
                  </div>
                </div>
              </div>

              <div class="d-flex flex-wrap gap-1 mt-2">
                <button v-if="goal.status === 'active'"
                        class="btn btn-sm"
                        :class="isDoneToday(goal) ? 'btn-gf' : 'btn-gf-outline'"
                        :disabled="goal._toggling"
                        @click="toggleDone(goal)">
                  {{ goal._toggling ? '…' : (isDoneToday(goal) ? '✓ Done Today' : 'Mark Today Done') }}
                </button>
                <button v-if="goal.status === 'active'"
                        class="btn btn-sm"
                        style="background:#fde8e8;border:1px solid #d99;color:#c44;"
                        :disabled="goal._archiving"
                        @click="archiveGoal(goal)">
                  {{ goal._archiving ? '…' : 'Archive' }}
                </button>
                <span v-if="goal.status === 'archived'"
                      class="badge text-bg-secondary">Archived</span>
              </div>

              <div v-if="editingId === goal.goalId" class="mt-3 pt-3 border-top">
                <div class="row g-2 mb-2">
                  <div class="col-md-6">
                    <label class="form-label form-label-sm">Notes</label>
                    <input type="text" class="form-control form-control-sm" v-model="editDraft.notes">
                  </div>
                  <div class="col-md-3">
                    <label class="form-label form-label-sm">Start</label>
                    <input type="date" class="form-control form-control-sm" v-model="editDraft.startDate">
                  </div>
                  <div class="col-md-3">
                    <label class="form-label form-label-sm">End</label>
                    <input type="date" class="form-control form-control-sm" v-model="editDraft.endDate">
                  </div>
                </div>
                <div class="row g-2 mb-2">
                  <div class="col-md-6">
                    <label class="form-label form-label-sm">Target Min</label>
                    <input type="number" class="form-control form-control-sm" v-model.number="editDraft.targetMin" step="any">
                  </div>
                  <div class="col-md-6">
                    <label class="form-label form-label-sm">Target Max</label>
                    <input type="number" class="form-control form-control-sm" v-model.number="editDraft.targetMax" step="any">
                  </div>
                </div>
                <div v-if="editError" class="alert alert-danger py-1 small mb-2">{{ editError }}</div>
                <div class="d-flex gap-2">
                  <button class="btn btn-gf btn-sm" :disabled="editSaving" @click="saveEdit(goal)">
                    {{ editSaving ? '…' : 'Save Changes' }}
                  </button>
                  <button class="btn btn-outline-secondary btn-sm" @click="cancelEdit">Cancel</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </template>

    <div v-if="showAddForm">
      <div class="meal-section-header">Add New Goal</div>
      <div class="row g-3 mt-1">

        <div class="col-md-6">
          <div class="add-meal-panel">
            <h6 class="fw-bold mb-3" style="color:#5a9e56;">Create Custom Goal</h6>

            <div class="mb-2">
              <label class="form-label form-label-sm">Goal Title / Notes <span class="text-danger">*</span></label>
              <input type="text" class="form-control form-control-sm" v-model="customGoal.notes"
                     placeholder="e.g. Reduce sugar intake to 30g/day">
            </div>

            <div class="row g-2 mb-2">
              <div class="col">
                <label class="form-label form-label-sm">Tracked Nutrient</label>
                <select class="form-select form-select-sm" v-model="customGoal.nutrientCode">
                  <option value="">No specific nutrient</option>
                  <option v-for="n in nutrients" :key="n.nutrientId" :value="n.code">
                    {{ n.name }} ({{ n.unit }})
                  </option>
                </select>
              </div>
              <div class="col">
                <label class="form-label form-label-sm">Direction</label>
                <select class="form-select form-select-sm" v-model="customGoal.direction"
                        :disabled="!customGoal.nutrientCode">
                  <option value="below">Stay Below</option>
                  <option value="above">Reach At Least</option>
                  <option value="range">Stay In Range</option>
                </select>
              </div>
            </div>

            <div class="row g-2 mb-2" v-if="customGoal.nutrientCode">
              <div class="col" v-if="customGoal.direction !== 'below'">
                <label class="form-label form-label-sm">Min ({{ selectedNutrientUnit }})</label>
                <input type="number" class="form-control form-control-sm"
                       v-model.number="customGoal.targetMin" step="any" min="0">
              </div>
              <div class="col" v-if="customGoal.direction !== 'above'">
                <label class="form-label form-label-sm">Max ({{ selectedNutrientUnit }})</label>
                <input type="number" class="form-control form-control-sm"
                       v-model.number="customGoal.targetMax" step="any" min="0">
              </div>
            </div>

            <div class="row g-2 mb-2">
              <div class="col">
                <label class="form-label form-label-sm">Start Date</label>
                <input type="date" class="form-control form-control-sm" v-model="customGoal.startDate">
              </div>
              <div class="col">
                <label class="form-label form-label-sm">End Date (optional)</label>
                <input type="date" class="form-control form-control-sm" v-model="customGoal.endDate">
              </div>
            </div>

            <div v-if="createError" class="alert alert-danger py-1 small mb-2">{{ createError }}</div>

            <button class="btn btn-gf" :disabled="creating" @click="saveCustomGoal">
              {{ creating ? 'Saving…' : 'Save Custom Goal' }}
            </button>
          </div>
        </div>

        <div class="col-md-6">
          <div class="add-meal-panel">
            <h6 class="fw-bold mb-2" style="color:#5a9e56;">Choose a Preset Goal</h6>
            <p class="text-muted small mb-3">Curated goals based on NHS reference intakes</p>

            <div v-for="preset in presets" :key="preset.title"
                 class="d-flex justify-content-between align-items-center p-2 bg-white border rounded mb-2">
              <div class="flex-grow-1 me-2">
                <div class="fw-semibold small">{{ preset.title }}</div>
                <div class="text-muted" style="font-size:0.72rem;">{{ preset.desc }}</div>
                <div class="text-muted" style="font-size:0.72rem;">Duration: {{ preset.durationLabel }}</div>
              </div>
              <button class="btn btn-gf btn-sm" :disabled="creating" @click="applyPreset(preset)">
                {{ creating && pendingPreset === preset.title ? '…' : 'Add' }}
              </button>
            </div>
          </div>
        </div>

      </div>
    </div>

  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { apiFetch } from '../auth.js'

const goals = ref([])
const nutrients = ref([])
const loading = ref(true)
const loadError = ref('')

const showAddForm = ref(false)
const activeTab = ref('active')

const creating = ref(false)
const createError = ref('')
const pendingPreset = ref(null)

const editingId = ref(null)
const editDraft = ref({})
const editSaving = ref(false)
const editError = ref('')

const todayIso = () => new Date().toISOString().slice(0, 10)
const addDays = (date, days) => {
  const d = new Date(date)
  d.setDate(d.getDate() + days)
  return d.toISOString().slice(0, 10)
}

const customGoal = ref({
  notes: '',
  nutrientCode: '',
  direction: 'below',
  targetMin: null,
  targetMax: null,
  startDate: todayIso(),
  endDate: '',
})

const selectedNutrientUnit = computed(() => {
  const n = nutrients.value.find(x => x.code === customGoal.value.nutrientCode)
  return n?.unit ?? ''
})

const activeGoals = computed(() => goals.value.filter(g => g.status === 'active'))
const archivedGoals = computed(() => goals.value.filter(g => g.status === 'archived'))
const proGoalsCount = computed(() => activeGoals.value.filter(g => g.source === 'professional_defined').length)
const doneToday = computed(() => activeGoals.value.filter(isDoneToday).length)

const tabs = computed(() => [
  { id: 'active', label: 'Active', count: activeGoals.value.length },
  { id: 'pro', label: 'From Pro', count: proGoalsCount.value },
  { id: 'archived', label: 'Archived', count: archivedGoals.value.length },
])

const visibleGoals = computed(() => {
  if (activeTab.value === 'archived') return archivedGoals.value
  if (activeTab.value === 'pro') return activeGoals.value.filter(g => g.source === 'professional_defined')
  return activeGoals.value
})

const emptyMessage = computed(() => {
  if (activeTab.value === 'archived') return 'No archived goals yet.'
  if (activeTab.value === 'pro') return 'Your nutritionist hasn’t set any goals for you yet.'
  return 'No active goals yet.'
})

const presets = [
  { title: 'Hit Daily Calorie Target', desc: 'Stay within 2,000 kcal/day', nutrientCode: 'calories', direction: 'below', targetMax: 2000, durationDays: 30, durationLabel: '30 days' },
  { title: 'Reach Protein Target', desc: 'At least 50g protein every day', nutrientCode: 'protein', direction: 'above', targetMin: 50, durationDays: 30, durationLabel: '30 days' },
  { title: 'Eat 30g of Fibre Daily', desc: 'Hit the NHS fibre recommendation', nutrientCode: 'fibre', direction: 'above', targetMin: 30, durationDays: 21, durationLabel: '21 days' },
  { title: 'Reduce Sugar to <30g/day', desc: 'Cut added sugars to under 30g', nutrientCode: 'sugar', direction: 'below', targetMax: 30, durationDays: 30, durationLabel: '30 days' },
  { title: 'Stay Under 6g Salt/day', desc: 'Lower salt intake for heart health', nutrientCode: 'salt', direction: 'below', targetMax: 6, durationDays: 30, durationLabel: '30 days' },
  { title: 'Two-Week Logging Streak', desc: 'Just log every meal for 14 days', nutrientCode: '', direction: 'below', targetMax: null, durationDays: 14, durationLabel: '14 days' },
]

onMounted(async () => {
  await Promise.all([loadGoals(), loadNutrients()])
})

async function loadGoals() {
  loading.value = true
  loadError.value = ''
  try {
    const res = await apiFetch('/api/goals?effective=false&include=all')
    const data = await res.json().catch(() => ({}))
    if (!res.ok) {
      loadError.value = data.error || 'Failed to load goals'
      return
    }
    goals.value = (data.goals ?? []).map(g => ({ ...g, _toggling: false, _archiving: false }))
  } catch {
    loadError.value = 'Network error - could not load goals'
  } finally {
    loading.value = false
  }
}

async function loadNutrients() {
  try {
    const res = await apiFetch('/api/goals/nutrients')
    const data = await res.json().catch(() => ({}))
    if (res.ok) nutrients.value = data.nutrients ?? []
  } catch {
    // non-critical
  }
}

function nutrientIdByCode(code) {
  return nutrients.value.find(n => n.code === code)?.nutrientId ?? null
}

function buildPayloadFromCustom() {
  const goal = {
    notes: customGoal.value.notes.trim(),
    startDate: customGoal.value.startDate || todayIso(),
  }
  if (customGoal.value.endDate) goal.endDate = customGoal.value.endDate
  if (customGoal.value.nutrientCode) {
    const id = nutrientIdByCode(customGoal.value.nutrientCode)
    if (id) goal.nutrientId = id
    if (customGoal.value.direction !== 'above' && customGoal.value.targetMax != null) {
      goal.targetMax = customGoal.value.targetMax
    }
    if (customGoal.value.direction !== 'below' && customGoal.value.targetMin != null) {
      goal.targetMin = customGoal.value.targetMin
    }
  }
  return goal
}

async function saveCustomGoal() {
  createError.value = ''
  if (!customGoal.value.notes.trim()) {
    createError.value = 'Please enter a goal title.'
    return
  }
  creating.value = true
  try {
    const goal = buildPayloadFromCustom()
    const res = await apiFetch('/api/goals', {
      method: 'POST',
      body: JSON.stringify({ goal }),
    })
    const data = await res.json().catch(() => ({}))
    if (!res.ok) {
      createError.value = data.error || 'Failed to save goal'
      return
    }
    customGoal.value = {
      notes: '', nutrientCode: '', direction: 'below',
      targetMin: null, targetMax: null,
      startDate: todayIso(), endDate: '',
    }
    showAddForm.value = false
    await loadGoals()
  } catch {
    createError.value = 'Network error'
  } finally {
    creating.value = false
  }
}

async function applyPreset(preset) {
  createError.value = ''
  pendingPreset.value = preset.title
  creating.value = true
  try {
    const goal = {
      notes: preset.title,
      startDate: todayIso(),
      endDate: addDays(new Date(), preset.durationDays),
    }
    if (preset.nutrientCode) {
      const id = nutrientIdByCode(preset.nutrientCode)
      if (id) goal.nutrientId = id
      if (preset.targetMin != null) goal.targetMin = preset.targetMin
      if (preset.targetMax != null) goal.targetMax = preset.targetMax
    }
    const res = await apiFetch('/api/goals', {
      method: 'POST',
      body: JSON.stringify({ goal }),
    })
    const data = await res.json().catch(() => ({}))
    if (!res.ok) {
      createError.value = data.error || 'Failed to add preset'
      return
    }
    showAddForm.value = false
    await loadGoals()
  } catch {
    createError.value = 'Network error'
  } finally {
    creating.value = false
    pendingPreset.value = null
  }
}

function isDoneToday(goal) {
  const today = todayIso()
  return (goal.checkIns ?? []).some(c => {
    const d = new Date(c.date).toISOString().slice(0, 10)
    return d === today && c.isDone
  })
}

async function toggleDone(goal) {
  goal._toggling = true
  try {
    const res = await apiFetch(`/api/goals/${goal.goalId}/toggle-done`, { method: 'PATCH' })
    if (!res.ok) {
      const data = await res.json().catch(() => ({}))
      alert(data.error || 'Failed to toggle goal')
      return
    }
    await loadGoals()
  } catch {
    alert('Network error')
  } finally {
    goal._toggling = false
  }
}

async function archiveGoal(goal) {
  if (!confirm(`Archive "${goalTitle(goal)}"? You can still see it in the Archived tab.`)) return
  goal._archiving = true
  try {
    const res = await apiFetch(`/api/goals/${goal.goalId}`, { method: 'DELETE' })
    if (!res.ok) {
      const data = await res.json().catch(() => ({}))
      alert(data.error || 'Failed to archive goal')
      return
    }
    await loadGoals()
  } catch {
    alert('Network error')
  } finally {
    goal._archiving = false
  }
}

function startEdit(goal) {
  editingId.value = goal.goalId
  editError.value = ''
  editDraft.value = {
    notes: goal.notes ?? '',
    startDate: goal.startDate ? new Date(goal.startDate).toISOString().slice(0, 10) : '',
    endDate: goal.endDate ? new Date(goal.endDate).toISOString().slice(0, 10) : '',
    targetMin: goal.targetMin != null ? Number(goal.targetMin) : null,
    targetMax: goal.targetMax != null ? Number(goal.targetMax) : null,
  }
}

function cancelEdit() {
  editingId.value = null
  editError.value = ''
}

async function saveEdit(goal) {
  editError.value = ''
  editSaving.value = true
  try {
    const payload = { goalId: goal.goalId }
    if (editDraft.value.notes !== undefined) payload.notes = editDraft.value.notes
    if (editDraft.value.startDate) payload.startDate = editDraft.value.startDate
    if (editDraft.value.endDate) payload.endDate = editDraft.value.endDate
    if (editDraft.value.targetMin != null) payload.targetMin = editDraft.value.targetMin
    if (editDraft.value.targetMax != null) payload.targetMax = editDraft.value.targetMax

    const res = await apiFetch('/api/goals', {
      method: 'PATCH',
      body: JSON.stringify({ goal: payload }),
    })
    const data = await res.json().catch(() => ({}))
    if (!res.ok) {
      editError.value = data.error || 'Failed to update goal'
      return
    }
    cancelEdit()
    await loadGoals()
  } catch {
    editError.value = 'Network error'
  } finally {
    editSaving.value = false
  }
}

function goalTitle(goal) {
  if (goal.notes) return goal.notes
  if (goal.nutrient?.name) return `${goal.nutrient.name} goal`
  return 'Custom goal'
}

function goalRange(goal) {
  const min = goal.targetMin != null ? Number(goal.targetMin) : null
  const max = goal.targetMax != null ? Number(goal.targetMax) : null
  const unit = goal.nutrient?.unit ? ` ${goal.nutrient.unit}` : ''
  if (min != null && max != null) return `${min}–${max}${unit}`
  if (min != null) return `≥ ${min}${unit}`
  if (max != null) return `≤ ${max}${unit}`
  return ''
}

function goalProgress(goal) {
  const checkIns = goal.checkIns ?? []
  const start = goal.startDate ? new Date(goal.startDate) : new Date()
  start.setHours(0, 0, 0, 0)
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  const elapsedDays = Math.max(1, Math.min(7, Math.floor((today - start) / 86400000) + 1))
  let done = 0
  for (let i = 0; i < elapsedDays; i++) {
    const d = new Date(today)
    d.setDate(d.getDate() - i)
    const iso = d.toISOString().slice(0, 10)
    if (checkIns.some(c => new Date(c.date).toISOString().slice(0, 10) === iso && c.isDone)) {
      done++
    }
  }
  return Math.round((done / elapsedDays) * 100)
}

function trendFor(goal) {
  const checkIns = goal.checkIns ?? []
  const result = []
  const today = new Date()
  for (let i = 6; i >= 0; i--) {
    const d = new Date(today)
    d.setDate(d.getDate() - i)
    d.setHours(0, 0, 0, 0)
    const iso = d.toISOString().slice(0, 10)
    const done = checkIns.some(c => new Date(c.date).toISOString().slice(0, 10) === iso && c.isDone)
    result.push({ label: iso, done })
  }
  return result
}

function formatRange(goal) {
  const start = goal.startDate ? new Date(goal.startDate).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' }) : null
  const end = goal.endDate ? new Date(goal.endDate).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' }) : 'ongoing'
  if (!start) return ''
  return `${start} → ${end}`
}

function sourceLabel(source) {
  if (source === 'professional_defined') return 'Pro'
  if (source === 'system_default') return 'System'
  return 'Personal'
}

function sourceColor(source) {
  if (source === 'professional_defined') return '#5a9e56'
  if (source === 'system_default') return '#888'
  return '#3a7fbf'
}
</script>
