// Initial template generated by Claude, with wiring up, edits, and function edits done manually with AI guidance
<template>
  <div>

    <section class="py-5" style="background:url('/src/assets/diet-menu-healthy-vegetarian-salad-fresh-vegetables-tomatoes-cucumber-sweet-peppers-porridge-bowl-vegan-food-flat-lay-top-view_2829-19941.png') center/cover no-repeat;min-height:75vh;display:flex;align-items:flex-end;position:relative;background-color:#f5f5f5;">
      <div class="container" style="position:relative;z-index:1;padding-bottom:4rem;">
        <div class="row align-items-center">

          <div class="col-lg-6">
            <h1 style="color:#1b4d1b;font-weight:400;font-size:3.5rem;line-height:1.2;margin-bottom:1.5rem;letter-spacing:-0.01em;font-family:Georgia,'Times New Roman',serif;text-shadow:0 0 30px rgba(255,255,255,1), 0 0 50px rgba(255,255,255,0.9), 0 0 70px rgba(255,255,255,0.7), 2px 2px 4px rgba(255,255,255,0.8);">
              Take Control of Your Nutrition
            </h1>
            <p style="color:#2d5a2d;font-size:1rem;font-weight:400;max-width:460px;line-height:1.7;margin-bottom:2.5rem;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;text-shadow:0 0 25px rgba(255,255,255,1), 0 0 40px rgba(255,255,255,0.9), 0 0 60px rgba(255,255,255,0.7), 1px 1px 3px rgba(255,255,255,0.8);">
              Track your meals, analyze your nutrition, and get personalized guidance from certified professionals.
            </p>
            <a href="#auth-section" style="color:#1b4d1b;font-weight:500;font-size:0.95rem;text-decoration:none;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;letter-spacing:0.02em;display:inline-flex;align-items:center;gap:0.5rem;border-bottom:1px solid #1b4d1b;padding-bottom:2px;transition:opacity 0.2s;text-shadow:0 0 25px rgba(255,255,255,1), 0 0 40px rgba(255,255,255,0.9), 1px 1px 3px rgba(255,255,255,0.8);" onmouseover="this.style.opacity='0.6'" onmouseout="this.style.opacity='1'">
              Get Started
              <span style="font-size:1.2rem;">→</span>
            </a>
          </div>

          <div class="col-lg-6 d-none d-lg-block">
          </div>

        </div>
      </div>
    </section>

    <section id="features" class="py-5" style="background:#f9fdf9;">
      <div class="container">
        <div class="text-center mb-5">
          <h2 style="color:#1b4d1b;font-weight:400;font-size:2.8rem;margin-bottom:0.5rem;font-family:Georgia,'Times New Roman',serif;">Everything You Need</h2>
          <p style="color:#2d5a2d;font-size:1rem;font-weight:400;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">Powerful tools to help you reach your health goals</p>
        </div>

        <div class="row g-4">
          <div class="col-md-6 col-lg-3" v-for="feature in features" :key="feature.title">
            <div class="h-100"
                 :style="`background:url('${feature.bgImage}') center/cover;border-radius:12px;padding:2rem 1.5rem;cursor:pointer;transition:all 0.3s;border:1px solid #d4e7d4;box-shadow:0 2px 8px rgba(27,77,27,0.1);position:relative;overflow:hidden;`"
                 @click="activeFeature = feature"
                 @mouseenter="$event.currentTarget.style.transform='translateY(-8px)';$event.currentTarget.style.boxShadow='0 12px 32px rgba(27,77,27,0.2)'"
                 @mouseleave="$event.currentTarget.style.transform='translateY(0)';$event.currentTarget.style.boxShadow='0 2px 8px rgba(27,77,27,0.1)'">
              <div style="position:absolute;top:0;left:0;right:0;bottom:0;background:rgba(249,253,249,0.85);backdrop-filter:blur(2px);"></div>
              <div style="position:relative;z-index:1;">
                <h5 style="color:#1b4d1b;font-weight:500;margin-bottom:1rem;font-size:1.2rem;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">{{ feature.title }}</h5>
                <ul class="list-unstyled mb-0">
                  <li v-for="item in feature.items.slice(0, 3)" :key="item" class="mb-2" style="color:#2d5a2d;font-size:0.9rem;display:flex;align-items:start;gap:0.5rem;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
                    <span style="color:#2e7d32;font-weight:700;">•</span>
                    <span>{{ item }}</span>
                  </li>
                </ul>
                <div class="mt-3" style="color:#1b4d1b;font-size:0.85rem;font-weight:500;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">Learn more →</div>
              </div>
            </div>
          </div>
        </div>

        <Teleport to="body">
          <div v-if="activeFeature"
               style="position:fixed;inset:0;background:rgba(27,77,27,0.4);backdrop-filter:blur(4px);z-index:1050;display:flex;align-items:center;justify-content:center;"
               @click.self="activeFeature = null">
            <div style="background:#ffffff;border-radius:12px;max-width:500px;width:90%;padding:2.5rem;position:relative;box-shadow:0 20px 60px rgba(27,77,27,0.3);">
              <button @click="activeFeature = null"
                      style="position:absolute;top:16px;right:16px;background:#f9fdf9;border:none;font-size:1.5rem;color:#2d5a2d;cursor:pointer;width:36px;height:36px;border-radius:50%;display:flex;align-items:center;justify-content:center;transition:all 0.2s;"
                      onmouseover="this.style.background='#e8f5e8';this.style.color='#1b4d1b'"
                      onmouseout="this.style.background='#f9fdf9';this.style.color='#2d5a2d'">×</button>
              <h4 class="fw-bold mb-2" style="color:#1b4d1b;font-size:1.8rem;font-family:Georgia,'Times New Roman',serif;font-weight:400;">{{ activeFeature.title }}</h4>
              <p class="mb-4" style="color:#2d5a2d;font-size:1rem;line-height:1.6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">{{ activeFeature.detail }}</p>
              <ul class="list-unstyled mb-4">
                <li v-for="item in activeFeature.items" :key="item" class="mb-3 d-flex align-items-start gap-2">
                  <span style="color:#2e7d32;font-weight:700;font-size:1.2rem;">•</span>
                  <span style="color:#2d5a2d;font-size:0.95rem;line-height:1.5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">{{ item }}</span>
                </li>
              </ul>
              <a href="#auth-section" class="btn w-100" @click="activeFeature = null" style="background:#1b4d1b;color:#ffffff;font-weight:500;padding:0.9rem;border-radius:6px;border:none;font-size:1rem;transition:all 0.2s;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;" onmouseover="this.style.background='#2e7d32'" onmouseout="this.style.background='#1b4d1b'">Get Started</a>
            </div>
          </div>
        </Teleport>
      </div>
    </section>

    <div style="height:1px;background:linear-gradient(to right, transparent, #d4e7d4 20%, #d4e7d4 80%, transparent);margin:0 auto;max-width:80%;"></div>

    <section class="py-5" style="background:#ffffff;position:relative;">
      <div class="container">
        <div class="text-center mb-5">
          <h2 style="color:#1b4d1b;font-weight:400;font-size:2.8rem;margin-bottom:0.5rem;font-family:Georgia,'Times New Roman',serif;">How It Works</h2>
          <p style="color:#2d5a2d;font-size:1rem;font-weight:400;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">Get started in four simple steps</p>
        </div>
        <div class="row g-4" style="position:relative;">
          <div style="position:absolute;top:50%;left:0;right:0;height:1px;background:#d4e7d4;z-index:0;transform:translateY(-50%);"></div>
          <div class="col-md-6 col-lg-3" v-for="step in steps" :key="step.num">
            <div class="h-100 text-center" style="background:#ffffff;border-radius:12px;padding:2rem 1.5rem;border:1px solid #d4e7d4;transition:all 0.3s;position:relative;z-index:1;box-shadow:0 2px 8px rgba(27,77,27,0.06);" onmouseover="this.style.transform='translateY(-6px)';this.style.boxShadow='0 8px 20px rgba(27,77,27,0.12)';this.style.borderColor='#2e7d32'" onmouseout="this.style.transform='translateY(0)';this.style.boxShadow='0 2px 8px rgba(27,77,27,0.06)';this.style.borderColor='#d4e7d4'">
              <div style="width:55px;height:55px;background:#ffffff;border:1px solid #2e7d32;border-radius:50%;display:flex;align-items:center;justify-content:center;margin:0 auto 1.5rem;position:relative;">
                <span style="font-size:1.5rem;font-weight:500;color:#2e7d32;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">{{ step.num }}</span>
              </div>
              <h5 class="mb-3" style="color:#1b4d1b;font-size:1.2rem;font-weight:500;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">{{ step.title }}</h5>
              <p class="mb-3" style="color:#2d5a2d;font-size:0.9rem;line-height:1.6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">{{ step.desc }}</p>
              <span style="background:#e8f5e8;color:#1b5e20;padding:0.35rem 0.9rem;border-radius:16px;display:inline-block;font-weight:500;font-size:0.8rem;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">{{ step.note }}</span>
            </div>
          </div>
        </div>
      </div>
    </section>

    <div style="height:1px;background:linear-gradient(to right, transparent, #d4e7d4 20%, #d4e7d4 80%, transparent);margin:0 auto;max-width:80%;"></div>

    <section id="auth-section" class="py-5" style="background:#ffffff;">
      <div class="container">
        <div class="text-center mb-5">
          <h2 style="color:#1b4d1b;font-weight:400;font-size:2.8rem;margin-bottom:0.5rem;font-family:Georgia,'Times New Roman',serif;">Get Started Today</h2>
          <p style="color:#2d5a2d;font-size:1rem;font-weight:400;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">Log in or create your free account</p>
        </div>

        <div class="row g-4 justify-content-center">

          <div class="col-md-6 col-lg-5">
            <div style="background:#ffffff;border-radius:12px;padding:2.5rem;box-shadow:0 4px 20px rgba(27,77,27,0.08);border:1px solid #d4e7d4;">
              <div style="margin-bottom:2rem;padding-bottom:1.5rem;border-bottom:2px solid #f9fdf9;">
                <h5 class="mb-1" style="color:#1b4d1b;font-size:1.5rem;font-weight:500;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">Welcome Back</h5>
                <p style="color:#2d5a2d;font-size:0.9rem;margin:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">Log in to your account</p>
              </div>

              <div class="mb-3">
                <label class="form-label" style="color:#1b4d1b;font-weight:500;font-size:0.9rem;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">Email Address</label>
                <input type="email" class="form-control"
                       placeholder="user@example.com"
                       v-model="loginForm.email"
                       style="border:1px solid #d4e7d4;border-radius:6px;padding:0.75rem 1rem;font-size:0.95rem;transition:all 0.2s;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;"
                       onfocus="this.style.borderColor='#2e7d32';this.style.boxShadow='0 0 0 3px rgba(46,125,50,0.1)'"
                       onblur="this.style.borderColor='#d4e7d4';this.style.boxShadow='none'">
              </div>

              <div class="mb-2">
                <label class="form-label" style="color:#1b4d1b;font-weight:500;font-size:0.9rem;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">Password</label>
                <input type="password" class="form-control"
                       placeholder="••••••••"
                       v-model="loginForm.password"
                       style="border:1px solid #d4e7d4;border-radius:6px;padding:0.75rem 1rem;font-size:0.95rem;transition:all 0.2s;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;"
                       onfocus="this.style.borderColor='#2e7d32';this.style.boxShadow='0 0 0 3px rgba(46,125,50,0.1)'"
                       onblur="this.style.borderColor='#d4e7d4';this.style.boxShadow='none'">
              </div>

              <div v-if="loginError" style="background:#ffebee;border:1px solid #ef5350;border-radius:6px;padding:0.75rem 1rem;margin-top:1rem;margin-bottom:0;">
                <span style="color:#c62828;font-size:0.9rem;font-weight:500;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">{{ loginError }}</span>
              </div>

              <button class="w-100 mt-4" @click="handleLogin" :disabled="loginLoading"
                      style="background:#1b4d1b;color:#ffffff;font-weight:500;padding:0.9rem;border-radius:6px;border:none;font-size:1rem;transition:all 0.2s;cursor:pointer;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;"
                      onmouseover="if(!this.disabled){this.style.background='#2e7d32'}"
                      onmouseout="this.style.background='#1b4d1b'">
                <span v-if="loginLoading" class="spinner-border spinner-border-sm me-2" role="status"></span>
                {{ loginLoading ? 'Logging In...' : 'Log In' }}
              </button>
            </div>
          </div>

          <div class="col-md-6 col-lg-5">
            <div style="background:#ffffff;border-radius:12px;padding:2.5rem;box-shadow:0 4px 20px rgba(27,77,27,0.08);border:1px solid #d4e7d4;">
              <div style="margin-bottom:2rem;padding-bottom:1.5rem;border-bottom:2px solid #f9fdf9;">
                <h5 class="mb-1" style="color:#1b4d1b;font-size:1.5rem;font-weight:500;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">Create Account</h5>
                <p style="color:#2d5a2d;font-size:0.9rem;margin:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">Join us for free today</p>
              </div>

              <div class="mb-3">
                <label class="form-label" style="color:#1b4d1b;font-weight:500;font-size:0.9rem;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">Full Name</label>
                <input type="text" class="form-control"
                       placeholder="Your name"
                       v-model="signupForm.name"
                       style="border:1px solid #d4e7d4;border-radius:6px;padding:0.75rem 1rem;font-size:0.95rem;transition:all 0.2s;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;"
                       onfocus="this.style.borderColor='#2e7d32';this.style.boxShadow='0 0 0 3px rgba(46,125,50,0.1)'"
                       onblur="this.style.borderColor='#d4e7d4';this.style.boxShadow='none'">
              </div>

              <div class="mb-3">
                <label class="form-label" style="color:#1b4d1b;font-weight:500;font-size:0.9rem;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">Email Address</label>
                <input type="email" class="form-control"
                       placeholder="user@example.com"
                       v-model="signupForm.email"
                       style="border:1px solid #d4e7d4;border-radius:6px;padding:0.75rem 1rem;font-size:0.95rem;transition:all 0.2s;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;"
                       onfocus="this.style.borderColor='#2e7d32';this.style.boxShadow='0 0 0 3px rgba(46,125,50,0.1)'"
                       onblur="this.style.borderColor='#d4e7d4';this.style.boxShadow='none'">
              </div>

              <div class="mb-3">
                <label class="form-label" style="color:#1b4d1b;font-weight:500;font-size:0.9rem;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">Password</label>
                <input type="password" class="form-control"
                       placeholder="Min. 8 characters"
                       v-model="signupForm.password"
                       minlength="8"
                       maxlength="30"
                       style="border:1px solid #d4e7d4;border-radius:6px;padding:0.75rem 1rem;font-size:0.95rem;transition:all 0.2s;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;"
                       onfocus="this.style.borderColor='#2e7d32';this.style.boxShadow='0 0 0 3px rgba(46,125,50,0.1)'"
                       onblur="this.style.borderColor='#d4e7d4';this.style.boxShadow='none'">
              </div>


              <div v-if="signupError" style="background:#ffebee;border:1px solid #ef5350;border-radius:6px;padding:0.75rem 1rem;margin-bottom:1rem;">
                <span style="color:#c62828;font-size:0.9rem;font-weight:500;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">{{ signupError }}</span>
              </div>
              <div v-if="signupSuccess" style="background:#e8f5e8;border:1px solid #2e7d32;border-radius:6px;padding:0.75rem 1rem;margin-bottom:1rem;">
                <span style="color:#1b5e20;font-size:0.9rem;font-weight:500;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">{{ signupSuccess }}</span>
              </div>

              <button class="w-100" @click="handleSignup" :disabled="signupLoading"
                      style="background:#1b4d1b;color:#ffffff;font-weight:500;padding:0.9rem;border-radius:6px;border:none;font-size:1rem;transition:all 0.2s;cursor:pointer;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;"
                      onmouseover="if(!this.disabled){this.style.background='#2e7d32'}"
                      onmouseout="this.style.background='#1b4d1b'">
                <span v-if="signupLoading" class="spinner-border spinner-border-sm me-2" role="status"></span>
                {{ signupLoading ? 'Creating Account...' : 'Create My Account' }}
              </button>
            </div>
          </div>

        </div>
      </div>
    </section>

  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { login, register, authError } from '../auth.js'

const router = useRouter()

const loginForm = ref({ email: '', password: '' })
const signupForm = ref({ name: '', email: '', password: '' })

const loginLoading = ref(false)
const loginError = ref('')
const signupLoading = ref(false)
const signupError = ref('')
const signupSuccess = ref('')

async function handleLogin() {
  loginError.value = ''
  loginLoading.value = true
  try {
    const ok = await login(loginForm.value.email, loginForm.value.password)
    if (ok) {
      router.push('/dashboard')
    } else {
      loginError.value = authError.value || 'Login failed'
    }
  } finally {
    loginLoading.value = false
  }
}

function isValidEmail(email) {
  const atIndex = email.indexOf('@')
  return atIndex > 0 && email.endsWith('.com') && atIndex < email.length - 1
}

async function handleSignup() {
  signupError.value = ''
  signupSuccess.value = ''
  if (!isValidEmail(signupForm.value.email)) {
    signupError.value = 'Please enter a valid email address'
    return
  }
  if (signupForm.value.password.length < 8) {
    signupError.value = 'Password must be at least 8 characters'
    return
  }
  signupLoading.value = true
  try {
    const ok = await register(
      signupForm.value.email,
      signupForm.value.name,
      signupForm.value.password,
      false,
    )
    if (ok) {
      signupSuccess.value = 'Account created! You can now log in.'
      signupForm.value = { name: '', email: '', password: '' }
    } else {
      signupError.value = authError.value || 'Registration failed'
    }
  } finally {
    signupLoading.value = false
  }
}

const activeFeature = ref(null)

const features = [
  {
    title: 'Food Diary',
    //bgImage: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&q=80',
    detail: 'Keep a complete record of everything you eat and drink. Log meals quickly, revisit past entries, and build healthy habits over time.',
    items: [
      'Log daily meals & snacks',
      'View historical entries',
      'Search past records',
      'Quick-add frequent foods',
    ],
  },
  {
    title: 'Nutrition',
    //bgImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    detail: 'Get a detailed breakdown of your calorie and macronutrient intake, aligned with NHS guidelines and your personal targets.',
    items: [
      'Calorie & macro tracking',
      'Follow NHS guidelines',
      'Trend graphs & charts',
      'Weekly & monthly reports',
      'Personalised targets',
    ],
  },
  {
    title: 'Recipes',
    //bgImage: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&q=80',
    detail: 'Browse a curated library of healthy, home-cooked recipes. Save your favourites and add them straight to your diary.',
    items: [
      'Curated healthy recipes',
      'Save favourites',
      'Full cooking instructions',
      'Add directly to diary',
    ],
  },
  {
    title: 'Pro Support',
    //bgImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80',
    detail: 'Get paired with a registered nutritionist who can monitor your progress, set goals with you, and offer personalised guidance.',
    items: [
      'Assigned nutritionist',
      'Progress monitoring',
      'Personalised advice',
      'Direct messaging',
      'Goal setting support',
    ],
  },
]

const steps = [
  { num: '1', title: 'Sign Up', desc: 'Create your account and set your goals', note: 'Free to join' },
  { num: '2', title: 'Log Meals', desc: 'Record what you eat each day', note: 'Quick & easy' },
  { num: '3', title: 'Get Insights', desc: 'View trends and nutrition feedback', note: 'Personalised' },
  { num: '4', title: 'Improve', desc: 'Follow advice & hit your targets', note: 'With pro support' },
]
</script>
