// Initial template generated by Claude, with wiring up, edits, and function edits done manually with AI guidance
<template>
  <div class="container-fluid px-4 py-3">

    <div class="p-3 mb-3 rounded" style="background:#e8f4e6;border:1px solid #5a9e56;">
      <h4 style="color:#5a9e56;" class="mb-0">Messages</h4>
      <small class="text-secondary">Communicate with your nutrition professional</small>
    </div>

    <div class="row g-3">

      <div class="col-md-4">

        <div class="card card-gf p-3 mb-3">
          <div class="d-flex align-items-center gap-3">
            <div class="avatar-circle" style="width:52px;height:52px;font-size:1rem;">?</div>
            <div>
              <div class="fw-bold text-muted">No professional assigned</div>
              <div class="text-muted small">A nutritionist will be linked to your account</div>
            </div>
          </div>
          <hr>
          <div class="small text-muted">
            <div class="mb-1">Next check-in: —</div>
            <div>Last report shared: —</div>
          </div>
        </div>

        <div class="card border p-3">
          <h6 class="fw-bold mb-2" style="color:#5a9e56;">Shared Goals</h6>
          <div class="small text-muted">
            <div>No shared goals yet.</div>
          </div>
        </div>

      </div>

      <div class="col-md-8">
        <div class="card border" style="height:420px;display:flex;flex-direction:column;">
          <div class="card-header fw-bold small" style="background:#e8f4e6;">
            Conversation
          </div>

          <div class="card-body overflow-auto flex-grow-1 p-3" ref="chatBody">
            <div v-if="messages.length === 0" class="text-center text-muted py-4">
              <small>No messages yet. Your conversation with your nutritionist will appear here.</small>
            </div>
            <div v-for="msg in messages" :key="msg.id" class="mb-2">

              <div v-if="msg.from === 'pro'" class="chat-pro" style="max-width:80%;">
                <div class="fw-semibold small mb-1" style="color:#5a9e56;">Your Nutritionist</div>
                <div class="small">{{ msg.text }}</div>
                <div class="text-muted mt-1" style="font-size:0.7rem;">{{ msg.time }}</div>
              </div>

              <div v-else class="chat-mine ms-auto" style="max-width:80%;">
                <div class="small">{{ msg.text }}</div>
                <div class="text-muted mt-1" style="font-size:0.7rem;">{{ msg.time }}</div>
              </div>

            </div>
          </div>

          <div class="card-footer p-2" style="background:#f9f9f9;">
            <div class="d-flex gap-2">
              <input type="text"
                     class="form-control form-control-sm"
                     placeholder="Type a message..."
                     v-model="newMessage"
                     @keyup.enter="sendMessage">
              <button class="btn btn-gf btn-sm px-3" @click="sendMessage">Send</button>
            </div>
          </div>

        </div>
      </div>

    </div>

  </div>
</template>

<script setup>
import { ref } from 'vue'

const newMessage = ref('')

// To do: load existing messages from /api/ and POST new ones
const messages = ref([])

function sendMessage() {
  if (!newMessage.value.trim()) return

  messages.value.push({
    id: Date.now(),
    from: 'me',
    text: newMessage.value,
    time: 'Just now',
  })

  newMessage.value = ''
}
</script>
