// Initial template generated by Claude, with wiring up, edits, and function edits done manually with AI guidance
<template>
  <div class="container-fluid px-4 py-3 d-flex flex-column" style="height:calc(100vh - 104px);overflow:hidden;">

    <div class="p-3 mb-3 rounded" style="background:#e8f4e6;border:1px solid #5a9e56;">
      <h4 style="color:#5a9e56;" class="mb-0">Messages</h4>
      <small class="text-secondary">
        {{ isProfessional ? 'Message your clients' : 'Communicate with your nutrition professional' }}
      </small>
    </div>

    <!-- Professional view -->
    <template v-if="isProfessional">
      <div v-if="loadingClients" class="text-muted small text-center py-4">Loading clients…</div>
      <div v-else-if="clientsError" class="alert alert-danger small">{{ clientsError }}</div>
      <div v-else-if="clients.length === 0"
           class="text-center text-muted py-5 border rounded"
           style="border-style:dashed!important;">
        <p class="mb-1">No active clients yet.</p>
        <small>Clients will appear here once they accept your invitation.</small>
      </div>
      <div v-else class="row g-3 flex-grow-1" style="min-height:0;">

        <div class="col-md-4">
          <div class="list-group">
            <button
              v-for="client in clients"
              :key="client.id"
              class="list-group-item list-group-item-action d-flex align-items-center gap-3"
              :style="selectedClient?.id === client.id ? 'background:#5a9e56;color:#fff;border-color:#5a9e56;' : ''"
              @click="selectClient(client)"
            >
              <div class="avatar-circle flex-shrink-0"
                   style="width:38px;height:38px;font-size:0.85rem;"
                   :style="selectedClient?.id === client.id ? 'background:#fff;color:#5a9e56;' : ''">
                {{ initialsFor(client.subscriber.fullName) }}
              </div>
              <div class="text-start overflow-hidden">
                <div class="fw-bold small text-truncate">{{ client.subscriber.fullName }}</div>
                <div class="text-muted" style="font-size:0.75rem;">ID {{ client.subscriberId }}</div>
              </div>
            </button>
          </div>
        </div>

        <div class="col-md-8 d-flex flex-column" style="min-height:0;">
          <div v-if="!selectedClient" class="text-muted small text-center py-5 border rounded"
               style="border-style:dashed!important;">
            Select a client to start messaging.
          </div>
          <div v-else class="card border flex-grow-1" style="min-height:0;display:flex;flex-direction:column;">
            <div class="card-header fw-bold small" style="background:#e8f4e6;">
              Conversation with {{ selectedClient.subscriber.fullName }}
            </div>

            <div class="card-body overflow-auto flex-grow-1 p-3" ref="proChatBody">
              <div v-if="proChat.loading" class="text-muted small text-center py-4">Loading messages…</div>
              <div v-else-if="proChat.error" class="alert alert-danger small">{{ proChat.error }}</div>
              <div v-else-if="proChat.messages.length === 0" class="text-center text-muted py-4">
                <small>No messages yet. Start the conversation below.</small>
              </div>
              <template v-else>
                <div v-for="msg in proChat.messages" :key="msg.id" class="mb-2">
                  <div v-if="msg.sentBy === 'professional'" class="chat-mine ms-auto" style="max-width:80%;">
                    <div class="small">{{ msg.message }}</div>
                    <div class="text-muted mt-1" style="font-size:0.65rem;">{{ formatDateTime(msg.createdAt) }}</div>
                  </div>
                  <div v-else class="chat-pro" style="max-width:80%;">
                    <div class="fw-semibold small mb-1" style="color:#5a9e56;">
                      {{ selectedClient.subscriber.fullName }}
                    </div>
                    <div class="small">{{ msg.message }}</div>
                    <div class="text-muted mt-1" style="font-size:0.65rem;">{{ formatDateTime(msg.createdAt) }}</div>
                  </div>
                </div>
              </template>
            </div>

            <div class="card-footer p-2" style="background:#f9f9f9;">
              <div v-if="proChat.sendError" class="alert alert-danger py-1 small mb-2">{{ proChat.sendError }}</div>
              <div class="d-flex gap-2">
                <input type="text"
                       class="form-control form-control-sm"
                       placeholder="Type a message…"
                       v-model="proChat.draft"
                       :disabled="proChat.sending"
                       @keyup.enter="proSendMessage">
                <button class="btn btn-gf btn-sm px-3"
                        @click="proSendMessage"
                        :disabled="proChat.sending || !proChat.draft.trim()">
                  {{ proChat.sending ? '…' : 'Send' }}
                </button>
              </div>
            </div>
          </div>
        </div>

      </div>
    </template>

    <!-- Subscriber view -->
    <template v-else>
      <div v-if="loadingPro" class="text-muted small text-center py-4">Loading...</div>
      <div v-else-if="proError" class="alert alert-danger small">{{ proError }}</div>

      <div v-else-if="!professional" class="text-center text-muted py-5 border rounded"
           style="border-style:dashed!important;">
        <p class="mb-1">No professional assigned yet.</p>
        <small>A nutritionist will appear here once they invite you and you accept.</small>
      </div>

      <div v-else class="row g-3 flex-grow-1" style="min-height:0;">

        <div class="col-md-4">
          <div class="card card-gf p-3 mb-3">
            <div class="d-flex align-items-center gap-3">
              <div class="avatar-circle" style="width:52px;height:52px;font-size:1rem;">
                {{ initialsFor(professional.professional.fullName) }}
              </div>
              <div>
                <div class="fw-bold">{{ professional.professional.fullName }}</div>
                <div class="text-muted small">{{ professional.professional.email }}</div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-8 d-flex flex-column" style="min-height:0;">
          <div class="card border flex-grow-1" style="min-height:0;display:flex;flex-direction:column;">
            <div class="card-header fw-bold small" style="background:#e8f4e6;">
              Conversation with {{ professional.professional.fullName }}
            </div>

            <div class="card-body overflow-auto flex-grow-1 p-3" ref="chatBody">
              <div v-if="loadingMessages" class="text-muted small text-center py-4">Loading messages...</div>
              <div v-else-if="messagesError" class="alert alert-danger small">{{ messagesError }}</div>
              <div v-else-if="messages.length === 0" class="text-center text-muted py-4">
                <small>No messages yet. Start the conversation below.</small>
              </div>
              <template v-else>
                <div v-for="msg in messages" :key="msg.id" class="mb-2">
                  <div v-if="msg.sentBy === 'professional'" class="chat-pro" style="max-width:80%;">
                    <div class="fw-semibold small mb-1" style="color:#5a9e56;">
                      {{ professional.professional.fullName }}
                    </div>
                    <div class="small">{{ msg.message }}</div>
                    <div class="text-muted mt-1" style="font-size:0.7rem;">{{ formatDateTime(msg.createdAt) }}</div>
                  </div>
                  <div v-else class="chat-mine ms-auto" style="max-width:80%;">
                    <div class="small">{{ msg.message }}</div>
                    <div class="text-muted mt-1" style="font-size:0.7rem;">{{ formatDateTime(msg.createdAt) }}</div>
                  </div>
                </div>
              </template>
            </div>

            <div class="card-footer p-2" style="background:#f9f9f9;">
              <div v-if="sendError" class="alert alert-danger py-1 small mb-2">{{ sendError }}</div>
              <div class="d-flex gap-2">
                <input type="text"
                       class="form-control form-control-sm"
                       placeholder="Type a message..."
                       v-model="newMessage"
                       :disabled="sending"
                       @keyup.enter="sendMessage">
                <button class="btn btn-gf btn-sm px-3" @click="sendMessage" :disabled="sending || !newMessage.trim()">
                  {{ sending ? '...' : 'Send' }}
                </button>
              </div>
            </div>

          </div>
        </div>

      </div>
    </template>

  </div>
</template>

<script setup>
import { ref, reactive, nextTick, onMounted } from 'vue'
import { apiFetch, currentUser } from '../auth.js'

const isProfessional = currentUser.value.role === 'professional'

// ── Professional state ────────────────────────────────────────────────────────
const clients = ref([])
const loadingClients = ref(false)
const clientsError = ref('')
const selectedClient = ref(null)
const proChatBody = ref(null)

const proChat = reactive({
  loading: false,
  error: '',
  messages: [],
  draft: '',
  sending: false,
  sendError: '',
})

async function loadClients() {
  loadingClients.value = true
  clientsError.value = ''
  try {
    const res = await apiFetch('/api/professional/clients')
    const data = await res.json().catch(() => ({}))
    if (!res.ok) {
      clientsError.value = data.error || 'Failed to load clients'
      return
    }
    clients.value = data.clients ?? []
  } catch {
    clientsError.value = 'Network error - could not load clients'
  } finally {
    loadingClients.value = false
  }
}

async function selectClient(client) {
  selectedClient.value = client
  proChat.messages = []
  proChat.error = ''
  proChat.sendError = ''
  proChat.draft = ''
  await loadProMessages()
}

async function loadProMessages() {
  proChat.loading = true
  proChat.error = ''
  try {
    const res = await apiFetch(`/api/professional/clients/${selectedClient.value.subscriberId}/messages`)
    const data = await res.json().catch(() => ({}))
    if (!res.ok) {
      proChat.error = data.error || 'Failed to load messages'
      return
    }
    proChat.messages = (data.messages ?? []).slice().reverse()
    await scrollProToBottom()
  } catch {
    proChat.error = 'Network error'
  } finally {
    proChat.loading = false
  }
}

async function proSendMessage() {
  const text = proChat.draft.trim()
  if (!text || proChat.sending) return
  proChat.sendError = ''
  proChat.sending = true
  try {
    const res = await apiFetch(`/api/professional/clients/${selectedClient.value.subscriberId}/messages`, {
      method: 'POST',
      body: JSON.stringify({ message: text }),
    })
    const data = await res.json().catch(() => ({}))
    if (!res.ok) {
      proChat.sendError = data.error || 'Failed to send message'
      return
    }
    proChat.draft = ''
    await loadProMessages()
  } catch {
    proChat.sendError = 'Network error'
  } finally {
    proChat.sending = false
  }
}

async function scrollProToBottom() {
  await nextTick()
  if (proChatBody.value) proChatBody.value.scrollTop = proChatBody.value.scrollHeight
}

// ── Subscriber state ──────────────────────────────────────────────────────────
const professional = ref(null)
const loadingPro = ref(true)
const proError = ref('')

const messages = ref([])
const loadingMessages = ref(false)
const messagesError = ref('')

const newMessage = ref('')
const sending = ref(false)
const sendError = ref('')

const chatBody = ref(null)

async function loadProfessional() {
  loadingPro.value = true
  proError.value = ''
  try {
    const res = await apiFetch('/api/client/professionals')
    const data = await res.json().catch(() => ({}))
    if (!res.ok) {
      proError.value = data.error || 'Failed to load professional'
      return
    }
    const list = data.professionals ?? []
    professional.value = list[0] ?? null
    if (professional.value) await loadMessages()
  } catch {
    proError.value = 'Network error - could not load professional'
  } finally {
    loadingPro.value = false
  }
}

async function loadMessages() {
  loadingMessages.value = true
  messagesError.value = ''
  try {
    const res = await apiFetch(`/api/client/professionals/${professional.value.professionalId}/messages`)
    const data = await res.json().catch(() => ({}))
    if (!res.ok) {
      messagesError.value = data.error || 'Failed to load messages'
      return
    }
    messages.value = (data.messages ?? []).slice().reverse()
    await scrollToBottom()
  } catch {
    messagesError.value = 'Network error - could not load messages'
  } finally {
    loadingMessages.value = false
  }
}

async function sendMessage() {
  const text = newMessage.value.trim()
  if (!text || sending.value) return
  sendError.value = ''
  sending.value = true
  try {
    const res = await apiFetch(`/api/client/professionals/${professional.value.professionalId}/messages`, {
      method: 'POST',
      body: JSON.stringify({ message: text }),
    })
    const data = await res.json().catch(() => ({}))
    if (!res.ok) {
      sendError.value = data.error || 'Failed to send message'
      return
    }
    newMessage.value = ''
    await loadMessages()
  } catch {
    sendError.value = 'Network error - could not send message'
  } finally {
    sending.value = false
  }
}

async function scrollToBottom() {
  await nextTick()
  if (chatBody.value) chatBody.value.scrollTop = chatBody.value.scrollHeight
}

// ── Shared helpers ────────────────────────────────────────────────────────────
function initialsFor(name) {
  if (!name) return '?'
  return name.trim().split(/\s+/).slice(0, 2).map(p => p[0].toUpperCase()).join('') || '?'
}

function formatDateTime(value) {
  if (!value) return ''
  const d = new Date(value)
  if (Number.isNaN(d.getTime())) return ''
  return d.toLocaleString('en-GB', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })
}

onMounted(() => {
  if (isProfessional) loadClients()
  else loadProfessional()
})
</script>
