// Initial template generated by Claude, with wiring up, edits, and function edits done manually with AI guidance
<template>
  <div class="container-fluid px-4 py-3">

    <div class="d-flex justify-content-between align-items-center mb-5">
      <div>
        <h2 class="mb-1" style="color:#1b4d1b;font-weight:600;font-size:1.75rem;">Nutritional Overview</h2>
        <p class="mb-0" style="color:#6b7280;font-size:0.9375rem;">Detailed breakdown of your nutritional intake</p>
      </div>
      <div class="d-flex align-items-center gap-2">
        <div class="d-flex gap-2">
          <button v-for="p in PERIOD_OPTIONS" :key="p.value"
                  class="btn"
                  :style="period === p.value ? 'background:#1b4d1b;color:#fff;border:none;padding:0.5rem 1rem;border-radius:8px;font-size:0.875rem;font-weight:500;' : 'background:#f3f4f6;color:#6b7280;border:none;padding:0.5rem 1rem;border-radius:8px;font-size:0.875rem;font-weight:500;'"
                  @click="period = p.value; load()">
            {{ p.label }}
          </button>
        </div>
        <input type="date" class="form-control" style="width:160px;border:1px solid #d4e7d4;border-radius:8px;padding:0.5rem 0.75rem;font-size:0.875rem;"
               v-model="endDate" @change="load()">
      </div>
    </div>

    <div v-if="loading" class="text-center text-muted py-5"><small>Loading…</small></div>
    <div v-else-if="error" class="alert alert-danger small">{{ error }}</div>

    <template v-else>

      <div class="row g-4 mb-4">

        <div class="col-md-4">
          <div class="card border p-3 text-center h-100">
            <h6 class="fw-bold mb-2" style="color:#1b4d1b;">Calories</h6>
            <svg viewBox="0 0 160 160" width="160" height="160" style="margin:0 auto;display:block;">
              <circle cx="80" cy="80" r="62" fill="none" stroke="#e9ecef" stroke-width="18"/>
              <circle cx="80" cy="80" r="62" fill="none" stroke="#1b4d1b" stroke-width="18"
                      stroke-dasharray="389.6"
                      :stroke-dashoffset="calorieOffset"
                      stroke-linecap="round"
                      transform="rotate(-90 80 80)"/>
              <text x="80" y="74" text-anchor="middle" font-size="18" font-weight="bold" fill="#1b4d1b">
                {{ nutrient('calories')?.totalAmount ?? 0 }}
              </text>
              <text x="80" y="90" text-anchor="middle" font-size="10" fill="#888">kcal</text>
            </svg>
            <div class="mt-2 text-start small text-muted">
              <div>Eaten: <strong>{{ nutrient('calories')?.totalAmount ?? 0 }} kcal</strong></div>
              <div>Reference: <strong>{{ scaledRefs.calories.label }}</strong></div>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="card border p-3 text-center h-100" style="position:relative;">
            <h6 class="fw-bold mb-2" style="color:#1b4d1b;">Macronutrients</h6>
            <div style="position:absolute;top:8px;right:8px;text-align:center;">
              <svg viewBox="0 0 160 160" width="60" height="60" style="display:block;">
                <circle cx="80" cy="80" r="62" fill="none" stroke="#e9ecef" stroke-width="18"/>
                <template v-for="seg in IDEAL_MACRO_SEGS" :key="seg.code">
                  <circle cx="80" cy="80" r="62" fill="none"
                          :stroke="seg.color" stroke-width="18"
                          :stroke-dasharray="`${seg.dash} ${seg.gap}`"
                          :stroke-dashoffset="seg.offset"
                          transform="rotate(-90 80 80)"/>
                </template>
              </svg>
              <span style="font-size:0.6rem;color:#888;">Ideal</span>
            </div>
            <svg viewBox="0 0 160 160" width="160" height="160" style="margin:0 auto;display:block;">
              <circle cx="80" cy="80" r="62" fill="none" stroke="#e9ecef" stroke-width="18"/>
              <template v-for="seg in macroSegs" :key="seg.code">
                <circle cx="80" cy="80" r="62" fill="none"
                        :stroke="seg.color" stroke-width="18"
                        :stroke-dasharray="`${seg.dash} ${seg.gap}`"
                        :stroke-dashoffset="seg.offset"
                        transform="rotate(-90 80 80)"/>
              </template>
              <text x="80" y="80" text-anchor="middle" font-size="10" fill="#555">Macros</text>
            </svg>
            <div class="mt-2 text-start small">
              <div v-for="m in macroLegend" :key="m.code" class="d-flex align-items-center gap-1 mb-1">
                <span style="display:inline-block;width:10px;height:10px;border-radius:2px;"
                      :style="`background:${m.color};`"></span>
                <span class="text-muted">{{ m.name }}:</span>
                <strong>{{ m.amount }} {{ m.unit }}</strong>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="card border p-3 text-center h-100" style="position:relative;">
            <h6 class="fw-bold mb-2" style="color:#1b4d1b;">Micronutrients</h6>
            <div style="position:absolute;top:8px;right:8px;text-align:center;">
              <svg viewBox="0 0 160 160" width="60" height="60" style="display:block;">
                <circle cx="80" cy="80" r="62" fill="none" stroke="#e9ecef" stroke-width="18"/>
                <template v-for="seg in IDEAL_MICRO_SEGS" :key="seg.code">
                  <circle cx="80" cy="80" r="62" fill="none"
                          :stroke="seg.color" stroke-width="18"
                          :stroke-dasharray="`${seg.dash} ${seg.gap}`"
                          :stroke-dashoffset="seg.offset"
                          transform="rotate(-90 80 80)"/>
                </template>
              </svg>
              <span style="font-size:0.6rem;color:#888;">Ideal</span>
            </div>
            <svg viewBox="0 0 160 160" width="160" height="160" style="margin:0 auto;display:block;">
              <circle cx="80" cy="80" r="62" fill="none" stroke="#e9ecef" stroke-width="18"/>
              <template v-for="seg in microSegs" :key="seg.code">
                <circle cx="80" cy="80" r="62" fill="none"
                        :stroke="seg.color" stroke-width="18"
                        :stroke-dasharray="`${seg.dash} ${seg.gap}`"
                        :stroke-dashoffset="seg.offset"
                        transform="rotate(-90 80 80)"/>
              </template>
              <text x="80" y="80" text-anchor="middle" font-size="10" fill="#555">Micros</text>
            </svg>
            <div class="mt-2 text-start small">
              <div v-for="m in microLegend" :key="m.code" class="d-flex align-items-center gap-1 mb-1">
                <span style="display:inline-block;width:10px;height:10px;border-radius:2px;"
                      :style="`background:${m.color};`"></span>
                <span class="text-muted">{{ m.name }}:</span>
                <strong>{{ m.amount }} {{ m.unit }}</strong>
              </div>
            </div>
          </div>
        </div>

      </div>

      <h6 class="fw-bold mb-2" style="color:#1b4d1b;">Full Nutrient Breakdown</h6>
      <div class="table-responsive mb-4">
        <table class="table table-sm table-striped border">
          <thead style="background:#1b4d1b;color:#fff;">
            <tr>
              <th class="small">Nutrient</th>
              <th class="small">Amount</th>
              <th class="small">Unit</th>
              <th class="small">Reference</th>
              <th class="small">Progress</th>
            </tr>
          </thead>
          <tbody>
            <tr v-if="breakdown.length === 0">
              <td colspan="5" class="text-center text-muted small py-3">No data for this period. Log meals to see your breakdown.</td>
            </tr>
            <tr v-for="row in breakdown" :key="row.code">
              <td class="small fw-semibold">{{ row.name }}</td>
              <td class="small">{{ row.amount }}</td>
              <td class="small text-muted">{{ row.unit }}</td>
              <td class="small text-muted">{{ row.reference }}</td>
              <td style="width:120px;">
                <div class="progress" style="height:8px;">
                  <div class="progress-bar" :style="`width:${row.pct}%;background-color:${row.color};`"></div>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <h6 class="fw-bold mb-2" style="color:#1b4d1b;">Insights</h6>
      <div class="card border p-3 mb-4">
        <div v-if="insights.length === 0" class="text-muted small">
          Your intake looks balanced for this period. Keep it up!
        </div>
        <div v-else class="d-flex flex-column gap-2">
          <div v-for="ins in insights" :key="ins.code"
               class="d-flex align-items-start gap-2 p-2 rounded"
               :style="`background:${ins.bg};`">
            <div>
              <div class="fw-semibold small" :style="`color:${ins.color};`">{{ ins.title }}</div>
              <div class="small text-muted">{{ ins.message }}</div>
            </div>
            <span class="ms-auto badge align-self-center"
                  :style="`background:${ins.color};font-size:0.65rem;`">
              {{ ins.pctLabel }}
            </span>
          </div>
        </div>
      </div>

      <h6 class="fw-bold mb-3" style="color:#1b4d1b;">7-Day Calorie Trend</h6>
      <div class="card border p-3 mb-4">
        <div class="d-flex align-items-end gap-2 justify-content-center px-2"
             style="height:140px;position:relative;">
          <div v-for="bar in weekBars" :key="bar.day"
               class="d-flex flex-column align-items-center gap-1" style="flex:1;max-width:72px;">
            <small :style="`font-size:0.65rem;font-weight:600;color:${bar.over ? '#b8860b' : '#1b4d1b'};`">
              {{ bar.val }}
            </small>
            <div style="width:100%;flex:1;display:flex;align-items:flex-end;position:relative;">
              <div style="position:absolute;bottom:0;left:0;right:0;border-radius:4px 4px 0 0;overflow:hidden;"
                   :style="`height:${bar.goalHeight}px;background:#f5d87a;`">
              </div>
              <div v-if="bar.height > 0"
                   style="position:absolute;bottom:0;left:0;right:0;border-radius:4px 4px 0 0;overflow:hidden;"
                   :style="`height:${bar.height}px;`">
                <div :style="`height:${bar.withinHeight}px;background:#1b4d1b;`"></div>
                <div v-if="bar.excessHeight > 0" :style="`height:${bar.excessHeight}px;background:#b8860b;`"></div>
              </div>
            </div>
            <small style="font-size:0.65rem;color:#888;">{{ bar.day }}</small>
          </div>
        </div>
        <div class="d-flex gap-3 mt-2">
          <span style="font-size:0.7rem;color:#888;display:flex;align-items:center;gap:4px;">
            <span style="display:inline-block;width:10px;height:10px;border-radius:2px;background:#f5d87a;"></span> Goal ({{ scaledRefs.calories.ref }} kcal)
          </span>
          <span style="font-size:0.7rem;color:#888;display:flex;align-items:center;gap:4px;">
            <span style="display:inline-block;width:10px;height:10px;border-radius:2px;background:#1b4d1b;"></span> Within goal
          </span>
          <span style="font-size:0.7rem;color:#888;display:flex;align-items:center;gap:4px;">
            <span style="display:inline-block;width:10px;height:10px;border-radius:2px;background:#b8860b;"></span> Over goal
          </span>
        </div>
        <small class="text-muted mt-1 d-block" style="font-size:0.7rem;">* Today's count is still in progress</small>
      </div>

    </template>

  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { apiFetch } from '../auth.js'

const PERIOD_OPTIONS = [
  { label: 'Today', value: 'daily' },
  { label: 'Week', value: 'weekly' },
  { label: 'Month', value: 'monthly' },
]

const PERIOD_DAYS = { daily: 1, weekly: 7, monthly: 30 }

const FALLBACK_REFS = {
  calories:      { ref: 2000, unit: 'kcal' },
  protein:       { ref: 50,   unit: 'g' },
  carbohydrates: { ref: 260,  unit: 'g' },
  fat:           { ref: 70,   unit: 'g' },
  fibre:         { ref: 30,   unit: 'g' },
  sugar:         { ref: 30,   unit: 'g' },
  salt:          { ref: 6,    unit: 'g' },
}

const todayIso = () => new Date().toISOString().slice(0, 10)

const period = ref('daily')
const endDate = ref(todayIso())
const loading = ref(true)
const error = ref('')
const nutrients = ref([])
const weekBars = ref([])
const goalRefs = ref({})

function buildGoalRefs(goals) {
  const map = {}
  for (const goal of goals) {
    if (!goal.nutrient?.code || goal.status !== 'active') continue
    const code = goal.nutrient.code
    map[code] = {
      min: goal.targetMin != null ? Number(goal.targetMin) : null,
      max: goal.targetMax != null ? Number(goal.targetMax) : null,
      unit: goal.nutrient.unit,
    }
  }
  return map
}

const scaledRefs = computed(() => {
  const days = PERIOD_DAYS[period.value] ?? 1
  const result = {}
  for (const [code, fallback] of Object.entries(FALLBACK_REFS)) {
    const goal = goalRefs.value[code]
    const isMaxNutrient = OVER_WATCH.includes(code) && !UNDER_WATCH.includes(code)
    const isMinNutrient = UNDER_WATCH.includes(code) && !OVER_WATCH.includes(code)
    // calories and carbs appear in both use max if set, else min
    let baseRef
    if (goal) {
      baseRef = isMaxNutrient ? (goal.max ?? goal.min ?? fallback.ref)
              : isMinNutrient ? (goal.min ?? goal.max ?? fallback.ref)
              : (goal.max ?? goal.min ?? fallback.ref)
    } else {
      baseRef = fallback.ref
    }
    const unit = goal?.unit ?? fallback.unit
    const scaled = baseRef * days
    const isMax = goal ? (goal.max != null && goal.min == null) : (code === 'fat' || code === 'sugar' || code === 'salt')
    const label = `${isMax ? '≤ ' : '≥ '}${scaled % 1 === 0 ? scaled : scaled.toFixed(1)} ${unit}`
    result[code] = { ref: scaled, unit, label }
  }
  return result
})

async function load() {
  loading.value = true
  error.value = ''
  try {
    const params = new URLSearchParams({ period: period.value, endDate: endDate.value })
    const [summaryRes, dashRes, goalsRes] = await Promise.all([
      apiFetch(`/api/diary/summary?${params}`),
      apiFetch('/api/diary/dashboard'),
      apiFetch('/api/goals'),
    ])

    const summaryData = await summaryRes.json().catch(() => ({}))
    if (!summaryRes.ok) {
      error.value = summaryData.error || summaryData.message || 'Failed to load nutrition data'
      return
    }
    nutrients.value = summaryData.summary?.nutrients ?? []

    const goalsData = await goalsRes.json().catch(() => ({}))
    if (goalsRes.ok) {
      goalRefs.value = buildGoalRefs(goalsData.goals ?? [])
    }

    const dashData = await dashRes.json().catch(() => ({}))
    if (dashRes.ok) {
      const trend = dashData.dashboardData?.weeklyCaloryTrend ?? dashData.weeklyCaloryTrend ?? []
      weekBars.value = buildWeekBars(trend)
    }
  } catch {
    error.value = 'Network error - could not load nutrition data'
  } finally {
    loading.value = false
  }
}

const DAY_LABELS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
const MAX_BAR_H = 100

function buildWeekBars(trend) {
  const calorieGoal = goalRefs.value['calories']?.ref ?? FALLBACK_REFS.calories.ref
  if (!trend.length) {
    return DAY_LABELS.map(day => ({ day, val: '-', height: 0, goalHeight: MAX_BAR_H, withinHeight: 0, excessHeight: 0, over: false }))
  }
  const maxCal = Math.max(...trend.map(d => d.calories), calorieGoal)
  const goalHeight = Math.round((calorieGoal / maxCal) * MAX_BAR_H)
  const todayStr = todayIso()
  return trend.map((d, i) => {
    const cal = Math.round(d.calories)
    const over = cal > calorieGoal
    const isToday = d.date === todayStr
    const height = cal > 0 ? Math.max(3, Math.round((cal / maxCal) * MAX_BAR_H)) : 0
    const withinHeight = over ? goalHeight : height
    const excessHeight = over ? height - goalHeight : 0
    return {
      day: isToday ? 'Today' : DAY_LABELS[i] ?? d.date.slice(5),
      val: cal > 0 ? String(cal) : '-',
      height,
      goalHeight,
      withinHeight,
      excessHeight,
      over,
    }
  })
}

const NUTRIENT_COLORS = {
  carbohydrates: '#4e9af1',
  protein:       '#1b4d1b',
  fat:           '#e8a820',
  fibre:         '#a86cc1',
  sugar:         '#d94f4f',
  salt:          '#6ec6c2',
}

const MACRO_CODES = ['carbohydrates', 'protein', 'fat']
const MICRO_CODES = ['fibre', 'sugar', 'salt']

const SVG_CIRC = 2 * Math.PI * 62  // ≈ 389.6

function nutrient(code) {
  return nutrients.value.find(n => n.code === code)
}

const calorieOffset = computed(() => {
  const eaten = nutrient('calories')?.totalAmount ?? 0
  const pct = Math.min(eaten / scaledRefs.value.calories.ref, 1)
  return SVG_CIRC * (1 - pct)
})

function buildSegments(codes) {
  const amounts = codes.map(code => nutrient(code)?.totalAmount ?? 0)
  const total = amounts.reduce((s, v) => s + v, 0) || 1
  let cumulative = 0
  return codes.map((code, i) => {
    const dash = (amounts[i] / total) * SVG_CIRC
    const gap = SVG_CIRC - dash
    const offset = SVG_CIRC - cumulative
    cumulative += dash
    return { code, color: NUTRIENT_COLORS[code], dash, gap, offset }
  })
}

function buildIdealSegments(codes) {
  const amounts = codes.map(code => scaledRefs.value[code]?.ref ?? 0)
  const total = amounts.reduce((s, v) => s + v, 0) || 1
  let cumulative = 0
  return codes.map((code, i) => {
    const dash = (amounts[i] / total) * SVG_CIRC
    const gap = SVG_CIRC - dash
    const offset = SVG_CIRC - cumulative
    cumulative += dash
    return { code, color: NUTRIENT_COLORS[code], dash, gap, offset }
  })
}

const macroSegs = computed(() => buildSegments(MACRO_CODES))
const microSegs = computed(() => buildSegments(MICRO_CODES))

const IDEAL_MACRO_SEGS = computed(() => buildIdealSegments(MACRO_CODES))
const IDEAL_MICRO_SEGS = computed(() => buildIdealSegments(MICRO_CODES))

function cap(str) {
  if (!str) return str
  return str.charAt(0).toUpperCase() + str.slice(1)
}

function buildLegend(codes) {
  return codes.map(code => {
    const n = nutrient(code)
    return {
      code,
      name: cap(n?.name ?? code),
      amount: n?.totalAmount ?? 0,
      unit: n?.unit ?? 'g',
      color: NUTRIENT_COLORS[code],
    }
  })
}

const macroLegend = computed(() => buildLegend(MACRO_CODES))
const microLegend = computed(() => buildLegend(MICRO_CODES))

const breakdown = computed(() => {
  const overWatchSet = new Set(OVER_WATCH)
  return nutrients.value.map(n => {
    const ref = scaledRefs.value[n.code]
    const rawPct = ref ? (n.totalAmount / ref.ref) * 100 : null
    const isMaxNutrient = overWatchSet.has(n.code)
    let color = '#aaa'
    if (rawPct != null) {
      if (isMaxNutrient) {
        color = rawPct > 120 ? '#d94f4f'
              : rawPct > 100 ? '#b8860b'
              : rawPct >= 80 ? '#1b4d1b'
              : '#e8a820'
      } else {
        color = rawPct < 50 ? '#d94f4f'
              : rawPct < 80 ? '#e8a820'
              : '#1b4d1b'
      }
    }
    return {
      code: n.code,
      name: cap(n.name),
      amount: n.totalAmount,
      unit: n.unit,
      reference: ref?.label ?? '-',
      pct: rawPct != null ? Math.min(rawPct, 100) : 50,
      color,
    }
  })
})

// Nutrients that warn when over the max reference
const OVER_WATCH = ['calories', 'carbohydrates', 'fat', 'sugar', 'salt']
// Nutrients that warn when under the min reference
const UNDER_WATCH = ['calories', 'protein', 'carbohydrates', 'fibre']

const insights = computed(() => {
  const refs = scaledRefs.value
  const results = []

  for (const code of OVER_WATCH) {
    const n = nutrient(code)
    const ref = refs[code]
    if (!ref || !n) continue
    const pct = (n.totalAmount / ref.ref) * 100
    if (pct > 120) {
      results.push({
        code,
        title: `High ${cap(n.name)}`,
        message: `Your ${n.name} intake is ${Math.round(pct - 100)}% over the recommended limit of ${ref.label}.`,
        pctLabel: `${Math.round(pct)}%`,
        color: '#d94f4f',
        bg: '#fdf2f2',
        priority: 1,
      })
    } else if (pct > 100) {
      results.push({
        code,
        title: `${cap(n.name)} slightly over`,
        message: `Your ${n.name} intake is ${Math.round(pct - 100)}% above the recommended limit of ${ref.label}.`,
        pctLabel: `${Math.round(pct)}%`,
        color: '#e8a820',
        bg: '#fffbf0',
        priority: 2,
      })
    }
  }

  for (const code of UNDER_WATCH) {
    const n = nutrient(code)
    const ref = refs[code]
    if (!ref || !n) continue
    const pct = (n.totalAmount / ref.ref) * 100
    if (pct < 50) {
      results.push({
        code,
        title: `Low ${cap(n.name)}`,
        message: `Your ${n.name} intake is only ${Math.round(pct)}% of the recommended ${ref.label}. Consider eating more ${n.name}-rich foods.`,
        pctLabel: `${Math.round(pct)}%`,
        color: '#d94f4f',
        bg: '#fdf2f2',
        priority: 1,
      })
    } else if (pct < 80) {
      results.push({
        code,
        title: `${cap(n.name)} below target`,
        message: `Your ${n.name} intake is at ${Math.round(pct)}% of the recommended ${ref.label}.`,
        pctLabel: `${Math.round(pct)}%`,
        color: '#e8a820',
        bg: '#fffbf0',
        priority: 2,
      })
    } else if (pct >= 80 && pct <= 100) {
      results.push({
        code,
        title: `Good ${cap(n.name)} intake`,
        message: `Your ${n.name} intake is on track at ${Math.round(pct)}% of the recommended ${ref.label}.`,
        pctLabel: `${Math.round(pct)}%`,
        color: '#1b4d1b',
        bg: '#f0f8f0',
        priority: 3,
      })
    }
  }

  return results.sort((a, b) => a.priority - b.priority)
})

onMounted(load)
</script>
