// Initial template generated by Claude, with wiring up, edits, and function edits done manually with AI guidance
<template>
  <div class="container-fluid px-4 py-4">

    <div class="d-flex justify-content-between align-items-center mb-5">
      <div>
        <h2 class="mb-1" style="color:#1b4d1b;font-weight:600;font-size:1.75rem;">Nutritional Overview</h2>
        <p class="mb-0" style="color:#6b7280;font-size:0.9375rem;">Detailed breakdown of your nutritional intake</p>
      </div>
      <div class="d-flex align-items-center gap-2">
        <div class="d-flex gap-2">
          <button v-for="p in PERIOD_OPTIONS" :key="p.value"
                  class="btn"
                  :style="period === p.value ? 'background:#1b4d1b;color:#fff;border:none;padding:0.5rem 1rem;border-radius:8px;font-size:0.875rem;font-weight:500;' : 'background:#f3f4f6;color:#6b7280;border:none;padding:0.5rem 1rem;border-radius:8px;font-size:0.875rem;font-weight:500;'"
                  @click="period = p.value; load()">
            {{ p.label }}
          </button>
        </div>
        <input type="date" class="form-control" style="width:150px;border-radius:8px;"
               v-model="endDate" @change="load()">
      </div>
    </div>

    <div v-if="loading" class="text-center py-5" style="color:#6b7280;font-size:0.875rem;">Loading…</div>
    <div v-else-if="error" class="alert alert-danger mb-4" style="border-radius:8px;">{{ error }}</div>

    <template v-else>

      <div class="row g-4 mb-4">

        <div class="col-md-4">
          <div class="p-3 text-center h-100 rounded" style="background:#fff;box-shadow:0 1px 3px rgba(0,0,0,0.08);border-radius:12px;border:0.75px solid #1b4d1b;">
            <h6 class="fw-bold mb-3" style="color:#1b4d1b;font-size:0.875rem;">Calories</h6>
            <svg viewBox="0 0 160 160" width="160" height="160" style="margin:0 auto;display:block;">
              <circle cx="80" cy="80" r="62" fill="none" stroke="#f3f4f6" stroke-width="18"/>
              <circle cx="80" cy="80" r="62" fill="none" stroke="#2e7d32" stroke-width="18"
                      stroke-dasharray="389.6"
                      :stroke-dashoffset="calorieOffset"
                      stroke-linecap="round"
                      transform="rotate(-90 80 80)"/>
              <text x="80" y="74" text-anchor="middle" font-size="18" font-weight="bold" fill="#1b4d1b">
                {{ nutrient('calories')?.totalAmount ?? 0 }}
              </text>
              <text x="80" y="90" text-anchor="middle" font-size="10" fill="#6b7280">kcal</text>
            </svg>
            <div class="mt-3 text-start" style="font-size:0.875rem;color:#6b7280;">
              <div>Eaten: <strong style="color:#1b4d1b;">{{ nutrient('calories')?.totalAmount ?? 0 }} kcal</strong></div>
              <div>Reference: <strong style="color:#1b4d1b;">{{ scaledRefs.calories.label }}</strong></div>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="p-3 text-center h-100 rounded" style="position:relative;background:#fff;box-shadow:0 1px 3px rgba(0,0,0,0.08);border-radius:12px;border:0.75px solid #1b4d1b;">
            <h6 class="fw-bold mb-3" style="color:#1b4d1b;font-size:0.875rem;">Macronutrients</h6>
            <div style="position:absolute;top:12px;right:12px;text-align:center;">
              <svg viewBox="0 0 160 160" width="60" height="60" style="display:block;">
                <circle cx="80" cy="80" r="62" fill="none" stroke="#f3f4f6" stroke-width="18"/>
                <template v-for="seg in IDEAL_MACRO_SEGS" :key="seg.code">
                  <circle cx="80" cy="80" r="62" fill="none"
                          :stroke="seg.color" stroke-width="18"
                          :stroke-dasharray="`${seg.dash} ${seg.gap}`"
                          :stroke-dashoffset="seg.offset"
                          transform="rotate(-90 80 80)"/>
                </template>
              </svg>
              <span style="font-size:0.6rem;color:#6b7280;">Ideal</span>
            </div>
            <svg viewBox="0 0 160 160" width="160" height="160" style="margin:0 auto;display:block;">
              <circle cx="80" cy="80" r="62" fill="none" stroke="#f3f4f6" stroke-width="18"/>
              <template v-for="seg in macroSegs" :key="seg.code">
                <circle cx="80" cy="80" r="62" fill="none"
                        :stroke="seg.color" stroke-width="18"
                        :stroke-dasharray="`${seg.dash} ${seg.gap}`"
                        :stroke-dashoffset="seg.offset"
                        transform="rotate(-90 80 80)"/>
              </template>
              <text x="80" y="80" text-anchor="middle" font-size="10" fill="#6b7280">Macros</text>
            </svg>
            <div class="mt-3 text-start" style="font-size:0.875rem;">
              <div v-for="m in macroLegend" :key="m.code" class="d-flex align-items-center gap-2 mb-1">
                <span style="display:inline-block;width:10px;height:10px;border-radius:2px;"
                      :style="`background:${m.color};`"></span>
                <span style="color:#6b7280;">{{ m.name }}:</span>
                <strong style="color:#1b4d1b;">{{ m.amount }} {{ m.unit }}</strong>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="p-3 text-center h-100 rounded" style="position:relative;background:#fff;box-shadow:0 1px 3px rgba(0,0,0,0.08);border-radius:12px;border:0.75px solid #1b4d1b;">
            <h6 class="fw-bold mb-3" style="color:#1b4d1b;font-size:0.875rem;">Micronutrients</h6>
            <div style="position:absolute;top:12px;right:12px;text-align:center;">
              <svg viewBox="0 0 160 160" width="60" height="60" style="display:block;">
                <circle cx="80" cy="80" r="62" fill="none" stroke="#f3f4f6" stroke-width="18"/>
                <template v-for="seg in IDEAL_MICRO_SEGS" :key="seg.code">
                  <circle cx="80" cy="80" r="62" fill="none"
                          :stroke="seg.color" stroke-width="18"
                          :stroke-dasharray="`${seg.dash} ${seg.gap}`"
                          :stroke-dashoffset="seg.offset"
                          transform="rotate(-90 80 80)"/>
                </template>
              </svg>
              <span style="font-size:0.6rem;color:#6b7280;">Ideal</span>
            </div>
            <svg viewBox="0 0 160 160" width="160" height="160" style="margin:0 auto;display:block;">
              <circle cx="80" cy="80" r="62" fill="none" stroke="#f3f4f6" stroke-width="18"/>
              <template v-for="seg in microSegs" :key="seg.code">
                <circle cx="80" cy="80" r="62" fill="none"
                        :stroke="seg.color" stroke-width="18"
                        :stroke-dasharray="`${seg.dash} ${seg.gap}`"
                        :stroke-dashoffset="seg.offset"
                        transform="rotate(-90 80 80)"/>
              </template>
              <text x="80" y="80" text-anchor="middle" font-size="10" fill="#6b7280">Micros</text>
            </svg>
            <div class="mt-3 text-start" style="font-size:0.875rem;">
              <div v-for="m in microLegend" :key="m.code" class="d-flex align-items-center gap-2 mb-1">
                <span style="display:inline-block;width:10px;height:10px;border-radius:2px;"
                      :style="`background:${m.color};`"></span>
                <span style="color:#6b7280;">{{ m.name }}:</span>
                <strong style="color:#1b4d1b;">{{ m.amount }} {{ m.unit }}</strong>
              </div>
            </div>
          </div>
        </div>

      </div>

      <h6 class="fw-bold mb-3" style="color:#1b4d1b;font-size:0.875rem;">Full Nutrient Breakdown</h6>
      <div class="table-responsive mb-4" style="overflow:visible;">
        <table class="table table-sm border" style="border-radius:12px;overflow:visible;">
          <thead style="background:#1b4d1b;color:#fff;">
            <tr>
              <th style="font-size:0.875rem;padding:0.75rem;">Nutrient</th>
              <th style="font-size:0.875rem;padding:0.75rem;">Amount</th>
              <th style="font-size:0.875rem;padding:0.75rem;">Unit</th>
              <th style="font-size:0.875rem;padding:0.75rem;">Reference</th>
              <th style="font-size:0.875rem;padding:0.75rem;">Progress</th>
            </tr>
          </thead>
          <tbody style="overflow:visible;">
            <tr v-if="breakdown.length === 0">
              <td colspan="5" class="text-center py-4" style="color:#6b7280;font-size:0.875rem;">No data for this period. Log meals to see your breakdown.</td>
            </tr>
            <tr v-for="row in breakdown" :key="row.code" style="overflow:visible;">
              <td class="fw-semibold" style="font-size:0.875rem;color:#1b4d1b;padding:0.75rem;position:relative;overflow:visible;">
                <div class="d-flex align-items-center gap-2">
                  <span>{{ row.name }}</span>
                  <div class="nutrient-info-icon" 
                       :data-status="row.status"
                       @mouseenter="showTooltip($event, row)"
                       @mouseleave="hideTooltip">
                    <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
                      <circle cx="8" cy="8" r="7" stroke="currentColor" stroke-width="1.5" fill="none"/>
                      <text x="8" y="11" text-anchor="middle" font-size="10" font-weight="bold" fill="currentColor">i</text>
                    </svg>
                  </div>
                </div>
              </td>
              <td style="font-size:0.875rem;padding:0.75rem;">{{ row.amount }}</td>
              <td style="font-size:0.875rem;color:#6b7280;padding:0.75rem;">{{ row.unit }}</td>
              <td style="font-size:0.875rem;color:#6b7280;padding:0.75rem;">{{ row.reference }}</td>
              <td style="width:120px;padding:0.75rem;">
                <div style="height:8px;background:#f3f4f6;border-radius:6px;overflow:hidden;">
                  <div style="height:100%;border-radius:6px;transition:width 0.4s;" :style="`width:${row.pct}%;background-color:${row.color};`"></div>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <h6 class="fw-bold mb-3" style="color:#1b4d1b;font-size:0.875rem;">Insights</h6>
      <div class="p-3 mb-4 rounded" style="background:#fff;box-shadow:0 1px 3px rgba(0,0,0,0.08);border-radius:12px;border:0.75px solid #1b4d1b;">
        <div v-if="insights.length === 0" style="color:#6b7280;font-size:0.875rem;">
          Your intake looks balanced for this period. Keep it up!
        </div>
        <div v-else class="d-flex flex-column gap-2">
          <div v-for="ins in insights" :key="ins.code"
               class="d-flex align-items-start gap-2 p-2 rounded"
               :style="`background:${ins.bg};`">
            <div>
              <div class="fw-semibold" :style="`color:${ins.color};font-size:0.875rem;`">{{ ins.title }}</div>
              <div style="font-size:0.875rem;color:#6b7280;">{{ ins.message }}</div>
            </div>
            <span class="ms-auto badge rounded-pill align-self-center"
                  :style="`background:${ins.color};font-size:0.7rem;padding:0.25rem 0.625rem;`">
              {{ ins.pctLabel }}
            </span>
          </div>
        </div>
      </div>

      <h6 class="fw-bold mb-3" style="color:#5a9e56;">7-Day Calorie Trend</h6>
      <div class="card border p-3 mb-4">
        <div class="d-flex align-items-end gap-2 justify-content-center px-2"
             style="height:140px;position:relative;">
          <div v-for="bar in weekBars" :key="bar.day"
               class="d-flex flex-column align-items-center gap-1" style="flex:1;max-width:72px;">
            <small :style="`font-size:0.65rem;font-weight:600;color:${bar.over ? '#b8860b' : '#5a9e56'};`">
              {{ bar.val }}
            </small>
            <div style="width:100%;flex:1;display:flex;align-items:flex-end;position:relative;">
              <div style="position:absolute;bottom:0;left:0;right:0;border-radius:4px 4px 0 0;overflow:hidden;"
                   :style="`height:${bar.goalHeight}px;background:#f5d87a;`">
              </div>
              <div v-if="bar.height > 0"
                   style="position:absolute;bottom:0;left:0;right:0;border-radius:4px 4px 0 0;overflow:hidden;"
                   :style="`height:${bar.height}px;`">
                <div :style="`height:${bar.withinHeight}px;background:#5a9e56;`"></div>
                <div v-if="bar.excessHeight > 0" :style="`height:${bar.excessHeight}px;background:#b8860b;`"></div>
              </div>
            </div>
            <small style="font-size:0.65rem;color:#888;">{{ bar.day }}</small>
          </div>
        </div>
        <div class="d-flex gap-3 mt-2">
          <span style="font-size:0.7rem;color:#888;display:flex;align-items:center;gap:4px;">
            <span style="display:inline-block;width:10px;height:10px;border-radius:2px;background:#f5d87a;"></span> Goal ({{ scaledRefs.calories.ref }} kcal)
          </span>
          <span style="font-size:0.7rem;color:#888;display:flex;align-items:center;gap:4px;">
            <span style="display:inline-block;width:10px;height:10px;border-radius:2px;background:#5a9e56;"></span> Within goal
          </span>
          <span style="font-size:0.7rem;color:#888;display:flex;align-items:center;gap:4px;">
            <span style="display:inline-block;width:10px;height:10px;border-radius:2px;background:#b8860b;"></span> Over goal
          </span>
        </div>
        <small class="text-muted mt-1 d-block" style="font-size:0.7rem;">* Today's count is still in progress</small>
      </div>

    </template>

  </div>

  <Teleport to="body">
    <div v-if="activeTooltip" 
         class="nutrient-tooltip" 
         :data-status="activeTooltip.status"
         :style="{
           left: tooltipPosition.x + 'px',
           top: tooltipPosition.y + 'px'
         }">
      <div class="tooltip-header">{{ activeTooltip.name }}</div>
      <div class="tooltip-body">
        <div class="mb-1"><strong>Current:</strong> {{ activeTooltip.amount }} {{ activeTooltip.unit }}</div>
        <div class="mb-2"><strong>Reference:</strong> {{ activeTooltip.reference }}</div>
        <div class="tooltip-insight">{{ activeTooltip.insight }}</div>
      </div>
    </div>
  </Teleport>
</template>

<style scoped>
.table-responsive {
  overflow: visible !important;
}

.nutrient-info-icon {
  position: relative;
  display: inline-flex;
  align-items: center;
  cursor: help;
  transition: all 0.2s;
  z-index: 1;
}

.nutrient-info-icon[data-status="good"] {
  color: #2e7d32;
}

.nutrient-info-icon[data-status="warning"] {
  color: #e8a820;
}

.nutrient-info-icon[data-status="danger"] {
  color: #d94f4f;
}

.nutrient-info-icon[data-status="neutral"] {
  color: #6b7280;
}

.nutrient-info-icon:hover {
  transform: scale(1.1);
  z-index: 1050;
}

.nutrient-tooltip {
  position: fixed;
  background: white;
  border-radius: 8px;
  padding: 0;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
  z-index: 9999;
  width: 280px;
  overflow: hidden;
  pointer-events: none;
}

.tooltip-header {
  padding: 0.75rem;
  font-weight: 600;
  font-size: 0.875rem;
  color: white;
}

.nutrient-tooltip[data-status="good"] .tooltip-header {
  background: #2e7d32;
}

.nutrient-tooltip[data-status="warning"] .tooltip-header {
  background: #e8a820;
}

.nutrient-tooltip[data-status="danger"] .tooltip-header {
  background: #d94f4f;
}

.nutrient-tooltip[data-status="neutral"] .tooltip-header {
  background: #6b7280;
}

.tooltip-body {
  padding: 0.75rem;
  font-size: 0.8125rem;
  color: #1b4d1b;
}

.tooltip-insight {
  margin-top: 0.5rem;
  padding-top: 0.5rem;
  border-top: 1px solid #f3f4f6;
  color: #6b7280;
  font-size: 0.8125rem;
  line-height: 1.4;
}
</style>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { apiFetch } from '../auth.js'

const PERIOD_OPTIONS = [
  { label: 'Today', value: 'daily' },
  { label: 'Week', value: 'weekly' },
  { label: 'Month', value: 'monthly' },
]

const PERIOD_DAYS = { daily: 1, weekly: 7, monthly: 30 }

const FALLBACK_REFS = {
  calories:      { ref: 2000, unit: 'kcal' },
  protein:       { ref: 50,   unit: 'g' },
  carbohydrates: { ref: 260,  unit: 'g' },
  fat:           { ref: 70,   unit: 'g' },
  fibre:         { ref: 30,   unit: 'g' },
  sugar:         { ref: 30,   unit: 'g' },
  salt:          { ref: 6,    unit: 'g' },
}

const todayIso = () => new Date().toISOString().slice(0, 10)

const period = ref('daily')
const endDate = ref(todayIso())
const loading = ref(true)
const error = ref('')
const nutrients = ref([])
const weekBars = ref([])
const goalRefs = ref({})

// Tooltip state
const activeTooltip = ref(null)
const tooltipPosition = ref({ x: 0, y: 0 })

function showTooltip(event, row) {
  const rect = event.currentTarget.getBoundingClientRect()
  const tooltipWidth = 280
  const tooltipHeight = 150 // approximate
  const margin = 12
  
  // Position to the right of the icon
  let x = rect.right + margin
  let y = rect.top + (rect.height / 2)
  
  // Check if tooltip would go off the right edge of the screen
  if (x + tooltipWidth > window.innerWidth) {
    // Position to the left instead
    x = rect.left - tooltipWidth - margin
  }
  
  // Check if tooltip would go off the bottom of the screen
  if (y + tooltipHeight / 2 > window.innerHeight) {
    y = window.innerHeight - tooltipHeight / 2 - 20
  }
  
  // Check if tooltip would go off the top of the screen
  if (y - tooltipHeight / 2 < 20) {
    y = tooltipHeight / 2 + 20
  }
  
  tooltipPosition.value = { x, y: y - tooltipHeight / 2 }
  activeTooltip.value = row
}

function hideTooltip() {
  activeTooltip.value = null
}

function buildGoalRefs(goals) {
  const map = {}
  for (const goal of goals) {
    if (!goal.nutrient?.code || goal.status !== 'active') continue
    const code = goal.nutrient.code
    map[code] = {
      min: goal.targetMin != null ? Number(goal.targetMin) : null,
      max: goal.targetMax != null ? Number(goal.targetMax) : null,
      unit: goal.nutrient.unit,
    }
  }
  return map
}

const scaledRefs = computed(() => {
  const days = PERIOD_DAYS[period.value] ?? 1
  const result = {}
  for (const [code, fallback] of Object.entries(FALLBACK_REFS)) {
    const goal = goalRefs.value[code]
    const isMaxNutrient = OVER_WATCH.includes(code) && !UNDER_WATCH.includes(code)
    const isMinNutrient = UNDER_WATCH.includes(code) && !OVER_WATCH.includes(code)
    // calories and carbs appear in both use max if set, else min
    let baseRef
    if (goal) {
      baseRef = isMaxNutrient ? (goal.max ?? goal.min ?? fallback.ref)
              : isMinNutrient ? (goal.min ?? goal.max ?? fallback.ref)
              : (goal.max ?? goal.min ?? fallback.ref)
    } else {
      baseRef = fallback.ref
    }
    const unit = goal?.unit ?? fallback.unit
    const scaled = baseRef * days
    const isMax = goal ? (goal.max != null && goal.min == null) : (code === 'fat' || code === 'sugar' || code === 'salt')
    const label = `${isMax ? '≤ ' : '≥ '}${scaled % 1 === 0 ? scaled : scaled.toFixed(1)} ${unit}`
    result[code] = { ref: scaled, unit, label }
  }
  return result
})

async function load() {
  loading.value = true
  error.value = ''
  try {
    const params = new URLSearchParams({ period: period.value, endDate: endDate.value })
    const [summaryRes, dashRes, goalsRes] = await Promise.all([
      apiFetch(`/api/diary/summary?${params}`),
      apiFetch('/api/diary/dashboard'),
      apiFetch('/api/goals'),
    ])

    const summaryData = await summaryRes.json().catch(() => ({}))
    if (!summaryRes.ok) {
      error.value = summaryData.error || summaryData.message || 'Failed to load nutrition data'
      return
    }
    nutrients.value = summaryData.summary?.nutrients ?? []

    const goalsData = await goalsRes.json().catch(() => ({}))
    if (goalsRes.ok) {
      goalRefs.value = buildGoalRefs(goalsData.goals ?? [])
    }

    const dashData = await dashRes.json().catch(() => ({}))
    if (dashRes.ok) {
      const trend = dashData.dashboardData?.weeklyCaloryTrend ?? dashData.weeklyCaloryTrend ?? []
      weekBars.value = buildWeekBars(trend)
    }
  } catch {
    error.value = 'Network error - could not load nutrition data'
  } finally {
    loading.value = false
  }
}

const DAY_LABELS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
const MAX_BAR_H = 100

function buildWeekBars(trend) {
  const calorieGoal = goalRefs.value['calories']?.ref ?? FALLBACK_REFS.calories.ref
  if (!trend.length) {
    return DAY_LABELS.map(day => ({ day, val: '-', height: 0, goalHeight: MAX_BAR_H, withinHeight: 0, excessHeight: 0, over: false }))
  }
  const maxCal = Math.max(...trend.map(d => d.calories), calorieGoal)
  const goalHeight = Math.round((calorieGoal / maxCal) * MAX_BAR_H)
  const todayStr = todayIso()
  return trend.map((d, i) => {
    const cal = Math.round(d.calories)
    const over = cal > calorieGoal
    const isToday = d.date === todayStr
    const height = cal > 0 ? Math.max(3, Math.round((cal / maxCal) * MAX_BAR_H)) : 0
    const withinHeight = over ? goalHeight : height
    const excessHeight = over ? height - goalHeight : 0
    return {
      day: isToday ? 'Today' : DAY_LABELS[i] ?? d.date.slice(5),
      val: cal > 0 ? String(cal) : '-',
      height,
      goalHeight,
      withinHeight,
      excessHeight,
      over,
    }
  })
}

const NUTRIENT_COLORS = {
  carbohydrates: '#4e9af1',
  protein:       '#5a9e56',
  fat:           '#e8a820',
  fibre:         '#a86cc1',
  sugar:         '#d94f4f',
  salt:          '#6ec6c2',
}

const MACRO_CODES = ['carbohydrates', 'protein', 'fat']
const MICRO_CODES = ['fibre', 'sugar', 'salt']

const SVG_CIRC = 2 * Math.PI * 62  // ≈ 389.6

function nutrient(code) {
  return nutrients.value.find(n => n.code === code)
}

const calorieOffset = computed(() => {
  const eaten = nutrient('calories')?.totalAmount ?? 0
  const pct = Math.min(eaten / scaledRefs.value.calories.ref, 1)
  return SVG_CIRC * (1 - pct)
})

function buildSegments(codes) {
  const amounts = codes.map(code => nutrient(code)?.totalAmount ?? 0)
  const total = amounts.reduce((s, v) => s + v, 0) || 1
  let cumulative = 0
  return codes.map((code, i) => {
    const dash = (amounts[i] / total) * SVG_CIRC
    const gap = SVG_CIRC - dash
    const offset = SVG_CIRC - cumulative
    cumulative += dash
    return { code, color: NUTRIENT_COLORS[code], dash, gap, offset }
  })
}

function buildIdealSegments(codes) {
  const amounts = codes.map(code => scaledRefs.value[code]?.ref ?? 0)
  const total = amounts.reduce((s, v) => s + v, 0) || 1
  let cumulative = 0
  return codes.map((code, i) => {
    const dash = (amounts[i] / total) * SVG_CIRC
    const gap = SVG_CIRC - dash
    const offset = SVG_CIRC - cumulative
    cumulative += dash
    return { code, color: NUTRIENT_COLORS[code], dash, gap, offset }
  })
}

const macroSegs = computed(() => buildSegments(MACRO_CODES))
const microSegs = computed(() => buildSegments(MICRO_CODES))

const IDEAL_MACRO_SEGS = computed(() => buildIdealSegments(MACRO_CODES))
const IDEAL_MICRO_SEGS = computed(() => buildIdealSegments(MICRO_CODES))

function cap(str) {
  if (!str) return str
  return str.charAt(0).toUpperCase() + str.slice(1)
}

function buildLegend(codes) {
  return codes.map(code => {
    const n = nutrient(code)
    return {
      code,
      name: cap(n?.name ?? code),
      amount: n?.totalAmount ?? 0,
      unit: n?.unit ?? 'g',
      color: NUTRIENT_COLORS[code],
    }
  })
}

const macroLegend = computed(() => buildLegend(MACRO_CODES))
const microLegend = computed(() => buildLegend(MICRO_CODES))

const breakdown = computed(() => {
  const overWatchSet = new Set(OVER_WATCH)
  const underWatchSet = new Set(UNDER_WATCH)
  return nutrients.value.map(n => {
    const ref = scaledRefs.value[n.code]
    const rawPct = ref ? (n.totalAmount / ref.ref) * 100 : null
    const isMaxNutrient = overWatchSet.has(n.code)
    const isMinNutrient = underWatchSet.has(n.code)
    let color = '#aaa'
    let status = 'neutral'
    let insight = 'No reference data available for this nutrient.'
    
    if (rawPct != null) {
      if (isMaxNutrient && !isMinNutrient) {
        // Should stay below reference
        if (rawPct > 120) {
          color = '#d94f4f'
          status = 'danger'
          insight = `⚠️ Your ${n.name} intake is ${Math.round(rawPct - 100)}% over the recommended limit. Consider reducing intake.`
        } else if (rawPct > 100) {
          color = '#e8a820'
          status = 'warning'
          insight = `⚡ Your ${n.name} intake is slightly above the recommended limit (${Math.round(rawPct - 100)}% over).`
        } else if (rawPct >= 80) {
          color = '#2e7d32'
          status = 'good'
          insight = `✓ Your ${n.name} intake is within the healthy range. Keep it up!`
        } else {
          color = '#e8a820'
          status = 'warning'
          insight = `Your ${n.name} intake is quite low at ${Math.round(rawPct)}% of the limit.`
        }
      } else if (isMinNutrient && !isMaxNutrient) {
        // Should reach minimum reference
        if (rawPct < 50) {
          color = '#d94f4f'
          status = 'danger'
          insight = `⚠️ Your ${n.name} intake is very low (${Math.round(rawPct)}% of recommended). Try to increase intake.`
        } else if (rawPct < 80) {
          color = '#e8a820'
          status = 'warning'
          insight = `⚡ Your ${n.name} intake is below the recommended amount (${Math.round(rawPct)}% of target).`
        } else {
          color = '#2e7d32'
          status = 'good'
          insight = `✓ Your ${n.name} intake meets or exceeds the recommended amount. Great job!`
        }
      } else {
        // Both min and max (like calories, carbs)
        if (rawPct > 120) {
          color = '#d94f4f'
          status = 'danger'
          insight = `⚠️ Your ${n.name} intake is significantly over the recommended range.`
        } else if (rawPct > 100) {
          color = '#e8a820'
          status = 'warning'
          insight = `⚡ Your ${n.name} intake is slightly above the recommended range.`
        } else if (rawPct >= 80) {
          color = '#2e7d32'
          status = 'good'
          insight = `✓ Your ${n.name} intake is within the healthy range.`
        } else if (rawPct >= 50) {
          color = '#e8a820'
          status = 'warning'
          insight = `⚡ Your ${n.name} intake is below the recommended range.`
        } else {
          color = '#d94f4f'
          status = 'danger'
          insight = `⚠️ Your ${n.name} intake is very low compared to recommendations.`
        }
      }
    }
    
    return {
      code: n.code,
      name: cap(n.name),
      amount: n.totalAmount,
      unit: n.unit,
      reference: ref?.label ?? '-',
      pct: rawPct != null ? Math.min(rawPct, 100) : 50,
      color,
      status,
      insight,
    }
  })
})

// Nutrients that warn when over the max reference
const OVER_WATCH = ['calories', 'carbohydrates', 'fat', 'sugar', 'salt']
// Nutrients that warn when under the min reference
const UNDER_WATCH = ['calories', 'protein', 'carbohydrates', 'fibre']

const insights = computed(() => {
  const refs = scaledRefs.value
  const results = []

  for (const code of OVER_WATCH) {
    const n = nutrient(code)
    const ref = refs[code]
    if (!ref || !n) continue
    const pct = (n.totalAmount / ref.ref) * 100
    if (pct > 120) {
      results.push({
        code,
        title: `High ${cap(n.name)}`,
        message: `Your ${n.name} intake is ${Math.round(pct - 100)}% over the recommended limit of ${ref.label}.`,
        pctLabel: `${Math.round(pct)}%`,
        color: '#d94f4f',
        bg: '#fdf2f2',
        priority: 1,
      })
    } else if (pct > 100) {
      results.push({
        code,
        title: `${cap(n.name)} slightly over`,
        message: `Your ${n.name} intake is ${Math.round(pct - 100)}% above the recommended limit of ${ref.label}.`,
        pctLabel: `${Math.round(pct)}%`,
        color: '#e8a820',
        bg: '#fffbf0',
        priority: 2,
      })
    }
  }

  for (const code of UNDER_WATCH) {
    const n = nutrient(code)
    const ref = refs[code]
    if (!ref || !n) continue
    const pct = (n.totalAmount / ref.ref) * 100
    if (pct < 50) {
      results.push({
        code,
        title: `Low ${cap(n.name)}`,
        message: `Your ${n.name} intake is only ${Math.round(pct)}% of the recommended ${ref.label}. Consider eating more ${n.name}-rich foods.`,
        pctLabel: `${Math.round(pct)}%`,
        color: '#d94f4f',
        bg: '#fdf2f2',
        priority: 1,
      })
    } else if (pct < 80) {
      results.push({
        code,
        title: `${cap(n.name)} below target`,
        message: `Your ${n.name} intake is at ${Math.round(pct)}% of the recommended ${ref.label}.`,
        pctLabel: `${Math.round(pct)}%`,
        color: '#e8a820',
        bg: '#fffbf0',
        priority: 2,
      })
    } else if (pct >= 80 && pct <= 100) {
      results.push({
        code,
        title: `Good ${cap(n.name)} intake`,
        message: `Your ${n.name} intake is on track at ${Math.round(pct)}% of the recommended ${ref.label}.`,
        pctLabel: `${Math.round(pct)}%`,
        color: '#5a9e56',
        bg: '#f0f8f0',
        priority: 3,
      })
    }
  }

  return results.sort((a, b) => a.priority - b.priority)
})

onMounted(load)
</script>
