// Initial template generated by Claude, with wiring up, edits, and function edits done manually with AI guidance
<template>
  <div class="container-fluid px-4 py-4">

    <div class="d-flex justify-content-between align-items-center mb-5">
      <div>
        <h2 class="mb-1" style="color:#1b4d1b;font-weight:600;font-size:1.75rem;">Professional Dashboard</h2>
        <p class="mb-0" style="color:#6b7280;font-size:0.9375rem;">{{ today }} - manage and review your assigned clients</p>
      </div>
      <div class="d-flex align-items-center gap-2">
        <button class="btn fw-semibold" @click="showInvite = !showInvite"
                style="background:#1b4d1b;color:#ffffff;border:none;padding:0.625rem 1.5rem;border-radius:8px;font-size:0.9375rem;">
          {{ showInvite ? 'Cancel' : 'Invite Client' }}
        </button>
      </div>
    </div>

    <div v-if="showInvite" class="p-4 rounded mb-4"
         style="background:#fffaf5;border:1.25px solid #1b4d1b;border-radius:12px;">
      <h6 class="fw-bold mb-3" style="color:#1b4d1b;font-size:0.9375rem;">Invite a Client</h6>
      <p class="mb-3" style="color:#6b7280;font-size:0.875rem;">
        Enter the client's registered email address to send them an invitation.
      </p>
      <div class="d-flex gap-2 align-items-end">
        <div style="flex:1;max-width:320px;">
          <label class="form-label" style="color:#1b4d1b;font-weight:500;font-size:0.875rem;">Client Email Address</label>
          <input type="email" class="form-control"
                 v-model="inviteEmail" placeholder="client@example.com"
                 style="border:1px solid #d4e7d4;border-radius:8px;padding:0.625rem 1rem;font-size:0.9375rem;">
        </div>
        <button class="btn fw-semibold" @click="sendInvite" :disabled="inviteLoading || !inviteEmail"
                style="background:#1b4d1b;color:#ffffff;border:none;padding:0.625rem 1.5rem;border-radius:8px;font-size:0.9375rem;">
          {{ inviteLoading ? '…' : 'Send Invite' }}
        </button>
      </div>
      <div v-if="inviteError" class="alert alert-danger mt-3 mb-0" style="border-radius:8px;">{{ inviteError }}</div>
      <div v-if="inviteSuccess" class="alert alert-success mt-3 mb-0" style="border-radius:8px;">{{ inviteSuccess }}</div>
    </div>

    <div v-if="pendingInvitations.length > 0" class="mb-4">
      <h6 class="fw-bold mb-3" style="color:#1b4d1b;font-size:1.125rem;">
        Pending Invitations
        <span class="badge ms-2" style="background:#fbbf24;color:#fff;font-size:0.8125rem;padding:0.375rem 0.75rem;border-radius:6px;">{{ pendingInvitations.length }}</span>
      </h6>
      <div v-for="inv in pendingInvitations" :key="inv.id"
           class="p-4 rounded mb-3 d-flex flex-row align-items-center justify-content-between gap-3"
           style="background:#fff;box-shadow:0 1px 3px rgba(0,0,0,0.08);border:1.25px solid #1b4d1b;border-radius:12px;">
        <div class="d-flex align-items-center gap-3 flex-grow-1">
          <div class="avatar-circle" style="width:48px;height:48px;font-size:1rem;">
            {{ initialsFor(inv.subscriber.fullName) }}
          </div>
          <div>
            <div class="fw-bold mb-1" style="color:#1b4d1b;font-size:0.9375rem;">{{ inv.subscriber.fullName }}</div>
            <div style="color:#6b7280;font-size:0.8125rem;">
              {{ inv.subscriber.email }} · ID {{ inv.subscriberId }}
            </div>
            <div style="color:#9ca3af;font-size:0.8125rem;">
              Invited {{ formatDate(inv.assignedAt) }} · awaiting response
            </div>
          </div>
        </div>
        <span class="badge" style="background:#fbbf24;color:#fff;font-size:0.8125rem;padding:0.375rem 0.75rem;border-radius:6px;">Pending</span>
      </div>
    </div>

    <div class="d-flex justify-content-between align-items-center mb-4">
      <h5 class="fw-bold mb-0" style="color:#1b4d1b;font-size:1.125rem;">Your Clients</h5>
      <span class="badge" style="background:#2e7d32;color:#fff;font-size:0.8125rem;padding:0.375rem 0.75rem;border-radius:6px;">
        {{ clients.length }} active
      </span>
    </div>

    <div v-if="loading" class="text-center py-5" style="color:#9ca3af;">
      <small>Loading clients…</small>
    </div>

    <div v-else-if="error" class="alert alert-danger" style="border-radius:8px;">{{ error }}</div>

    <div v-else-if="clients.length === 0"
         class="text-center py-5 rounded"
         style="background:#f9fafb;border:2px dashed #e5e7eb;">
      <p class="mb-2" style="color:#6b7280;font-size:0.9375rem;">No active clients yet.</p>
      <small style="color:#9ca3af;">Invite a subscriber using their email - they'll appear here once they accept.</small>
    </div>

    <div v-else>
      <div v-for="client in clients" :key="client.id" class="mb-4 rounded"
           style="background:#fff;box-shadow:0 1px 3px rgba(0,0,0,0.08);border:1.25px solid #1b4d1b;border-radius:12px;overflow:hidden;">

        <div class="d-flex justify-content-between align-items-center p-4"
             style="cursor:pointer;border-bottom:1px solid #f3f4f6;"
             @click="toggleClient(client)">
          <div class="d-flex align-items-center gap-3">
            <div class="avatar-circle" style="width:48px;height:48px;font-size:1rem;">
              {{ initialsFor(client.subscriber.fullName) }}
            </div>
            <div>
              <div class="fw-bold mb-1" style="color:#1b4d1b;font-size:0.9375rem;">{{ client.subscriber.fullName }}</div>
              <div style="color:#6b7280;font-size:0.8125rem;">
                {{ client.subscriber.email }} · ID {{ client.subscriberId }}
              </div>
            </div>
          </div>
          <div class="d-flex align-items-center gap-2">
            <button class="btn btn-sm"
                    style="background:#fecaca;border:none;color:#991b1b;padding:0.375rem 0.75rem;border-radius:6px;font-size:0.8125rem;font-weight:500;"
                    title="Remove client"
                    @click.stop="removeClient(client)">Remove</button>
            <span style="color:#1b4d1b;font-weight:bold;font-size:1.125rem;">
              {{ expandedId === client.id ? '▲' : '▼' }}
            </span>
          </div>
        </div>

        <div v-if="expandedId === client.id" class="p-4">

          <div class="d-flex gap-2 mb-4 pb-3" style="border-bottom:1px solid #f3f4f6;">
            <button v-for="tab in tabs" :key="tab.id"
                    class="btn"
                    :style="activeTab[client.id] === tab.id ? 'background:#1b4d1b;color:#fff;border:none;padding:0.5rem 1rem;border-radius:8px;font-size:0.875rem;font-weight:500;' : 'background:#f3f4f6;color:#6b7280;border:none;padding:0.5rem 1rem;border-radius:8px;font-size:0.875rem;font-weight:500;'"
                    @click="setTab(client, tab.id)">
              {{ tab.label }}
            </button>
          </div>

          <div v-if="activeTab[client.id] === 'dashboard'">
            <div v-if="client.dashboard.loading" class="text-center py-3" style="color:#9ca3af;"><small>Loading…</small></div>
            <div v-else-if="client.dashboard.error" class="alert alert-danger mb-0" style="border-radius:8px;">
              {{ client.dashboard.error }}
            </div>
            <div v-else-if="client.dashboard.data">
              <div class="row g-3 mb-4">
                <div class="col-4">
                  <div class="p-3 rounded text-center" style="background:#f9fafb;">
                    <div class="fw-bold mb-1" style="color:#1b4d1b;font-size:1.25rem;">
                      {{ client.dashboard.data.quickStats?.calories_today ?? 0 }}
                    </div>
                    <div style="color:#6b7280;font-size:0.8125rem;">kcal today</div>
                  </div>
                </div>
                <div class="col-4">
                  <div class="p-3 rounded text-center" style="background:#f9fafb;">
                    <div class="fw-bold mb-1" style="color:#1b4d1b;font-size:1.25rem;">
                      {{ client.dashboard.data.quickStats?.meals_logged_today ?? 0 }}
                    </div>
                    <div style="color:#6b7280;font-size:0.8125rem;">meals today</div>
                  </div>
                </div>
                <div class="col-4">
                  <div class="p-3 rounded text-center" style="background:#f9fafb;">
                    <div class="fw-bold mb-1" style="color:#1b4d1b;font-size:1.25rem;">
                      {{ client.dashboard.data.quickStats?.days_logged ?? 0 }}
                    </div>
                    <div style="color:#6b7280;font-size:0.8125rem;">days logged</div>
                  </div>
                </div>
              </div>

              <div class="row g-4">
                <div class="col-md-6">
                  <h6 class="fw-bold mb-3" style="color:#1b4d1b;font-size:0.9375rem;">Today's Diary</h6>
                  <div v-if="recentEntries(client.dashboard.data).length === 0"
                       style="color:#9ca3af;font-size:0.875rem;">No entries logged today.</div>
                  <ul v-else class="list-unstyled mb-0">
                    <li v-for="entry in recentEntries(client.dashboard.data)" :key="entry.diaryEntryId"
                        class="mb-2 pb-2" style="border-bottom:1px solid #f3f4f6;">
                      <span class="fw-semibold text-capitalize" style="color:#1b4d1b;font-size:0.875rem;">{{ entry.mealType }}</span>
                      <span class="ms-1" style="color:#6b7280;font-size:0.8125rem;">- {{ formatDate(entry.consumedAt) }}</span>
                      <span v-if="entry.items?.length" class="ms-1"
                            style="color:#9ca3af;font-size:0.8125rem;">({{ entry.items.length }} item{{ entry.items.length !== 1 ? 's' : '' }})</span>
                    </li>
                  </ul>
                </div>

                <div class="col-md-6">
                  <h6 class="fw-bold mb-3" style="color:#1b4d1b;font-size:0.9375rem;">Today's Nutrition</h6>
                  <div v-if="!(client.dashboard.data.nutritionPreview?.length)"
                       style="color:#9ca3af;font-size:0.875rem;">No nutrition data yet.</div>
                  <ul v-else class="list-unstyled mb-0">
                    <li v-for="n in client.dashboard.data.nutritionPreview" :key="n.code"
                        class="mb-2 pb-2 d-flex justify-content-between" style="border-bottom:1px solid #f3f4f6;">
                      <span class="fw-semibold" style="color:#1b4d1b;font-size:0.875rem;">{{ n.name }}</span>
                      <span style="color:#6b7280;font-size:0.875rem;">{{ n.totalAmount }} {{ n.unit }}</span>
                    </li>
                  </ul>
                </div>

                <div class="col-12" v-if="riskSnapshots(client.dashboard.data).length">
                  <h6 class="fw-bold mb-3" style="color:#1b4d1b;font-size:0.9375rem;">Recent Risk Flags</h6>
                  <ul class="list-unstyled mb-0">
                    <li v-for="snap in riskSnapshots(client.dashboard.data)" :key="snap.snapshotId"
                        class="mb-2 pb-2" style="border-bottom:1px solid #f3f4f6;">
                      <span class="badge me-2"
                            :style="`background:${severityColor(snap.riskLevel)};color:#fff;font-size:0.8125rem;padding:0.25rem 0.5rem;border-radius:4px;`">
                        {{ snap.riskLevel }}
                      </span>
                      <span class="fw-semibold" style="color:#1b4d1b;font-size:0.875rem;">{{ snap.rule?.name ?? 'Rule' }}</span>
                      <span class="ms-1" style="color:#6b7280;font-size:0.875rem;" v-if="snap.reason">- {{ snap.reason }}</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <div v-if="activeTab[client.id] === 'summary'">
            <div class="d-flex gap-2 align-items-end mb-4">
              <div>
                <label class="form-label" style="color:#1b4d1b;font-weight:500;font-size:0.875rem;">Period</label>
                <select class="form-select" v-model="client.summary.period"
                        style="border:1px solid #d4e7d4;border-radius:8px;padding:0.5rem 0.75rem;font-size:0.875rem;">
                  <option value="daily">Daily</option>
                  <option value="weekly">Weekly</option>
                  <option value="monthly">Monthly</option>
                </select>
              </div>
              <div>
                <label class="form-label" style="color:#1b4d1b;font-weight:500;font-size:0.875rem;">End Date</label>
                <input type="date" class="form-control"
                       v-model="client.summary.endDate"
                       style="border:1px solid #d4e7d4;border-radius:8px;padding:0.5rem 0.75rem;font-size:0.875rem;">
              </div>
              <button class="btn fw-semibold" @click="loadSummary(client)"
                      :disabled="client.summary.loading"
                      style="background:#1b4d1b;color:#ffffff;border:none;padding:0.5rem 1.25rem;border-radius:8px;font-size:0.875rem;">
                {{ client.summary.loading ? '…' : 'Load' }}
              </button>
            </div>

            <div v-if="client.summary.loading" class="text-center py-3" style="color:#9ca3af;"><small>Loading…</small></div>
            <div v-else-if="client.summary.error" class="alert alert-danger" style="border-radius:8px;">{{ client.summary.error }}</div>
            <div v-else-if="client.summary.data">
              <div class="row g-4 mb-4">

                <div class="col-md-4">
                  <div class="p-4 text-center h-100 rounded" style="background:#f9fafb;">
                    <h6 class="fw-bold mb-3" style="color:#1b4d1b;font-size:0.9375rem;">Calories</h6>
                    <svg viewBox="0 0 160 160" width="140" height="140" style="margin:0 auto;display:block;">
                      <circle cx="80" cy="80" r="62" fill="none" stroke="#e9ecef" stroke-width="18"/>
                      <circle cx="80" cy="80" r="62" fill="none" stroke="#2e7d32" stroke-width="18"
                              stroke-dasharray="389.6"
                              :stroke-dashoffset="calorieOffset(client.summary.data)"
                              stroke-linecap="round"
                              transform="rotate(-90 80 80)"/>
                      <text x="80" y="74" text-anchor="middle" font-size="18" font-weight="bold" fill="#1b4d1b">
                        {{ summaryNutrient(client.summary.data, 'calories')?.totalAmount ?? 0 }}
                      </text>
                      <text x="80" y="90" text-anchor="middle" font-size="10" fill="#6b7280">kcal</text>
                    </svg>
                    <div class="mt-3 text-start" style="font-size:0.875rem;color:#6b7280;">
                      <div>Eaten: <strong style="color:#1b4d1b;">{{ summaryNutrient(client.summary.data, 'calories')?.totalAmount ?? 0 }} kcal</strong></div>
                      <div>Reference: <strong style="color:#1b4d1b;">{{ scaledRefsFor(client).calories.label }}</strong></div>
                    </div>
                  </div>
                </div>

                <div class="col-md-4">
                  <div class="p-4 text-center h-100 rounded" style="background:#f9fafb;position:relative;">
                    <h6 class="fw-bold mb-3" style="color:#1b4d1b;font-size:0.9375rem;">Macronutrients</h6>
                    <div style="position:absolute;top:12px;right:12px;text-align:center;">
                      <svg viewBox="0 0 160 160" width="60" height="60" style="display:block;">
                        <circle cx="80" cy="80" r="62" fill="none" stroke="#e9ecef" stroke-width="18"/>
                        <template v-for="seg in IDEAL_MACRO_SEGS" :key="seg.code">
                          <circle cx="80" cy="80" r="62" fill="none"
                                  :stroke="seg.color" stroke-width="18"
                                  :stroke-dasharray="`${seg.dash} ${seg.gap}`"
                                  :stroke-dashoffset="seg.offset"
                                  transform="rotate(-90 80 80)"/>
                        </template>
                      </svg>
                      <span style="font-size:0.7rem;color:#9ca3af;">Ideal</span>
                    </div>
                    <svg viewBox="0 0 160 160" width="140" height="140" style="margin:0 auto;display:block;">
                      <circle cx="80" cy="80" r="62" fill="none" stroke="#e9ecef" stroke-width="18"/>
                      <template v-for="seg in macroSegments(client.summary.data)" :key="seg.code">
                        <circle cx="80" cy="80" r="62" fill="none"
                                :stroke="seg.color" stroke-width="18"
                                :stroke-dasharray="`${seg.dash} ${seg.gap}`"
                                :stroke-dashoffset="seg.offset"
                                transform="rotate(-90 80 80)"/>
                      </template>
                      <text x="80" y="80" text-anchor="middle" font-size="10" fill="#6b7280">Macros</text>
                    </svg>
                    <div class="mt-3 text-start" style="font-size:0.875rem;">
                      <div v-for="m in donutLegend(client.summary.data, MACRO_CODES)" :key="m.code"
                           class="d-flex align-items-center gap-2 mb-2">
                        <span style="display:inline-block;width:12px;height:12px;border-radius:3px;"
                              :style="`background:${m.color};`"></span>
                        <span style="color:#6b7280;">{{ m.name }}:</span>
                        <strong style="color:#1b4d1b;">{{ m.amount }} {{ m.unit }}</strong>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="col-md-4">
                  <div class="p-4 text-center h-100 rounded" style="background:#f9fafb;position:relative;">
                    <h6 class="fw-bold mb-3" style="color:#1b4d1b;font-size:0.9375rem;">Micronutrients</h6>
                    <div style="position:absolute;top:12px;right:12px;text-align:center;">
                      <svg viewBox="0 0 160 160" width="60" height="60" style="display:block;">
                        <circle cx="80" cy="80" r="62" fill="none" stroke="#e9ecef" stroke-width="18"/>
                        <template v-for="seg in IDEAL_MICRO_SEGS" :key="seg.code">
                          <circle cx="80" cy="80" r="62" fill="none"
                                  :stroke="seg.color" stroke-width="18"
                                  :stroke-dasharray="`${seg.dash} ${seg.gap}`"
                                  :stroke-dashoffset="seg.offset"
                                  transform="rotate(-90 80 80)"/>
                        </template>
                      </svg>
                      <span style="font-size:0.7rem;color:#9ca3af;">Ideal</span>
                    </div>
                    <svg viewBox="0 0 160 160" width="140" height="140" style="margin:0 auto;display:block;">
                      <circle cx="80" cy="80" r="62" fill="none" stroke="#e9ecef" stroke-width="18"/>
                      <template v-for="seg in microSegments(client.summary.data)" :key="seg.code">
                        <circle cx="80" cy="80" r="62" fill="none"
                                :stroke="seg.color" stroke-width="18"
                                :stroke-dasharray="`${seg.dash} ${seg.gap}`"
                                :stroke-dashoffset="seg.offset"
                                transform="rotate(-90 80 80)"/>
                      </template>
                      <text x="80" y="80" text-anchor="middle" font-size="10" fill="#6b7280">Micros</text>
                    </svg>
                    <div class="mt-3 text-start" style="font-size:0.875rem;">
                      <div v-for="m in donutLegend(client.summary.data, MICRO_CODES)" :key="m.code"
                           class="d-flex align-items-center gap-2 mb-2">
                        <span style="display:inline-block;width:12px;height:12px;border-radius:3px;"
                              :style="`background:${m.color};`"></span>
                        <span style="color:#6b7280;">{{ m.name }}:</span>
                        <strong style="color:#1b4d1b;">{{ m.amount }} {{ m.unit }}</strong>
                      </div>
                    </div>
                  </div>
                </div>

              </div>

              <h6 class="fw-bold mb-3" style="color:#1b4d1b;font-size:1rem;">Full Nutrient Breakdown</h6>
              <div class="table-responsive">
                <table class="table table-sm mb-0" style="border:1px solid #e5e7eb;border-radius:8px;overflow:hidden;">
                  <thead style="background:#1b4d1b;color:#fff;">
                    <tr>
                      <th style="font-size:0.875rem;padding:0.75rem;">Nutrient</th>
                      <th style="font-size:0.875rem;padding:0.75rem;">Amount</th>
                      <th style="font-size:0.875rem;padding:0.75rem;">Unit</th>
                      <th style="font-size:0.875rem;padding:0.75rem;">Reference</th>
                      <th style="font-size:0.875rem;padding:0.75rem;">Progress</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="row in summaryBreakdown(client)" :key="row.code">
                      <td style="font-size:0.875rem;font-weight:600;color:#1b4d1b;padding:0.75rem;">{{ row.name }}</td>
                      <td style="font-size:0.875rem;padding:0.75rem;">{{ row.amount }}</td>
                      <td style="font-size:0.875rem;color:#6b7280;padding:0.75rem;">{{ row.unit }}</td>
                      <td style="font-size:0.875rem;color:#6b7280;padding:0.75rem;">{{ row.reference }}</td>
                      <td style="width:140px;padding:0.75rem;">
                        <div class="progress" style="height:10px;background:#f3f4f6;border-radius:6px;">
                          <div class="progress-bar"
                               :style="`width:${row.pct}%;background-color:${row.color};border-radius:6px;`"></div>
                        </div>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div v-else style="color:#9ca3af;font-size:0.875rem;">Select a period and end date, then press Load.</div>
          </div>

          <div v-if="activeTab[client.id] === 'goals'">
            <div v-if="client.goals.loading" class="text-center py-3" style="color:#9ca3af;"><small>Loading…</small></div>
            <div v-else-if="client.goals.error" class="alert alert-danger" style="border-radius:8px;">{{ client.goals.error }}</div>
            <div v-else>
              <div v-if="(client.goals.data ?? []).length === 0"
                   style="color:#9ca3af;font-size:0.875rem;" class="mb-4">No goals set.</div>
              <ul v-else class="list-unstyled mb-4">
                <li v-for="goal in client.goals.data" :key="goal.goalId"
                    class="mb-3 pb-3 d-flex justify-content-between align-items-center" style="border-bottom:1px solid #f3f4f6;">
                  <div>
                    <span class="fw-semibold" style="color:#1b4d1b;font-size:0.9375rem;">{{ goal.nutrient?.name ?? goal.notes ?? 'Custom goal' }}</span>
                    <span class="ms-2" style="color:#6b7280;font-size:0.875rem;">{{ goalRange(goal) }}</span>
                    <span class="badge ms-2"
                          :style="`background:${goalSourceColor(goal.source)};color:#fff;font-size:0.8125rem;padding:0.25rem 0.5rem;border-radius:4px;`">
                      {{ goalSourceLabel(goal.source) }}
                    </span>
                    <div v-if="goal.notes && goal.nutrient" style="color:#9ca3af;font-size:0.8125rem;margin-top:0.25rem;">
                      {{ goal.notes }}
                    </div>
                  </div>
                  <span style="color:#9ca3af;font-size:0.8125rem;">{{ goalRangeDates(goal) }}</span>
                </li>
              </ul>

              <div class="p-4 rounded" style="background:#fffaf5;border:1.25px solid #1b4d1b;border-radius:12px;">
                <h6 class="fw-bold mb-3" style="color:#1b4d1b;font-size:0.9375rem;">Set a Goal</h6>

                <div class="d-flex flex-wrap gap-2 mb-4">
                  <button v-for="preset in goalPresets" :key="preset.title"
                          class="btn btn-sm"
                          style="background:#f3f4f6;color:#1b4d1b;border:none;padding:0.5rem 1rem;border-radius:6px;font-size:0.8125rem;font-weight:500;"
                          @click="applyGoalPreset(client, preset)">
                    {{ preset.title }}
                  </button>
                </div>

                <div class="row g-3 mb-3">
                  <div class="col-md-4">
                    <label class="form-label" style="color:#1b4d1b;font-weight:500;font-size:0.875rem;">Tracked Nutrient</label>
                    <select class="form-select" v-model="client.goalDraft.nutrientId"
                            style="border:1px solid #d4e7d4;border-radius:8px;padding:0.5rem 0.75rem;font-size:0.875rem;">
                      <option :value="null">No specific nutrient</option>
                      <option v-for="n in nutrients" :key="n.nutrientId" :value="n.nutrientId">
                        {{ n.name }} ({{ n.unit }})
                      </option>
                    </select>
                  </div>
                  <div class="col-md-4">
                    <label class="form-label" style="color:#1b4d1b;font-weight:500;font-size:0.875rem;">
                      Target Min{{ nutrientUnitFor(client.goalDraft.nutrientId) ? ` (${nutrientUnitFor(client.goalDraft.nutrientId)})` : '' }}
                    </label>
                    <input type="number" class="form-control" step="any" min="0"
                           v-model.number="client.goalDraft.targetMin"
                           :disabled="!client.goalDraft.nutrientId"
                           style="border:1px solid #d4e7d4;border-radius:8px;padding:0.5rem 0.75rem;font-size:0.875rem;">
                  </div>
                  <div class="col-md-4">
                    <label class="form-label" style="color:#1b4d1b;font-weight:500;font-size:0.875rem;">
                      Target Max{{ nutrientUnitFor(client.goalDraft.nutrientId) ? ` (${nutrientUnitFor(client.goalDraft.nutrientId)})` : '' }}
                    </label>
                    <input type="number" class="form-control" step="any" min="0"
                           v-model.number="client.goalDraft.targetMax"
                           :disabled="!client.goalDraft.nutrientId"
                           style="border:1px solid #d4e7d4;border-radius:8px;padding:0.5rem 0.75rem;font-size:0.875rem;">
                  </div>
                </div>
                <div class="row g-3 mb-3">
                  <div class="col-md-3">
                    <label class="form-label" style="color:#1b4d1b;font-weight:500;font-size:0.875rem;">Start Date</label>
                    <input type="date" class="form-control"
                           v-model="client.goalDraft.startDate"
                           style="border:1px solid #d4e7d4;border-radius:8px;padding:0.5rem 0.75rem;font-size:0.875rem;">
                  </div>
                  <div class="col-md-3">
                    <label class="form-label" style="color:#1b4d1b;font-weight:500;font-size:0.875rem;">End Date</label>
                    <input type="date" class="form-control"
                           v-model="client.goalDraft.endDate"
                           style="border:1px solid #d4e7d4;border-radius:8px;padding:0.5rem 0.75rem;font-size:0.875rem;">
                  </div>
                  <div class="col-md-6">
                    <label class="form-label" style="color:#1b4d1b;font-weight:500;font-size:0.875rem;">Notes (required)</label>
                    <input type="text" class="form-control"
                           v-model="client.goalDraft.notes" placeholder="Why are you setting this goal?"
                           style="border:1px solid #d4e7d4;border-radius:8px;padding:0.5rem 0.75rem;font-size:0.875rem;">
                  </div>
                </div>
                <div v-if="replacesGoalWarningFor(client)" class="alert mt-3 mb-0"
                     style="background:#fffbf0;border:1px solid #fbbf24;color:#92400e;border-radius:8px;padding:0.75rem 1rem;font-size:0.875rem;">
                  This will replace the client's existing active {{ replacesGoalWarningFor(client) }} goal.
                </div>
                <button class="btn fw-semibold mt-3" @click="setGoal(client)"
                        :disabled="client.goalDraft.saving"
                        style="background:#1b4d1b;color:#ffffff;border:none;padding:0.625rem 1.5rem;border-radius:8px;font-size:0.875rem;">
                  {{ client.goalDraft.saving ? '…' : 'Save Goal' }}
                </button>
                <div v-if="client.goalDraft.error" class="alert alert-danger mt-3 mb-0" style="border-radius:8px;">
                  {{ client.goalDraft.error }}
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>

  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { apiFetch } from '../auth.js'

const today = new Date().toLocaleDateString('en-GB', {
  weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
})

const tabs = [
  { id: 'dashboard', label: 'Dashboard' },
  { id: 'summary', label: 'Summary' },
  { id: 'goals', label: 'Goals' },
]

const clients = ref([])
const loading = ref(true)
const error = ref('')
const expandedId = ref(null)
const activeTab = reactive({})

const showInvite = ref(false)
const inviteId = ref(null)
const inviteLoading = ref(false)
const inviteError = ref('')
const inviteSuccess = ref('')

const todayIso = () => new Date().toISOString().slice(0, 10)

function blankClientState() {
  return {
    dashboard: { loading: false, error: '', data: null },
    summary: { loading: false, error: '', data: null, period: 'daily', endDate: todayIso() },
    goals: { loading: false, error: '', data: null },
    goalDraft: {
      nutrientId: null, targetMin: null, targetMax: null,
      startDate: todayIso(), endDate: '', notes: '',
      saving: false, error: '',
    },
  }
}

onMounted(loadClients)

async function fetchJson(url, options) {
  const res = await apiFetch(url, options)
  const data = await res.json().catch(() => ({}))
  return { ok: res.ok, data, message: data.error || data.message }
}

async function loadResource(state, url, pickData, fallback = 'Failed to load') {
  state.loading = true
  state.error = ''
  try {
    const { ok, data, message } = await fetchJson(url)
    if (!ok) {
      state.error = message || fallback
      return
    }
    state.data = pickData(data)
  } catch {
    state.error = 'Network error'
  } finally {
    state.loading = false
  }
}

async function loadClients() {
  loading.value = true
  error.value = ''
  try {
    const url = '/api/professional/clients'
    const { ok, data, message } = await fetchJson(url)
    if (!ok) {
      error.value = message || 'Failed to load clients'
      return
    }
    clients.value = (data.clients ?? []).map(c => ({ ...c, ...blankClientState() }))
  } catch {
    error.value = 'Network error - could not load clients'
  } finally {
    loading.value = false
  }
}

async function sendInvite() {
  inviteError.value = ''
  inviteSuccess.value = ''
  inviteLoading.value = true
  try {
    const { ok, message } = await fetchJson('/api/professional/client-invitations', {
      method: 'POST',
      body: JSON.stringify({ subscriberId: Number(inviteId.value) }),
    })
    if (!ok) {
      inviteError.value = message || 'Invitation failed'
      return
    }
    inviteSuccess.value = `Invitation sent to user #${inviteId.value}.`
    inviteId.value = null
  } catch {
    inviteError.value = 'Network error - could not send invitation'
  } finally {
    inviteLoading.value = false
  }
}

async function removeClient(client) {
  if (!confirm(`Remove ${client.subscriber.fullName} from your clients?`)) return
  try {
    const { ok, message } = await fetchJson(`/api/professional/clients/${client.subscriberId}`, {
      method: 'DELETE',
    })
    if (!ok) {
      alert(message || 'Removal failed')
      return
    }
    clients.value = clients.value.filter(c => c.id !== client.id)
    if (expandedId.value === client.id) expandedId.value = null
  } catch {
    alert('Network error - could not remove client')
  }
}

function toggleClient(client) {
  if (expandedId.value === client.id) {
    expandedId.value = null
    return
  }
  expandedId.value = client.id
  if (!activeTab[client.id]) activeTab[client.id] = 'dashboard'
  loadTab(client, activeTab[client.id])
}

function setTab(client, tabId) {
  activeTab[client.id] = tabId
  loadTab(client, tabId)
}

function loadTab(client, tabId) {
  if (tabId === 'dashboard' && !client.dashboard.data && !client.dashboard.loading) {
    loadDashboard(client)
  } else if (tabId === 'goals' && !client.goals.data && !client.goals.loading) {
    loadGoals(client)
  }
}

function loadDashboard(client) {
  return loadResource(
    client.dashboard,
    `/api/professional/clients/${client.subscriberId}/dashboard`,
    d => d.dashboardData ?? d,
    'Failed to load dashboard',
  )
}

async function loadSummary(client) {
  client.summary.data = null
  const params = new URLSearchParams({
    period: client.summary.period,
    endDate: client.summary.endDate,
  })
  await loadResource(
    client.summary,
    `/api/professional/clients/${client.subscriberId}/summary?${params}`,
    d => d.summary ?? d,
    'Failed to load summary',
  )
}

function loadGoals(client) {
  return loadResource(
    client.goals,
    `/api/professional/clients/${client.subscriberId}/goals`,
    d => d.goals ?? d,
    'Failed to load goals',
  )
}

async function setGoal(client) {
  client.goalDraft.error = ''
  client.goalDraft.saving = true
  try {
    const goal = {}
    if (client.goalDraft.nutrientId != null) goal.nutrientId = client.goalDraft.nutrientId
    if (client.goalDraft.targetMin != null) goal.targetMin = client.goalDraft.targetMin
    if (client.goalDraft.targetMax != null) goal.targetMax = client.goalDraft.targetMax
    if (client.goalDraft.startDate) goal.startDate = client.goalDraft.startDate
    if (client.goalDraft.endDate) goal.endDate = client.goalDraft.endDate
    goal.notes = client.goalDraft.notes

    const { ok, message } = await fetchJson(
      `/api/professional/clients/${client.subscriberId}/goals`,
      { method: 'POST', body: JSON.stringify({ goal }) },
    )
    if (!ok) {
      client.goalDraft.error = message || 'Failed to set goal'
      return
    }
    client.goalDraft = {
      nutrientId: null, targetMin: null, targetMax: null,
      startDate: todayIso(), endDate: '', notes: '',
      saving: false, error: '',
    }
    client.goals.data = null
    await loadGoals(client)
  } catch {
    client.goalDraft.error = 'Network error'
  } finally {
    client.goalDraft.saving = false
  }
}

function initialsFor(name) {
  if (!name) return '?'
  return name.trim().split(/\s+/).slice(0, 2).map(p => p[0].toUpperCase()).join('') || '?'
}

function formatDate(value) {
  if (!value) return ''
  const d = new Date(value)
  if (Number.isNaN(d.getTime())) return ''
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
}

function recentEntries(data) {
  const entries = data?.foodDiaryPreview ?? data?.recentDiaryEntries ?? data?.diaryEntries ?? data?.entries ?? []
  return entries.filter(e => e.items?.length > 0)
}

function riskSnapshots(data) {
  return data?.riskSnapshots ?? data?.recentRisks ?? []
}

function goalRange(goal) {
  const min = goal.targetMin
  const max = goal.targetMax
  const unit = goal.nutrient?.unit ? ` ${goal.nutrient.unit}` : ''
  if (min != null && max != null) return `${min}–${max}${unit}`
  if (min != null) return `≥ ${min}${unit}`
  if (max != null) return `≤ ${max}${unit}`
  return ''
}

function goalSourceColor(source) {
  if (source === 'professional_defined') return '#5a9e56'
  if (source === 'user_defined') return '#3a7fbf'
  return '#888'
}

// NHS reference intakes used for progress bars
const REFERENCES = {
  calories:      { ref: 2000, unit: 'kcal', label: '2,000 kcal' },
  protein:       { ref: 50,   unit: 'g',    label: '50 g' },
  carbohydrates: { ref: 260,  unit: 'g',    label: '260 g' },
  fat:           { ref: 70,   unit: 'g',    label: '70 g' },
  fibre:         { ref: 30,   unit: 'g',    label: '30 g' },
  sugar:         { ref: 30,   unit: 'g',    label: '≤ 30 g' },
  salt:          { ref: 6,    unit: 'g',    label: '≤ 6 g' },
}

const MACRO_CODES = ['carbohydrates', 'protein', 'fat']
const MICRO_CODES = ['fibre', 'sugar', 'salt']

const NUTRIENT_COLORS = {
  carbohydrates: '#4e9af1',
  protein:       '#5a9e56',
  fat:           '#e8a820',
  fibre:         '#a86cc1',
  sugar:         '#d94f4f',
  salt:          '#6ec6c2',
}

function summaryNutrient(data, code) {
  return data?.nutrients?.find(n => n.code === code)
}

const SVG_CIRC = 2 * Math.PI * 62  // ≈ 389.6

function calorieOffset(data) {
  const eaten = summaryNutrient(data, 'calories')?.totalAmount ?? 0
  const pct = Math.min(eaten / REFERENCES.calories.ref, 1)
  return SVG_CIRC * (1 - pct)
}

function buildSegments(data, codes) {
  const amounts = codes.map(code => summaryNutrient(data, code)?.totalAmount ?? 0)
  const total = amounts.reduce((s, v) => s + v, 0) || 1
  let cumulative = 0
  return codes.map((code, i) => {
    const dash = (amounts[i] / total) * SVG_CIRC
    const gap = SVG_CIRC - dash
    const offset = SVG_CIRC - cumulative
    cumulative += dash
    return { code, color: NUTRIENT_COLORS[code], dash, gap, offset }
  })
}

function macroSegments(data) { return buildSegments(data, MACRO_CODES) }
function microSegments(data) { return buildSegments(data, MICRO_CODES) }

function buildIdealSegments(codes) {
  const amounts = codes.map(code => REFERENCES[code]?.ref ?? 0)
  const total = amounts.reduce((s, v) => s + v, 0) || 1
  let cumulative = 0
  return codes.map((code, i) => {
    const dash = (amounts[i] / total) * SVG_CIRC
    const gap = SVG_CIRC - dash
    const offset = SVG_CIRC - cumulative
    cumulative += dash
    return { code, color: NUTRIENT_COLORS[code], dash, gap, offset }
  })
}

const IDEAL_MACRO_SEGS = buildIdealSegments(MACRO_CODES)
const IDEAL_MICRO_SEGS = buildIdealSegments(MICRO_CODES)

function donutLegend(data, codes) {
  return codes.map(code => {
    const n = summaryNutrient(data, code)
    return {
      code,
      name: n?.name ?? code,
      amount: n?.totalAmount ?? 0,
      unit: n?.unit ?? 'g',
      color: NUTRIENT_COLORS[code],
    }
  })
}

function summaryBreakdown(data) {
  const nutrients = data?.nutrients ?? []
  return nutrients.map(n => {
    const ref = REFERENCES[n.code]
    const pct = ref ? Math.min((n.totalAmount / ref.ref) * 100, 100) : null
    const color = pct == null ? '#aaa'
      : pct < 50 ? '#e8a820'
      : pct <= 100 ? '#5a9e56'
      : '#d94f4f'
    return {
      code: n.code,
      name: n.name,
      amount: n.totalAmount,
      unit: n.unit,
      reference: ref?.label ?? '-',
      pct: pct ?? 50,
      color,
    }
  })
}

function severityColor(level) {
  if (level === 'high') return '#d94f4f'
  if (level === 'medium') return '#e8a820'
  return '#5a9e56'
}
</script>
