// Initial template generated by Claude, with wiring up, edits, and function edits done manually with AI guidance
<template>
  <div class="container-fluid px-4 py-3">

    <div class="d-flex justify-content-between align-items-center p-3 mb-3 rounded"
         style="background:#e8f4e6;border:1px solid #5a9e56;">
      <div>
        <h4 style="color:#5a9e56;" class="mb-0">Professional Dashboard</h4>
        <small class="text-secondary">{{ today }} - manage and review your assigned clients</small>
      </div>
      <div class="d-flex align-items-center gap-2">
        <button class="btn btn-gf btn-sm" @click="showInvite = !showInvite">
          {{ showInvite ? 'Cancel' : 'Invite Client' }}
        </button>
      </div>
    </div>

    <div v-if="showInvite" class="add-meal-panel mb-3">
      <h6 class="fw-bold mb-2" style="color:#5a9e56;">Invite a Subscriber</h6>
      <p class="text-muted small mb-2">
        Ask the subscriber for their User ID (visible on their Profile page) and enter it below.
      </p>
      <div class="d-flex gap-2 align-items-end">
        <div style="flex:1;max-width:200px;">
          <label class="form-label form-label-sm">Subscriber User ID</label>
          <input type="number" class="form-control form-control-sm"
                 v-model.number="inviteId" min="1" placeholder="e.g. 42">
        </div>
        <button class="btn btn-gf btn-sm" @click="sendInvite" :disabled="inviteLoading || !inviteId">
          {{ inviteLoading ? '…' : 'Send Invite' }}
        </button>
      </div>
      <div v-if="inviteError" class="alert alert-danger py-2 small mt-2 mb-0">{{ inviteError }}</div>
      <div v-if="inviteSuccess" class="alert alert-success py-2 small mt-2 mb-0">{{ inviteSuccess }}</div>
    </div>

    <div v-if="pendingInvitations.length > 0" class="mb-3">
      <h6 class="fw-bold mb-2" style="color:#5a9e56;">
        Pending Invitations
        <span class="badge ms-1" style="background:#e8a820;font-size:0.7rem;">{{ pendingInvitations.length }}</span>
      </h6>
      <div v-for="inv in pendingInvitations" :key="inv.id"
           class="card card-gf mb-2 p-3 d-flex flex-row align-items-center justify-content-between gap-3">
        <div class="d-flex align-items-center gap-3 flex-grow-1">
          <div class="avatar-circle" style="width:36px;height:36px;font-size:0.8rem;">
            {{ initialsFor(inv.subscriber.fullName) }}
          </div>
          <div>
            <div class="fw-bold small">{{ inv.subscriber.fullName }}</div>
            <div class="text-muted" style="font-size:0.75rem;">
              {{ inv.subscriber.email }} · ID {{ inv.subscriberId }}
            </div>
            <div class="text-muted" style="font-size:0.7rem;">
              Invited {{ formatDate(inv.assignedAt) }} · awaiting response
            </div>
          </div>
        </div>
        <span class="badge" style="background:#e8a820;font-size:0.7rem;">Pending</span>
      </div>
    </div>

    <div class="d-flex justify-content-between align-items-center mb-2">
      <h5 class="fw-bold mb-0" style="color:#5a9e56;">Your Clients</h5>
      <span class="badge" style="background:#5a9e56;font-size:0.75rem;">
        {{ clients.length }} active
      </span>
    </div>

    <div v-if="loading" class="text-center text-muted py-4">
      <small>Loading clients…</small>
    </div>

    <div v-else-if="error" class="alert alert-danger small">{{ error }}</div>

    <div v-else-if="clients.length === 0"
         class="text-center text-muted py-4 border rounded"
         style="border-style:dashed!important;">
      <p class="mb-1">No active clients yet.</p>
      <small>Invite a subscriber using their User ID - they'll appear here once they accept.</small>
    </div>

    <div v-else>
      <div v-for="client in clients" :key="client.id" class="card card-gf mb-2">

        <div class="card-header d-flex justify-content-between align-items-center"
             style="cursor:pointer;"
             @click="toggleClient(client)">
          <div class="d-flex align-items-center gap-3">
            <div class="avatar-circle" style="width:38px;height:38px;font-size:0.85rem;">
              {{ initialsFor(client.subscriber.fullName) }}
            </div>
            <div>
              <div class="fw-bold small">{{ client.subscriber.fullName }}</div>
              <div class="text-muted" style="font-size:0.75rem;">
                {{ client.subscriber.email }} · ID {{ client.subscriberId }}
              </div>
            </div>
          </div>
          <div class="d-flex align-items-center gap-2">
            <button class="btn btn-sm py-0 px-2"
                    style="background:#fde8e8;border:1px solid #d99;color:#c44;"
                    title="Remove client"
                    @click.stop="removeClient(client)">Remove</button>
            <span style="color:#5a9e56;font-weight:bold;">
              {{ expandedId === client.id ? '▲' : '▼' }}
            </span>
          </div>
        </div>

        <div v-if="expandedId === client.id" class="card-body">

          <div class="d-flex gap-2 mb-3 border-bottom pb-2">
            <button v-for="tab in tabs" :key="tab.id"
                    class="btn btn-sm"
                    :class="activeTab[client.id] === tab.id ? 'btn-gf' : 'btn-outline-secondary'"
                    @click="setTab(client, tab.id)">
              {{ tab.label }}
            </button>
          </div>

          <div v-if="activeTab[client.id] === 'dashboard'">
            <div v-if="client.dashboard.loading" class="text-muted small">Loading…</div>
            <div v-else-if="client.dashboard.error" class="alert alert-danger small mb-0">
              {{ client.dashboard.error }}
            </div>
            <div v-else-if="client.dashboard.data">
              <div class="row g-2 mb-3">
                <div class="col-4">
                  <div class="p-2 rounded text-center" style="background:#f0f8f0;border:1px solid #c3e0c3;">
                    <div class="fw-bold" style="color:#5a9e56;font-size:1.1rem;">
                      {{ client.dashboard.data.quickStats?.calories_today ?? 0 }}
                    </div>
                    <div class="text-muted" style="font-size:0.7rem;">kcal today</div>
                  </div>
                </div>
                <div class="col-4">
                  <div class="p-2 rounded text-center" style="background:#f0f8f0;border:1px solid #c3e0c3;">
                    <div class="fw-bold" style="color:#5a9e56;font-size:1.1rem;">
                      {{ client.dashboard.data.quickStats?.meals_logged_today ?? 0 }}
                    </div>
                    <div class="text-muted" style="font-size:0.7rem;">meals today</div>
                  </div>
                </div>
                <div class="col-4">
                  <div class="p-2 rounded text-center" style="background:#f0f8f0;border:1px solid #c3e0c3;">
                    <div class="fw-bold" style="color:#5a9e56;font-size:1.1rem;">
                      {{ client.dashboard.data.quickStats?.days_logged ?? 0 }}
                    </div>
                    <div class="text-muted" style="font-size:0.7rem;">days logged</div>
                  </div>
                </div>
              </div>

              <div class="row g-3">
                <div class="col-md-6">
                  <h6 class="fw-bold mb-2" style="color:#5a9e56;">Today's Diary</h6>
                  <div v-if="recentEntries(client.dashboard.data).length === 0"
                       class="text-muted small">No entries logged today.</div>
                  <ul v-else class="list-unstyled small mb-0">
                    <li v-for="entry in recentEntries(client.dashboard.data)" :key="entry.diaryEntryId"
                        class="mb-1 pb-1 border-bottom">
                      <span class="fw-semibold text-capitalize">{{ entry.mealType }}</span>
                      <span class="text-muted ms-1">- {{ formatDate(entry.consumedAt) }}</span>
                      <span v-if="entry.items?.length" class="text-muted ms-1"
                            style="font-size:0.7rem;">({{ entry.items.length }} item{{ entry.items.length !== 1 ? 's' : '' }})</span>
                    </li>
                  </ul>
                </div>

                <div class="col-md-6">
                  <h6 class="fw-bold mb-2" style="color:#5a9e56;">Today's Nutrition</h6>
                  <div v-if="!(client.dashboard.data.nutritionPreview?.length)"
                       class="text-muted small">No nutrition data yet.</div>
                  <ul v-else class="list-unstyled small mb-0">
                    <li v-for="n in client.dashboard.data.nutritionPreview" :key="n.code"
                        class="mb-1 pb-1 border-bottom d-flex justify-content-between">
                      <span class="fw-semibold">{{ n.name }}</span>
                      <span class="text-muted">{{ n.totalAmount }} {{ n.unit }}</span>
                    </li>
                  </ul>
                </div>

                <div class="col-12" v-if="riskSnapshots(client.dashboard.data).length">
                  <h6 class="fw-bold mb-2" style="color:#5a9e56;">Recent Risk Flags</h6>
                  <ul class="list-unstyled small mb-0">
                    <li v-for="snap in riskSnapshots(client.dashboard.data)" :key="snap.snapshotId"
                        class="mb-1 pb-1 border-bottom">
                      <span class="badge me-2"
                            :style="`background:${severityColor(snap.riskLevel)};font-size:0.65rem;`">
                        {{ snap.riskLevel }}
                      </span>
                      <span class="fw-semibold">{{ snap.rule?.name ?? 'Rule' }}</span>
                      <span class="text-muted ms-1" v-if="snap.reason">- {{ snap.reason }}</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <div v-if="activeTab[client.id] === 'summary'">
            <div class="d-flex gap-2 align-items-end mb-3">
              <div>
                <label class="form-label form-label-sm">Period</label>
                <select class="form-select form-select-sm" v-model="client.summary.period">
                  <option value="daily">Daily</option>
                  <option value="weekly">Weekly</option>
                  <option value="monthly">Monthly</option>
                </select>
              </div>
              <div>
                <label class="form-label form-label-sm">End Date</label>
                <input type="date" class="form-control form-control-sm"
                       v-model="client.summary.endDate">
              </div>
              <button class="btn btn-gf btn-sm" @click="loadSummary(client)"
                      :disabled="client.summary.loading">
                {{ client.summary.loading ? '…' : 'Load' }}
              </button>
            </div>

            <div v-if="client.summary.loading" class="text-muted small">Loading…</div>
            <div v-else-if="client.summary.error" class="alert alert-danger small">{{ client.summary.error }}</div>
            <div v-else-if="client.summary.data">
              <div class="row g-3 mb-3">

                <div class="col-md-4">
                  <div class="card border p-3 text-center h-100">
                    <h6 class="fw-bold mb-2" style="color:#5a9e56;">Calories</h6>
                    <svg viewBox="0 0 160 160" width="140" height="140" style="margin:0 auto;display:block;">
                      <circle cx="80" cy="80" r="62" fill="none" stroke="#e9ecef" stroke-width="18"/>
                      <circle cx="80" cy="80" r="62" fill="none" stroke="#5a9e56" stroke-width="18"
                              stroke-dasharray="389.6"
                              :stroke-dashoffset="calorieOffset(client.summary.data)"
                              stroke-linecap="round"
                              transform="rotate(-90 80 80)"/>
                      <text x="80" y="74" text-anchor="middle" font-size="18" font-weight="bold" fill="#5a9e56">
                        {{ summaryNutrient(client.summary.data, 'calories')?.totalAmount ?? 0 }}
                      </text>
                      <text x="80" y="90" text-anchor="middle" font-size="10" fill="#888">kcal</text>
                    </svg>
                    <div class="mt-2 text-start small text-muted">
                      <div>Eaten: <strong>{{ summaryNutrient(client.summary.data, 'calories')?.totalAmount ?? 0 }} kcal</strong></div>
                      <div>Reference: <strong>2,000 kcal</strong></div>
                    </div>
                  </div>
                </div>

                <div class="col-md-4">
                  <div class="card border p-3 text-center h-100" style="position:relative;">
                    <h6 class="fw-bold mb-2" style="color:#5a9e56;">Macronutrients</h6>
                    <div style="position:absolute;top:8px;right:8px;text-align:center;">
                      <svg viewBox="0 0 160 160" width="60" height="60" style="display:block;">
                        <circle cx="80" cy="80" r="62" fill="none" stroke="#e9ecef" stroke-width="18"/>
                        <template v-for="seg in IDEAL_MACRO_SEGS" :key="seg.code">
                          <circle cx="80" cy="80" r="62" fill="none"
                                  :stroke="seg.color" stroke-width="18"
                                  :stroke-dasharray="`${seg.dash} ${seg.gap}`"
                                  :stroke-dashoffset="seg.offset"
                                  transform="rotate(-90 80 80)"/>
                        </template>
                      </svg>
                      <span style="font-size:0.6rem;color:#888;">Ideal</span>
                    </div>
                    <svg viewBox="0 0 160 160" width="140" height="140" style="margin:0 auto;display:block;">
                      <circle cx="80" cy="80" r="62" fill="none" stroke="#e9ecef" stroke-width="18"/>
                      <template v-for="seg in macroSegments(client.summary.data)" :key="seg.code">
                        <circle cx="80" cy="80" r="62" fill="none"
                                :stroke="seg.color" stroke-width="18"
                                :stroke-dasharray="`${seg.dash} ${seg.gap}`"
                                :stroke-dashoffset="seg.offset"
                                transform="rotate(-90 80 80)"/>
                      </template>
                      <text x="80" y="80" text-anchor="middle" font-size="10" fill="#555">Macros</text>
                    </svg>
                    <div class="mt-2 text-start small">
                      <div v-for="m in donutLegend(client.summary.data, MACRO_CODES)" :key="m.code"
                           class="d-flex align-items-center gap-1 mb-1">
                        <span style="display:inline-block;width:10px;height:10px;border-radius:2px;"
                              :style="`background:${m.color};`"></span>
                        <span class="text-muted">{{ m.name }}:</span>
                        <strong>{{ m.amount }} {{ m.unit }}</strong>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="col-md-4">
                  <div class="card border p-3 text-center h-100" style="position:relative;">
                    <h6 class="fw-bold mb-2" style="color:#5a9e56;">Micronutrients</h6>
                    <div style="position:absolute;top:8px;right:8px;text-align:center;">
                      <svg viewBox="0 0 160 160" width="60" height="60" style="display:block;">
                        <circle cx="80" cy="80" r="62" fill="none" stroke="#e9ecef" stroke-width="18"/>
                        <template v-for="seg in IDEAL_MICRO_SEGS" :key="seg.code">
                          <circle cx="80" cy="80" r="62" fill="none"
                                  :stroke="seg.color" stroke-width="18"
                                  :stroke-dasharray="`${seg.dash} ${seg.gap}`"
                                  :stroke-dashoffset="seg.offset"
                                  transform="rotate(-90 80 80)"/>
                        </template>
                      </svg>
                      <span style="font-size:0.6rem;color:#888;">Ideal</span>
                    </div>
                    <svg viewBox="0 0 160 160" width="140" height="140" style="margin:0 auto;display:block;">
                      <circle cx="80" cy="80" r="62" fill="none" stroke="#e9ecef" stroke-width="18"/>
                      <template v-for="seg in microSegments(client.summary.data)" :key="seg.code">
                        <circle cx="80" cy="80" r="62" fill="none"
                                :stroke="seg.color" stroke-width="18"
                                :stroke-dasharray="`${seg.dash} ${seg.gap}`"
                                :stroke-dashoffset="seg.offset"
                                transform="rotate(-90 80 80)"/>
                      </template>
                      <text x="80" y="80" text-anchor="middle" font-size="10" fill="#555">Micros</text>
                    </svg>
                    <div class="mt-2 text-start small">
                      <div v-for="m in donutLegend(client.summary.data, MICRO_CODES)" :key="m.code"
                           class="d-flex align-items-center gap-1 mb-1">
                        <span style="display:inline-block;width:10px;height:10px;border-radius:2px;"
                              :style="`background:${m.color};`"></span>
                        <span class="text-muted">{{ m.name }}:</span>
                        <strong>{{ m.amount }} {{ m.unit }}</strong>
                      </div>
                    </div>
                  </div>
                </div>

              </div>

              <h6 class="fw-bold mb-2" style="color:#5a9e56;">Full Nutrient Breakdown</h6>
              <div class="table-responsive">
                <table class="table table-sm table-striped border mb-0">
                  <thead style="background:#5a9e56;color:#fff;">
                    <tr>
                      <th class="small">Nutrient</th>
                      <th class="small">Amount</th>
                      <th class="small">Unit</th>
                      <th class="small">Reference</th>
                      <th class="small">Progress</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="row in summaryBreakdown(client.summary.data)" :key="row.code">
                      <td class="small fw-semibold">{{ row.name }}</td>
                      <td class="small">{{ row.amount }}</td>
                      <td class="small text-muted">{{ row.unit }}</td>
                      <td class="small text-muted">{{ row.reference }}</td>
                      <td style="width:120px;">
                        <div class="progress" style="height:8px;">
                          <div class="progress-bar"
                               :style="`width:${row.pct}%;background-color:${row.color};`"></div>
                        </div>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div v-else class="text-muted small">Select a period and end date, then press Load.</div>
          </div>

          <div v-if="activeTab[client.id] === 'goals'">
            <div v-if="client.goals.loading" class="text-muted small">Loading…</div>
            <div v-else-if="client.goals.error" class="alert alert-danger small">{{ client.goals.error }}</div>
            <div v-else>
              <div v-if="(client.goals.data ?? []).length === 0"
                   class="text-muted small mb-3">No goals set.</div>
              <ul v-else class="list-unstyled small mb-3">
                <li v-for="goal in client.goals.data" :key="goal.goalId"
                    class="mb-1 pb-1 border-bottom d-flex justify-content-between align-items-center">
                  <div>
                    <span class="fw-semibold">{{ goal.nutrient?.name ?? goal.notes ?? 'Custom goal' }}</span>
                    <span class="text-muted ms-1">{{ goalRange(goal) }}</span>
                    <span class="badge ms-1"
                          :style="`background:${goalSourceColor(goal.source)};font-size:0.65rem;`">
                      {{ goalSourceLabel(goal.source) }}
                    </span>
                    <div v-if="goal.notes && goal.nutrient" class="text-muted" style="font-size:0.7rem;">
                      {{ goal.notes }}
                    </div>
                  </div>
                  <span class="text-muted" style="font-size:0.7rem;">{{ goalRangeDates(goal) }}</span>
                </li>
              </ul>

              <div class="add-meal-panel">
                <h6 class="fw-bold mb-2" style="color:#5a9e56;">Set a Goal</h6>

                <div class="d-flex flex-wrap gap-1 mb-3">
                  <button v-for="preset in goalPresets" :key="preset.title"
                          class="btn btn-gf-outline btn-sm py-0"
                          @click="applyGoalPreset(client, preset)">
                    {{ preset.title }}
                  </button>
                </div>

                <div class="row g-2 mb-2">
                  <div class="col-md-4">
                    <label class="form-label form-label-sm">Tracked Nutrient</label>
                    <select class="form-select form-select-sm" v-model="client.goalDraft.nutrientId">
                      <option :value="null">No specific nutrient</option>
                      <option v-for="n in nutrients" :key="n.nutrientId" :value="n.nutrientId">
                        {{ n.name }} ({{ n.unit }})
                      </option>
                    </select>
                  </div>
                  <div class="col-md-4">
                    <label class="form-label form-label-sm">
                      Target Min{{ nutrientUnitFor(client.goalDraft.nutrientId) ? ` (${nutrientUnitFor(client.goalDraft.nutrientId)})` : '' }}
                    </label>
                    <input type="number" class="form-control form-control-sm" step="any" min="0"
                           v-model.number="client.goalDraft.targetMin"
                           :disabled="!client.goalDraft.nutrientId">
                  </div>
                  <div class="col-md-4">
                    <label class="form-label form-label-sm">
                      Target Max{{ nutrientUnitFor(client.goalDraft.nutrientId) ? ` (${nutrientUnitFor(client.goalDraft.nutrientId)})` : '' }}
                    </label>
                    <input type="number" class="form-control form-control-sm" step="any" min="0"
                           v-model.number="client.goalDraft.targetMax"
                           :disabled="!client.goalDraft.nutrientId">
                  </div>
                </div>
                <div class="row g-2 mb-2">
                  <div class="col-md-3">
                    <label class="form-label form-label-sm">Start Date</label>
                    <input type="date" class="form-control form-control-sm"
                           v-model="client.goalDraft.startDate">
                  </div>
                  <div class="col-md-3">
                    <label class="form-label form-label-sm">End Date</label>
                    <input type="date" class="form-control form-control-sm"
                           v-model="client.goalDraft.endDate">
                  </div>
                  <div class="col-md-6">
                    <label class="form-label form-label-sm">Notes (required)</label>
                    <input type="text" class="form-control form-control-sm"
                           v-model="client.goalDraft.notes" placeholder="Why are you setting this goal?">
                  </div>
                </div>
                <button class="btn btn-gf btn-sm" @click="setGoal(client)"
                        :disabled="client.goalDraft.saving">
                  {{ client.goalDraft.saving ? '…' : 'Save Goal' }}
                </button>
                <div v-if="client.goalDraft.error" class="alert alert-danger small mt-2 mb-0">
                  {{ client.goalDraft.error }}
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>

  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { apiFetch } from '../auth.js'

const today = new Date().toLocaleDateString('en-GB', {
  weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
})

const tabs = [
  { id: 'dashboard', label: 'Dashboard' },
  { id: 'summary', label: 'Summary' },
  { id: 'goals', label: 'Goals' },
]

const clients = ref([])
const loading = ref(true)
const error = ref('')
const expandedId = ref(null)
const activeTab = reactive({})
const nutrients = ref([])

const goalPresets = [
  { title: 'Calories ≤ 2000', nutrientCode: 'calories', targetMax: 2000, durationDays: 30, notes: 'Stay within daily calorie target' },
  { title: 'Protein ≥ 50g', nutrientCode: 'protein', targetMin: 50, durationDays: 30, notes: 'Hit daily protein target' },
  { title: 'Fibre ≥ 30g', nutrientCode: 'fibre', targetMin: 30, durationDays: 21, notes: 'Reach NHS fibre recommendation' },
  { title: 'Sugar ≤ 30g', nutrientCode: 'sugar', targetMax: 30, durationDays: 30, notes: 'Reduce added sugar' },
  { title: 'Salt ≤ 6g', nutrientCode: 'salt', targetMax: 6, durationDays: 30, notes: 'Lower salt intake' },
]

const showInvite = ref(false)
const inviteId = ref(null)
const inviteLoading = ref(false)
const inviteError = ref('')
const inviteSuccess = ref('')

const pendingInvitations = ref([])

const todayIso = () => new Date().toISOString().slice(0, 10)

function blankClientState() {
  return {
    dashboard: { loading: false, error: '', data: null },
    summary: { loading: false, error: '', data: null, period: 'daily', endDate: todayIso() },
    goals: { loading: false, error: '', data: null },
    goalDraft: {
      nutrientId: null, targetMin: null, targetMax: null,
      startDate: todayIso(), endDate: '', notes: '',
      saving: false, error: '',
    },
  }
}

onMounted(() => {
  loadClients()
  loadNutrients()
  loadPendingInvitations()
})

async function loadPendingInvitations() {
  try {
    const res = await apiFetch('/api/professional/client-invitations')
    const data = await res.json().catch(() => ({}))
    if (res.ok) pendingInvitations.value = data.invitations ?? data.clients ?? []
  } catch {
    // non-critical
  }
}

async function loadNutrients() {
  try {
    const res = await apiFetch('/api/goals/nutrients')
    const data = await res.json().catch(() => ({}))
    if (res.ok) nutrients.value = data.nutrients ?? []
  } catch {
    // non-critical
  }
}

function nutrientUnitFor(nutrientId) {
  if (!nutrientId) return ''
  return nutrients.value.find(n => n.nutrientId === nutrientId)?.unit ?? ''
}

function nutrientIdByCode(code) {
  return nutrients.value.find(n => n.code === code)?.nutrientId ?? null
}

function applyGoalPreset(client, preset) {
  const start = new Date()
  const end = new Date()
  end.setDate(end.getDate() + preset.durationDays)
  client.goalDraft.nutrientId = nutrientIdByCode(preset.nutrientCode)
  client.goalDraft.targetMin = preset.targetMin ?? null
  client.goalDraft.targetMax = preset.targetMax ?? null
  client.goalDraft.startDate = start.toISOString().slice(0, 10)
  client.goalDraft.endDate = end.toISOString().slice(0, 10)
  client.goalDraft.notes = preset.notes
}

function goalSourceLabel(source) {
  if (source === 'professional_defined') return 'pro'
  if (source === 'system_default') return 'system'
  return 'personal'
}

function goalRangeDates(goal) {
  const start = goal.startDate ? new Date(goal.startDate).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' }) : ''
  const end = goal.endDate ? new Date(goal.endDate).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' }) : 'ongoing'
  if (!start) return ''
  return `${start} → ${end}`
}

async function fetchJson(url, options) {
  const res = await apiFetch(url, options)
  const data = await res.json().catch(() => ({}))
  return { ok: res.ok, data, message: data.error || data.message }
}

async function loadResource(state, url, pickData, fallback = 'Failed to load') {
  state.loading = true
  state.error = ''
  try {
    const { ok, data, message } = await fetchJson(url)
    if (!ok) {
      state.error = message || fallback
      return
    }
    state.data = pickData(data)
  } catch {
    state.error = 'Network error'
  } finally {
    state.loading = false
  }
}

async function loadClients() {
  loading.value = true
  error.value = ''
  try {
    const url = '/api/professional/clients'
    const { ok, data, message } = await fetchJson(url)
    if (!ok) {
      error.value = message || 'Failed to load clients'
      return
    }
    clients.value = (data.clients ?? []).map(c => ({ ...c, ...blankClientState() }))
  } catch {
    error.value = 'Network error - could not load clients'
  } finally {
    loading.value = false
  }
}

async function sendInvite() {
  inviteError.value = ''
  inviteSuccess.value = ''
  inviteLoading.value = true
  try {
    const { ok, message } = await fetchJson('/api/professional/client-invitations', {
      method: 'POST',
      body: JSON.stringify({ subscriberId: Number(inviteId.value) }),
    })
    if (!ok) {
      inviteError.value = message || 'Invitation failed'
      return
    }
    inviteSuccess.value = `Invitation sent to user #${inviteId.value}.`
    inviteId.value = null
    await loadPendingInvitations()
  } catch {
    inviteError.value = 'Network error - could not send invitation'
  } finally {
    inviteLoading.value = false
  }
}

async function removeClient(client) {
  if (!confirm(`Remove ${client.subscriber.fullName} from your clients?`)) return
  try {
    const { ok, message } = await fetchJson(`/api/professional/clients/${client.subscriberId}`, {
      method: 'DELETE',
    })
    if (!ok) {
      alert(message || 'Removal failed')
      return
    }
    clients.value = clients.value.filter(c => c.id !== client.id)
    if (expandedId.value === client.id) expandedId.value = null
  } catch {
    alert('Network error - could not remove client')
  }
}

function toggleClient(client) {
  if (expandedId.value === client.id) {
    expandedId.value = null
    return
  }
  expandedId.value = client.id
  if (!activeTab[client.id]) activeTab[client.id] = 'dashboard'
  loadTab(client, activeTab[client.id])
}

function setTab(client, tabId) {
  activeTab[client.id] = tabId
  loadTab(client, tabId)
}

function loadTab(client, tabId) {
  if (tabId === 'dashboard' && !client.dashboard.data && !client.dashboard.loading) {
    loadDashboard(client)
  } else if (tabId === 'goals' && !client.goals.data && !client.goals.loading) {
    loadGoals(client)
  }
}

function loadDashboard(client) {
  return loadResource(
    client.dashboard,
    `/api/professional/clients/${client.subscriberId}/dashboard`,
    d => d.dashboardData ?? d,
    'Failed to load dashboard',
  )
}

async function loadSummary(client) {
  client.summary.data = null
  const params = new URLSearchParams({
    period: client.summary.period,
    endDate: client.summary.endDate,
  })
  await loadResource(
    client.summary,
    `/api/professional/clients/${client.subscriberId}/summary?${params}`,
    d => d.summary ?? d,
    'Failed to load summary',
  )
}

function loadGoals(client) {
  return loadResource(
    client.goals,
    `/api/professional/clients/${client.subscriberId}/goals`,
    d => d.goals ?? d,
    'Failed to load goals',
  )
}

async function setGoal(client) {
  client.goalDraft.error = ''
  client.goalDraft.saving = true
  try {
    const goal = {}
    if (client.goalDraft.nutrientId != null) goal.nutrientId = client.goalDraft.nutrientId
    if (client.goalDraft.targetMin != null) goal.targetMin = client.goalDraft.targetMin
    if (client.goalDraft.targetMax != null) goal.targetMax = client.goalDraft.targetMax
    if (client.goalDraft.startDate) goal.startDate = client.goalDraft.startDate
    if (client.goalDraft.endDate) goal.endDate = client.goalDraft.endDate
    goal.notes = client.goalDraft.notes

    const { ok, message } = await fetchJson(
      `/api/professional/clients/${client.subscriberId}/goals`,
      { method: 'POST', body: JSON.stringify({ goal }) },
    )
    if (!ok) {
      client.goalDraft.error = message || 'Failed to set goal'
      return
    }
    client.goalDraft = {
      nutrientId: null, targetMin: null, targetMax: null,
      startDate: todayIso(), endDate: '', notes: '',
      saving: false, error: '',
    }
    client.goals.data = null
    await loadGoals(client)
  } catch {
    client.goalDraft.error = 'Network error'
  } finally {
    client.goalDraft.saving = false
  }
}

function initialsFor(name) {
  if (!name) return '?'
  return name.trim().split(/\s+/).slice(0, 2).map(p => p[0].toUpperCase()).join('') || '?'
}

function formatDate(value) {
  if (!value) return ''
  const d = new Date(value)
  if (Number.isNaN(d.getTime())) return ''
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
}

function recentEntries(data) {
  const entries = data?.foodDiaryPreview ?? data?.recentDiaryEntries ?? data?.diaryEntries ?? data?.entries ?? []
  return entries.filter(e => e.items?.length > 0)
}

function riskSnapshots(data) {
  return data?.riskSnapshots ?? data?.recentRisks ?? []
}

function goalRange(goal) {
  const min = goal.targetMin
  const max = goal.targetMax
  const unit = goal.nutrient?.unit ? ` ${goal.nutrient.unit}` : ''
  if (min != null && max != null) return `${min}–${max}${unit}`
  if (min != null) return `≥ ${min}${unit}`
  if (max != null) return `≤ ${max}${unit}`
  return ''
}

function goalSourceColor(source) {
  if (source === 'professional_defined') return '#5a9e56'
  if (source === 'user_defined') return '#3a7fbf'
  return '#888'
}

// NHS reference intakes used for progress bars
const REFERENCES = {
  calories:      { ref: 2000, unit: 'kcal', label: '2,000 kcal' },
  protein:       { ref: 50,   unit: 'g',    label: '50 g' },
  carbohydrates: { ref: 260,  unit: 'g',    label: '260 g' },
  fat:           { ref: 70,   unit: 'g',    label: '70 g' },
  fibre:         { ref: 30,   unit: 'g',    label: '30 g' },
  sugar:         { ref: 30,   unit: 'g',    label: '≤ 30 g' },
  salt:          { ref: 6,    unit: 'g',    label: '≤ 6 g' },
}

const MACRO_CODES = ['carbohydrates', 'protein', 'fat']
const MICRO_CODES = ['fibre', 'sugar', 'salt']

const NUTRIENT_COLORS = {
  carbohydrates: '#4e9af1',
  protein:       '#5a9e56',
  fat:           '#e8a820',
  fibre:         '#a86cc1',
  sugar:         '#d94f4f',
  salt:          '#6ec6c2',
}

function summaryNutrient(data, code) {
  return data?.nutrients?.find(n => n.code === code)
}

const SVG_CIRC = 2 * Math.PI * 62  // ≈ 389.6

function calorieOffset(data) {
  const eaten = summaryNutrient(data, 'calories')?.totalAmount ?? 0
  const pct = Math.min(eaten / REFERENCES.calories.ref, 1)
  return SVG_CIRC * (1 - pct)
}

function buildSegments(data, codes) {
  const amounts = codes.map(code => summaryNutrient(data, code)?.totalAmount ?? 0)
  const total = amounts.reduce((s, v) => s + v, 0) || 1
  let cumulative = 0
  return codes.map((code, i) => {
    const dash = (amounts[i] / total) * SVG_CIRC
    const gap = SVG_CIRC - dash
    const offset = SVG_CIRC - cumulative
    cumulative += dash
    return { code, color: NUTRIENT_COLORS[code], dash, gap, offset }
  })
}

function macroSegments(data) { return buildSegments(data, MACRO_CODES) }
function microSegments(data) { return buildSegments(data, MICRO_CODES) }

function buildIdealSegments(codes) {
  const amounts = codes.map(code => REFERENCES[code]?.ref ?? 0)
  const total = amounts.reduce((s, v) => s + v, 0) || 1
  let cumulative = 0
  return codes.map((code, i) => {
    const dash = (amounts[i] / total) * SVG_CIRC
    const gap = SVG_CIRC - dash
    const offset = SVG_CIRC - cumulative
    cumulative += dash
    return { code, color: NUTRIENT_COLORS[code], dash, gap, offset }
  })
}

const IDEAL_MACRO_SEGS = buildIdealSegments(MACRO_CODES)
const IDEAL_MICRO_SEGS = buildIdealSegments(MICRO_CODES)

function donutLegend(data, codes) {
  return codes.map(code => {
    const n = summaryNutrient(data, code)
    return {
      code,
      name: n?.name ?? code,
      amount: n?.totalAmount ?? 0,
      unit: n?.unit ?? 'g',
      color: NUTRIENT_COLORS[code],
    }
  })
}

function summaryBreakdown(data) {
  const nutrients = data?.nutrients ?? []
  return nutrients.map(n => {
    const ref = REFERENCES[n.code]
    const pct = ref ? Math.min((n.totalAmount / ref.ref) * 100, 100) : null
    const color = pct == null ? '#aaa'
      : pct < 50 ? '#e8a820'
      : pct <= 100 ? '#5a9e56'
      : '#d94f4f'
    return {
      code: n.code,
      name: n.name,
      amount: n.totalAmount,
      unit: n.unit,
      reference: ref?.label ?? '-',
      pct: pct ?? 50,
      color,
    }
  })
}

function severityColor(level) {
  if (level === 'high') return '#d94f4f'
  if (level === 'medium') return '#e8a820'
  return '#5a9e56'
}
</script>
