// Initial template generated by Claude, with wiring up, edits, and function edits done manually with AI guidance
<template>
  <div class="container-fluid px-4 py-4">

    <div class="p-5 pt-3 rounded text-center">
      <h2 class="fw-bold mb-4" style="color:#1b4d1b;font-size:1.75rem;">Recipe Library</h2>
      <div class="d-flex justify-content-center gap-2">
        <input type="text" class="form-control"
               style="max-width:500px;border:1px solid #d4e7d4;border-radius:8px;padding:0.625rem 1rem;font-size:0.9375rem;"
               placeholder="Search recipes..."
               v-model="searchQuery"
               @input="currentPage = 1">
        <button class="btn fw-semibold" style="background:#1b4d1b;color:#ffffff;border:none;padding:0.625rem 1.5rem;border-radius:8px;font-size:0.9375rem;">Search</button>
      </div>
    </div>

    <div class="mb-5" style="height:1px;background:linear-gradient(to right, transparent, #d4e7d4 20%, #d4e7d4 80%, transparent);margin:0 auto;max-width:80%;"></div>

    <div v-if="loadError" class="alert alert-danger mb-4" style="border-radius:8px;">{{ loadError }}</div>

    <div class="d-flex justify-content-between align-items-center mb-4 pb-3" style="border-bottom:1px solid #f3f4f6;">
      <div class="d-flex gap-2">
        <button v-for="tab in tabs" :key="tab.id"
                class="btn"
                :style="activeTab === tab.id ? 'background:#1b4d1b;color:#fff;border:none;padding:0.5rem 1rem;border-radius:8px;font-size:0.875rem;font-weight:500;' : 'background:#f3f4f6;color:#6b7280;border:none;padding:0.5rem 1rem;border-radius:8px;font-size:0.875rem;font-weight:500;'"
                @click="switchTab(tab.id)">
          {{ tab.label }}
        </button>
      </div>
      <small style="color:#6b7280;font-size:0.875rem;">
        <span v-if="loading">Loading…</span>
        <span v-else>Showing {{ filteredRecipes.length }} recipes</span>
      </small>
    </div>

    <div v-if="loading" class="text-center py-5" style="color:#9ca3af;"><small>Loading recipes…</small></div>

    <template v-else>
      <div class="row g-4 mb-4">
        <div class="col-lg-4 col-md-6" v-for="recipe in pagedRecipes" :key="recipe.recipeId">
          <div class="h-100 rounded" style="background:#fff;box-shadow:0 2px 8px rgba(0,0,0,0.1);border-radius:16px;overflow:hidden;transition:transform 0.2s,box-shadow 0.2s;"
               @mouseenter="$event.currentTarget.style.transform='translateY(-4px)';$event.currentTarget.style.boxShadow='0 4px 16px rgba(0,0,0,0.15)'"
               @mouseleave="$event.currentTarget.style.transform='translateY(0)';$event.currentTarget.style.boxShadow='0 2px 8px rgba(0,0,0,0.1)'">

            <div style="position:relative;overflow:hidden;height:200px;">
              <img :src="recipe.image || '/src/assets/hero.png'" :alt="recipe.title"
                   style="width:100%;height:100%;object-fit:cover;" />
            </div>

            <div class="p-3">
              <div class="d-flex justify-content-between align-items-start">
                <h6 class="fw-bold mb-0" style="color:#1b4d1b;font-size:1rem;line-height:1.3;flex:1;">{{ recipe.title }}</h6>
                <button class="p-0 ms-2"
                        style="cursor:pointer;font-size:1.375rem;line-height:1;border:none;background:none;outline:none;transition:color 0.2s;"
                        :title="recipe.isFavorited ? 'Remove from favourites' : 'Save to favourites'"
                        @click.stop="toggleFavorite(recipe)"
                        @mouseenter="$event.currentTarget.style.color='#d94f4f'"
                        @mouseleave="$event.currentTarget.style.color=recipe.isFavorited ? '#d94f4f' : '#ccc'"
                        :style="recipe.isFavorited ? 'color:#d94f4f;' : 'color:#ccc;'">
                  {{ recipe._favLoading ? '…' : '♥' }}
                </button>
              </div>

              <div class="mb-2" style="color:#6b7280;font-size:0.8125rem;">
                {{ recipe.category }} · {{ recipe.cuisine }}
              </div>

              <div class="mb-2" style="color:#6b7280;font-size:0.8125rem;">
                {{ recipe.kcal }} kcal · P:{{ recipe.protein }}g · C:{{ recipe.carbs }}g · F:{{ recipe.fat }}g
              </div>
              
              <div class="d-flex align-items-center gap-3 mb-3" style="color:#6b7280;font-size:0.875rem;">
                <div class="d-flex align-items-center gap-1">
                  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <circle cx="12" cy="12" r="10"/>
                    <polyline points="12 6 12 12 16 14"/>
                  </svg>
                  <span>{{ recipe.cookTime }}</span>
                </div>
                <div class="d-flex align-items-center gap-1">
                  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/>
                    <circle cx="12" cy="7" r="4"/>
                  </svg>
                  <span>{{ recipe.ingredientDetails?.length ?? 0 }} items</span>
                </div>
              </div>

              <div class="d-flex gap-2">
                <button class="btn fw-semibold flex-fill" 
                        style="background:#1b4d1b;color:#fff;border:none;padding:0.5rem 0.875rem;border-radius:8px;font-size:0.875rem;"
                        @click="viewRecipe(recipe)">
                  View Recipe
                </button>
                <button class="btn fw-semibold flex-fill" 
                        style="background:#f3f4f6;color:#1b4d1b;border:none;padding:0.5rem 0.875rem;border-radius:8px;font-size:0.875rem;"
                        @click="pickMeal(recipe)">
                  Add to Diary
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div v-if="filteredRecipes.length === 0 && !loading"
           class="text-center text-muted py-5 border rounded"
           style="border-style:dashed!important;">
        <p class="mb-1">{{ activeTab === 'fav' ? 'No favourites saved yet.' : 'No recipes match your search.' }}</p>
      </div>

    <div class="d-flex justify-content-center gap-1 mb-4">
      <button class="btn btn-outline-secondary btn-sm"
              :disabled="currentPage === 1"
              @click="currentPage--">‹</button>

      <template v-for="item in pageItems" :key="item">
        <span v-if="item === '...'" class="btn btn-sm disabled">…</span>
        <button v-else
                class="btn btn-sm"
                :class="item === currentPage ? 'btn-gf' : 'btn-outline-secondary'"
                @click="currentPage = item">{{ item }}</button>
      </template>

      <button class="btn btn-outline-secondary btn-sm"
              :disabled="currentPage === totalPages"
              @click="currentPage++">›</button>
    </div>

    <div v-if="selectedRecipe"
         class="p-4 rounded mb-4"
         style="background:#fff;border:1px solid #e5e7eb;box-shadow:0 2px 8px rgba(0,0,0,0.1);border-radius:16px;">
      <div class="d-flex justify-content-between align-items-start mb-4">
        <h4 class="fw-bold mb-0" style="color:#1b4d1b;">{{ selectedRecipe.title }}</h4>
        <button class="btn btn-sm" style="background:#f3f4f6;color:#6b7280;border:none;padding:0.5rem 1rem;border-radius:8px;" @click="selectedRecipe = null">Close</button>
      </div>
      
      <div class="row g-4">

        <div class="col-md-4">
          <img :src="selectedRecipe.image || '/src/assets/placeholder.jpg'" :alt="selectedRecipe.title"
               class="rounded mb-3" style="width:100%;height:240px;object-fit:cover;border-radius:12px;" />
          
          <div class="d-flex align-items-center gap-3 mb-3" style="color:#6b7280;font-size:0.875rem;">
            <div class="d-flex align-items-center gap-1">
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <circle cx="12" cy="12" r="10"/>
                <polyline points="12 6 12 12 16 14"/>
              </svg>
              <span>{{ selectedRecipe.cookTime }}</span>
            </div>
            <div class="d-flex align-items-center gap-1">
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path d="M12 2L2 7l10 5 10-5-10-5z"/>
                <path d="M2 17l10 5 10-5M2 12l10 5 10-5"/>
              </svg>
              <span>{{ selectedRecipe.kcal }} kcal</span>
            </div>
            <span class="badge" style="background:#f3f4f6;color:#1b4d1b;padding:0.25rem 0.5rem;border-radius:6px;font-size:0.75rem;">{{ selectedRecipe.servings }} servings</span>
          </div>

          <div class="d-flex gap-2 mb-3">
            <button class="btn fw-semibold flex-fill"
                    style="background:#1b4d1b;color:#fff;border:none;padding:0.625rem 1rem;border-radius:8px;font-size:0.875rem;"
                    :disabled="selectedRecipe._favLoading"
                    @click="toggleFavorite(selectedRecipe)">
              {{ selectedRecipe._favLoading ? '…' : (selectedRecipe.isFavorited ? '♥ Saved' : '♥ Save') }}
            </button>
            <button class="btn fw-semibold flex-fill" 
                    style="background:#f3f4f6;color:#1b4d1b;border:none;padding:0.625rem 1rem;border-radius:8px;font-size:0.875rem;"
                    @click="pickMeal(selectedRecipe)">
              Add to Diary
            </button>
          </div>

          <div class="p-3 rounded" style="background:#f9fafb;">
            <h6 class="fw-bold mb-2" style="color:#1b4d1b;font-size:0.9375rem;">Nutrition Per Serving</h6>
            <div style="font-size:0.875rem;color:#6b7280;">
              <div class="d-flex justify-content-between mb-1">
                <span>Calories</span>
                <strong style="color:#1b4d1b;">{{ selectedRecipe.kcal }} kcal</strong>
              </div>
              <div class="d-flex justify-content-between mb-1">
                <span>Protein</span>
                <strong style="color:#1b4d1b;">{{ selectedRecipe.protein }}g</strong>
              </div>
              <div class="d-flex justify-content-between mb-1">
                <span>Carbs</span>
                <strong style="color:#1b4d1b;">{{ selectedRecipe.carbs }}g</strong>
              </div>
              <div v-if="selectedRecipe.sugars != null" class="d-flex justify-content-between mb-1 ms-2">
                <span style="font-size:0.8125rem;">of which sugars</span>
                <strong style="color:#1b4d1b;font-size:0.8125rem;">{{ selectedRecipe.sugars }}g</strong>
              </div>
              <div class="d-flex justify-content-between mb-1">
                <span>Fat</span>
                <strong style="color:#1b4d1b;">{{ selectedRecipe.fat }}g</strong>
              </div>
              <div v-if="selectedRecipe.saturatedFat != null" class="d-flex justify-content-between mb-1 ms-2">
                <span style="font-size:0.8125rem;">of which saturated</span>
                <strong style="color:#1b4d1b;font-size:0.8125rem;">{{ selectedRecipe.saturatedFat }}g</strong>
              </div>
              <div v-if="selectedRecipe.fibre != null" class="d-flex justify-content-between mb-1">
                <span>Fibre</span>
                <strong style="color:#1b4d1b;">{{ selectedRecipe.fibre }}g</strong>
              </div>
              <div v-if="selectedRecipe.salt != null" class="d-flex justify-content-between">
                <span>Salt</span>
                <strong style="color:#1b4d1b;">{{ selectedRecipe.salt }}g</strong>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <h6 class="fw-bold mb-3" style="color:#1b4d1b;font-size:1rem;">Ingredients</h6>
          <ul class="ps-3 mb-4" style="font-size:0.875rem;color:#6b7280;">
            <li v-for="(ing, i) in (selectedRecipe.ingredientDetails ?? [])" :key="i" class="mb-2">
              {{ ing.quantity }} {{ ing.name }}
            </li>
          </ul>

          <h6 class="fw-bold mb-3" style="color:#1b4d1b;font-size:1rem;">Method</h6>
          <ol class="ps-3 mb-0" style="font-size:0.875rem;color:#6b7280;">
            <li v-for="(step, i) in selectedRecipeSteps" :key="i" class="mb-2">{{ step }}</li>
          </ol>
        </div>

        <div class="col-md-4">
          <h6 class="fw-bold mb-3" style="color:#1b4d1b;font-size:1rem;">
            Reviews
            <span v-if="selectedRecipe.averageRating != null" class="ms-2 fw-normal" style="font-size:0.875rem;color:#6b7280;">
              ★ {{ selectedRecipe.averageRating.toFixed(1) }} ({{ selectedRecipe.reviewCount }})
            </span>
          </h6>

          <div v-if="(selectedRecipe.reviews ?? []).length > 0" class="mb-3" style="max-height:400px;overflow-y:auto;">
            <div v-for="rev in selectedRecipe.reviews" :key="rev.reviewId"
                 class="p-3 mb-2 rounded" style="background:#f9fafb;border:1px solid #e5e7eb;">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <span style="color:#fbbf24;font-size:0.875rem;">{{ '★'.repeat(rev.rating) }}{{ '☆'.repeat(5 - rev.rating) }}</span>
                <small style="color:#9ca3af;font-size:0.8125rem;">{{ formatDate(rev.createdAt) }}</small>
              </div>
              <div v-if="rev.comment" style="font-size:0.875rem;color:#6b7280;">{{ rev.comment }}</div>
            </div>
          </div>
          <div v-else class="mb-3" style="color:#9ca3af;font-size:0.875rem;">No reviews yet — be the first!</div>

          <div v-if="!userReviewExists" class="p-3 rounded" style="background:#f9fafb;border:1px solid #e5e7eb;">
            <div class="d-flex align-items-center gap-2 mb-2">
              <span class="fw-semibold" style="font-size:0.875rem;color:#1b4d1b;">Rate this recipe:</span>
              <span v-for="star in 5" :key="star"
                    style="cursor:pointer;font-size:1.2rem;"
                    :style="star <= reviewDraft.rating ? 'color:#fbbf24;' : 'color:#ccc;'"
                    @click="reviewDraft.rating = star">★</span>
            </div>
            <textarea class="form-control mb-2" rows="2"
                      placeholder="Leave a comment (optional)…"
                      v-model="reviewDraft.comment"
                      style="border:1px solid #d4e7d4;border-radius:8px;padding:0.625rem;font-size:0.875rem;"></textarea>
            <div v-if="reviewError" class="mb-2" style="color:#d94f4f;font-size:0.875rem;">{{ reviewError }}</div>
            <button class="btn fw-semibold w-100"
                    style="background:#1b4d1b;color:#fff;border:none;padding:0.5rem 1rem;border-radius:8px;font-size:0.875rem;"
                    :disabled="reviewDraft.rating === 0 || reviewSubmitting"
                    @click="submitReview">
              {{ reviewSubmitting ? 'Submitting…' : 'Submit Review' }}
            </button>
          </div>
          <div v-else class="p-3 rounded" style="background:#f9fafb;color:#9ca3af;font-size:0.875rem;">You have already reviewed this recipe.</div>
        </div>

      </div>
    </div>

    <Teleport to="body">
      <div v-if="pendingRecipe"
           style="position:fixed;inset:0;background:rgba(0,0,0,0.45);z-index:1050;display:flex;align-items:center;justify-content:center;"
           @click.self="pendingRecipe = null">
        <div class="p-4 rounded bg-white shadow" style="min-width:300px;max-width:380px;">
          <h6 class="fw-bold mb-1" style="color:#5a9e56;">Add to Diary</h6>
          <p class="small text-muted mb-3">{{ pendingRecipe.title }} - choose a meal:</p>
          <div class="d-grid gap-2">
            <button v-for="meal in meals" :key="meal.id"
                    class="btn btn-gf"
                    @click="confirmAdd(meal.id)">
              {{ meal.label }}
            </button>
          </div>
          <button class="btn btn-outline-secondary btn-sm w-100 mt-3"
                  @click="pendingRecipe = null">Cancel</button>
        </div>
      </div>
    </Teleport>

  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { recipes, meals, addRecipeToDiary } from '../diaryStore.js'

const PAGE_SIZE = 6

const searchQuery = ref('')
const activeTab = ref('all')
const selectedRecipe = ref(null)
const currentPage = ref(1)

const pendingRecipe = ref(null)

const tabs = [
  { id: 'all', label: 'All Recipes' },
  { id: 'fav', label: 'My Favourites' },
]

const filteredRecipes = computed(() => {
  let result = recipes.value
  if (activeTab.value === 'fav') result = result.filter(r => r.saved)
  if (searchQuery.value) {
    const q = searchQuery.value.toLowerCase()
    result = result.filter(r => r.title.toLowerCase().includes(q))
  }
  return result
})

const totalPages = computed(() => Math.max(1, Math.ceil(filteredRecipes.value.length / PAGE_SIZE)))

const pagedRecipes = computed(() => {
  const start = (currentPage.value - 1) * PAGE_SIZE
  return filteredRecipes.value.slice(start, start + PAGE_SIZE)
})

const pageItems = computed(() => {
  const total = totalPages.value
  const cur = currentPage.value
  const items = []

  for (let p = 1; p <= total; p++) {
    if (p === 1 || p === total || (p >= cur - 1 && p <= cur + 1)) {
      items.push(p)
    } else if (items[items.length - 1] !== '...') {
      items.push('...')
    }
  }
  return items
})

function viewRecipe(recipe) {
  selectedRecipe.value = recipe
  window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' })
}

function pickMeal(recipe) {
  pendingRecipe.value = recipe
}

function confirmAdd(mealId) {
  addRecipeToDiary(pendingRecipe.value, mealId)
  pendingRecipe.value = null
}
</script>
